import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { getEffectiveRole } from "@/lib/effective-role";
import { approveSupervisorOverride, decideAdminOverride } from "@/app/live/actions";

export const dynamic="force-dynamic";
export const revalidate=0;

function fmt(value:string|null){return value?new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:"America/New_York"}).format(new Date(value)):"—";}

export default async function LiveAdminPage(){
 const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)redirect("/login");
 const{data:p}=await s.from("profiles").select("role,preview_role").eq("id",user.id).single();const role=getEffectiveRole(p?.role,p?.preview_role);if(role!=="admin"&&role!=="supervisor")redirect("/dashboard");
 const db=createAdminClient();
 const[{data:usage},{data:extensions},{data:profiles},{data:sessions},{data:studies},{data:groups}]=await Promise.all([
   db.from("lf_live_monthly_usage").select("usage_month,live_sessions,participant_minutes").order("usage_month",{ascending:false}).limit(12),
   db.from("study_session_extensions").select("id,session_id,requested_by,extension_level,reason,requested_minutes,status,decided_by,requested_at,decided_at,metadata").order("requested_at",{ascending:false}).limit(100),
   db.from("profiles").select("id,full_name,email,role"),
   db.from("study_sessions").select("id,bible_study_id,group_id,facilitator_user_id,scheduled_start,live_started_at,live_ended_at,live_participant_minutes"),
   db.from("bible_studies").select("id,title"),
   db.from("study_groups").select("id,name")
 ]);
 const profileMap=new Map((profiles||[]).map(x=>[x.id,x]));const sessionMap=new Map((sessions||[]).map(x=>[x.id,x]));const studyMap=new Map((studies||[]).map(x=>[x.id,x]));const groupMap=new Map((groups||[]).map(x=>[x.id,x]));
 const currentMonth=(usage||[])[0];const used=Number(currentMonth?.participant_minutes||0);const freeBudget=10000;const percent=Math.min(100,Math.round((used/freeBudget)*100));
 return <main className="lfp-page pb-24"><div className="lfp-shell py-10"><Link href="/admin" className="text-sm font-black text-indigo-700">← Admin Center</Link><div className="mt-6"><p className="lfp-eyebrow">L&F Live</p><h1 className="mt-2 text-4xl font-black">Usage & Extensions</h1><p className="mt-3 max-w-3xl text-slate-600">Review participant-minute usage, facilitator extensions, supervisor approvals and administrator overrides.</p></div>
 <section className="mt-8 grid gap-4 lg:grid-cols-3"><div className="lfp-card p-6 lg:col-span-2"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-widest text-indigo-700">Current monthly usage</p><p className="mt-2 text-4xl font-black">{used.toLocaleString()} <span className="text-lg text-slate-500">/ {freeBudget.toLocaleString()}</span></p><p className="mt-1 text-sm text-slate-500">participant-minutes tracked</p></div><p className="text-2xl font-black">{percent}%</p></div><div className="mt-5 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-700" style={{width:`${percent}%`}}/></div><p className="mt-3 text-sm font-bold text-slate-600">{Math.max(0,freeBudget-used).toLocaleString()} free participant-minutes remain before paid usage.</p></div><div className="lfp-card p-6"><p className="text-xs font-black uppercase tracking-widest text-violet-700">This month</p><p className="mt-2 text-4xl font-black">{Number(currentMonth?.live_sessions||0)}</p><p className="mt-1 text-sm text-slate-500">L&F Live sessions started</p></div></section>
 <section className="mt-10"><h2 className="text-2xl font-black">Extension & override log</h2><div className="mt-4 grid gap-3">{!(extensions||[]).length&&<div className="rounded-2xl border border-dashed bg-white p-6 text-sm font-bold text-slate-500">No L&F Live extensions have been recorded yet.</div>}{(extensions||[]).map((ext:any)=>{const session=sessionMap.get(ext.session_id) as any;const study=session?studyMap.get(session.bible_study_id) as any:null;const group=session?groupMap.get(session.group_id) as any:null;const requester=profileMap.get(ext.requested_by) as any;const decider=ext.decided_by?profileMap.get(ext.decided_by) as any:null;return <article key={ext.id} className="lfp-card p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-widest text-indigo-700">{ext.extension_level.replaceAll("_"," ")}</p><h3 className="mt-1 text-lg font-black">{study?.title||"Live Study"}{group?` · ${group.name}`:""}</h3><p className="mt-1 text-sm text-slate-500">Requested by {requester?.full_name||requester?.email||"Unknown"} · {fmt(ext.requested_at)} ET</p></div><span className={`rounded-full px-3 py-1 text-xs font-black uppercase ${ext.status==="approved"?"bg-emerald-50 text-emerald-700":ext.status==="pending"?"bg-amber-50 text-amber-800":"bg-slate-100 text-slate-600"}`}>{ext.status}</span></div><div className="mt-4 rounded-2xl bg-slate-50 p-4"><p className="text-xs font-black uppercase tracking-widest text-slate-500">Reason</p><p className="mt-2 font-bold text-slate-800">{ext.reason}</p></div><div className="mt-4 flex flex-wrap items-center gap-3 text-sm text-slate-600"><span><strong>{ext.requested_minutes}</strong> minutes requested</span>{decider&&<span>· Decided by <strong>{decider.full_name||decider.email}</strong></span>}{ext.decided_at&&<span>· {fmt(ext.decided_at)} ET</span>}</div>{ext.extension_level==="facilitator_15"&&ext.status==="approved"&&role==="supervisor"&&<form action={async()=>{"use server";await approveSupervisorOverride(ext.id)}} className="mt-4"><button className="rounded-xl bg-indigo-700 px-4 py-2 text-sm font-black text-white">Approve +15 to 105 minutes</button></form>}{ext.extension_level==="admin_override"&&ext.status==="pending"&&role==="admin"&&<div className="mt-4 flex gap-2"><form action={async()=>{"use server";await decideAdminOverride(ext.id,true)}}><button className="rounded-xl bg-emerald-700 px-4 py-2 text-sm font-black text-white">Approve</button></form><form action={async()=>{"use server";await decideAdminOverride(ext.id,false)}}><button className="rounded-xl border px-4 py-2 text-sm font-black">Deny</button></form></div>}</article>})}</div></section>
 </div></main>
}
