export type GeographyExercise={id:string;title:string;passage:string;place:string;skill:string;question:string;choices:string[];correct:string;teaching:string;mapHabit:string};
export const geographyFoundations={
 title:"Geography Foundations",
 description:"Learn where biblical events happen, then ask the more important question: what does this location help explain in the passage?",
 exercises:[
 {id:"galilee",title:"A Ministry Around the Lake",passage:"Mark 1:14–20; 4:35–41",place:"Sea of Galilee",skill:"Water & livelihood",question:"Which body of water forms the setting for many fishing, crossing, and storm scenes in the Gospels?",choices:["Sea of Galilee","Dead Sea","Mediterranean Sea","Red Sea"],correct:"Sea of Galilee",teaching:"The Sea of Galilee is a freshwater lake in northern Israel. Fishing supported communities around it, and Jesus' Galilean ministry repeatedly moves along or across its shores. Knowing the setting connects calling fishermen, boat travel, storms, and movement between communities without making geography the point of every story.",mapHabit:"When a passage names water, ask whether it functions as livelihood, route, boundary, danger, or simply setting. Let the narrative tell you which matters."},
 {id:"nazareth",title:"Home and Reputation",passage:"Luke 4:16–30",place:"Nazareth",skill:"Hometown setting",question:"Which Galilean town does Luke identify as the place where Jesus had been brought up?",choices:["Nazareth","Bethany","Jericho","Caesarea"],correct:"Nazareth",teaching:"Luke explicitly calls Nazareth the place where Jesus had been brought up. That hometown setting sharpens the synagogue scene: the listeners know His local background and react to His claims. Geography matters here because familiarity is part of the narrative tension.",mapHabit:"Do not stop at locating a town. Ask whether the author uses hometown, region, border, or destination to create a social expectation in the scene."},
 {id:"samaria",title:"A Region With a History",passage:"John 4:1–42",place:"Samaria",skill:"Region & social boundary",question:"Why does Samaria matter to the encounter between Jesus and the Samaritan woman?",choices:["Jewish-Samaritan history created a meaningful social and religious boundary","Samaria was outside all Roman control","No Jewish person could physically enter the region","Only priests were permitted to live there"],correct:"Jewish-Samaritan history created a meaningful social and religious boundary",teaching:"John 4 itself flags the Jewish-Samaritan divide. The region is therefore more than a dot on a map: inherited religious and ethnic tensions give force to Jesus' conversation and the Samaritan response. Avoid exaggerating the divide into claims that Jews universally could not enter Samaria.",mapHabit:"When geography overlaps with people groups, use the passage's own social signals first. Historical background should clarify the encounter, not turn nuanced relations into absolute rules."},
 {id:"jerusalem",title:"Going Up to Jerusalem",passage:"Luke 18:31; 19:28",place:"Jerusalem",skill:"Elevation & destination",question:"Why can Scripture speak naturally of “going up” to Jerusalem?",choices:["Jerusalem sits in elevated hill country","Jerusalem is always north of every traveler","The phrase means only spiritual improvement","Ancient maps placed Jerusalem at the top"],correct:"Jerusalem sits in elevated hill country",teaching:"Jerusalem lies in the Judean hill country, so travelers can literally ascend toward it. The city is also Israel's temple and royal center, giving journeys there theological weight. Physical elevation explains the ordinary travel language; context determines when authors also invest the destination with larger significance.",mapHabit:"Directional language can describe terrain, not just compass direction. Check elevation and route before assuming “up” means north or is purely figurative."},
 {id:"acts-world",title:"The Gospel Moves Through a Network",passage:"Acts 13:1–14:28",place:"Eastern Roman world",skill:"Routes, cities & provinces",question:"What geographical network helps explain the movement of Paul's missionary journeys in Acts?",choices:["Cities, roads, ports, and provinces of the eastern Roman world","One isolated desert settlement","Only the villages surrounding Jerusalem","A direct route through northern Europe"],correct:"Cities, roads, ports, and provinces of the eastern Roman world",teaching:"Acts follows mission through real urban centers, sea routes, roads, islands, and Roman provinces. Geography helps readers see both the practical movement of the missionaries and Luke's expanding narrative horizon from Jerusalem toward the wider nations.",mapHabit:"For a journey narrative, trace origin, stops, barriers, and destination. Then ask why the author tells you about movement instead of treating every place-name as trivia."}
 ] as GeographyExercise[]
};