import { NextRequest,NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { getEffectiveRole } from "@/lib/effective-role";

type RoomMode="gather"|"teach"|"discuss";
const roomModes=new Set<RoomMode>(["gather","teach","discuss"]);

async function access(sessionId:string){const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)return null;const db=createAdminClient();const[{data:p},{data:ss},{data:part}]=await Promise.all([db.from("profiles").select("role,preview_role").eq("id",user.id).maybeSingle(),db.from("study_sessions").select("id,facilitator_user_id,created_by,live_slide_index,live_slide_updated_at,live_room_mode").eq("id",sessionId).maybeSingle(),db.from("study_session_participants").select("study_session_id").eq("study_session_id",sessionId).eq("user_id",user.id).maybeSingle()]);if(!ss)return null;const role=getEffectiveRole(p?.role,p?.preview_role);const facilitator=role==="admin"||ss.facilitator_user_id===user.id||(!ss.facilitator_user_id&&ss.created_by===user.id);if(!part&&!facilitator)return null;return{db,ss,facilitator};}
export async function GET(_request:NextRequest,{params}:{params:Promise<{sessionId:string}>}){const{sessionId}=await params;const ctx=await access(sessionId);if(!ctx)return NextResponse.json({error:"Not authorized"},{status:403});return NextResponse.json({slideIndex:ctx.ss.live_slide_index||0,mode:ctx.ss.live_room_mode||"gather",updatedAt:ctx.ss.live_slide_updated_at||null},{headers:{"Cache-Control":"no-store"}});}
export async function POST(request:NextRequest,{params}:{params:Promise<{sessionId:string}>}){const{sessionId}=await params;const ctx=await access(sessionId);if(!ctx?.facilitator)return NextResponse.json({error:"Facilitator access required"},{status:403});const body=await request.json().catch(()=>({}));const slideIndex=Math.max(0,Math.floor(Number(body.slideIndex)||0));const requestedMode=String(body.mode||ctx.ss.live_room_mode||"gather") as RoomMode;const mode=roomModes.has(requestedMode)?requestedMode:"gather";const now=new Date().toISOString();const{error}=await ctx.db.from("study_sessions").update({live_slide_index:slideIndex,live_room_mode:mode,live_slide_updated_at:now,updated_at:now}).eq("id",sessionId);if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({slideIndex,mode,updatedAt:now});}
