begin;

create extension if not exists pgtap with schema extensions;

select plan(21);

create table public.devotion_weeks (id uuid primary key);
create table public.prayer_categories (id uuid primary key);
create table public.prayer_requests (id uuid primary key);
create table public.prayer_reactions (id uuid primary key);
create table public.profiles (id uuid primary key, full_name text, role text);
create table public.notifications (id uuid primary key);
create table public.weekly_digest_log (
  id bigint generated by default as identity primary key
);
create view public.prayer_wall_public as select id from public.prayer_requests;

grant all on all tables in schema public to public, anon, authenticated, service_role;
grant all on all sequences in schema public to public, anon, authenticated, service_role;

revoke all privileges on all tables in schema public
  from public, anon, authenticated;
revoke truncate, references, trigger on all tables in schema public
  from service_role;

grant select on table
  public.devotion_weeks,
  public.prayer_categories,
  public.prayer_wall_public
to anon;
grant insert on table public.prayer_requests, public.prayer_reactions to anon;

grant select on table
  public.devotion_weeks,
  public.prayer_categories,
  public.prayer_reactions,
  public.prayer_requests,
  public.profiles,
  public.notifications,
  public.prayer_wall_public
to authenticated;
grant insert on table public.prayer_requests, public.prayer_reactions to authenticated;
grant update, delete on table public.notifications to authenticated;
grant update (full_name) on table public.profiles to authenticated;

grant select, insert, update, delete on all tables in schema public to service_role;

revoke all privileges on all sequences in schema public
  from public, anon, authenticated;
grant usage, select on all sequences in schema public to service_role;

select ok(has_table_privilege('anon', 'public.prayer_wall_public', 'SELECT'),
  'anonymous visitors can read the public prayer projection');
select ok(not has_table_privilege('anon', 'public.prayer_requests', 'SELECT'),
  'anonymous visitors cannot read private prayer rows');
select ok(has_table_privilege('anon', 'public.prayer_requests', 'INSERT'),
  'anonymous visitors can submit prayer requests');
select ok(not has_table_privilege('anon', 'public.prayer_requests', 'UPDATE'),
  'anonymous visitors cannot update prayer requests');
select ok(has_table_privilege('anon', 'public.prayer_reactions', 'INSERT'),
  'anonymous visitors can add prayer activity');
select ok(not has_table_privilege('anon', 'public.prayer_reactions', 'SELECT'),
  'anonymous visitors cannot enumerate prayer activity identities');
select ok(not has_table_privilege('anon', 'public.profiles', 'SELECT'),
  'anonymous visitors cannot read profiles');
select ok(not has_table_privilege('anon', 'public.weekly_digest_log', 'SELECT'),
  'anonymous visitors cannot read internal logs');
select ok(not has_table_privilege('anon', 'public.prayer_requests', 'TRUNCATE'),
  'anonymous visitors cannot truncate tables');

select ok(has_table_privilege('authenticated', 'public.prayer_requests', 'SELECT, INSERT'),
  'members can read their allowed prayers and submit new ones');
select ok(has_table_privilege('authenticated', 'public.notifications', 'SELECT, UPDATE, DELETE'),
  'members can manage their own notifications');
select ok(has_column_privilege('authenticated', 'public.profiles', 'full_name', 'UPDATE'),
  'members can edit an ordinary profile field');
select ok(not has_column_privilege('authenticated', 'public.profiles', 'role', 'UPDATE'),
  'members cannot edit their authorization role');
select ok(not has_table_privilege('authenticated', 'public.weekly_digest_log', 'SELECT'),
  'members cannot read internal logs');
select ok(not has_table_privilege('authenticated', 'public.prayer_requests', 'TRIGGER'),
  'members do not receive trigger privileges');
select ok(not has_table_privilege('authenticated', 'public.prayer_requests', 'REFERENCES'),
  'members do not receive reference privileges');

select ok(has_table_privilege('service_role', 'public.weekly_digest_log', 'SELECT, INSERT, UPDATE, DELETE'),
  'trusted routes retain ordinary CRUD on internal tables');
select ok(not has_table_privilege('service_role', 'public.weekly_digest_log', 'TRUNCATE'),
  'trusted routes do not receive truncate privileges');
select ok(not has_table_privilege('service_role', 'public.weekly_digest_log', 'TRIGGER'),
  'trusted routes do not receive trigger privileges');
select ok(not has_table_privilege('service_role', 'public.weekly_digest_log', 'REFERENCES'),
  'trusted routes do not receive reference privileges');
select ok(has_sequence_privilege('service_role', 'public.weekly_digest_log_id_seq', 'USAGE'),
  'trusted inserts retain identity sequence access');

select * from finish();
rollback;
