-- Row Level Security policies for the public schema, exported from the live
-- Supabase project (lostandfoundproject26 / lsxaadzyonvvdbzewpql) on 2026-07-27.
--
-- This file is a point-in-time snapshot for version control and disaster
-- recovery reference. It was generated by querying pg_policies directly and
-- reconstructing the equivalent CREATE POLICY statements — it is NOT run
-- automatically as part of any migration, and editing it does not change
-- the live database. If you change policies in the Supabase dashboard or via
-- a migration, please re-export and update this file to keep it current.
--
-- To re-export, run this in the Supabase SQL Editor and copy the result:
--
--   select string_agg(
--     'CREATE POLICY ' || quote_ident(policyname) || ' ON ' || schemaname || '.' || tablename ||
--     ' AS ' || permissive || ' FOR ' || cmd || ' TO ' || array_to_string(roles, ', ') ||
--     case when qual is not null then E'\n  USING (' || qual || ')' else '' end ||
--     case when with_check is not null then E'\n  WITH CHECK (' || with_check || ')' else '' end ||
--     ';', E'\n\n' order by tablename, policyname
--   ) from pg_policies where schemaname = 'public';

CREATE POLICY feedback_insert_own ON public.feedback_messages AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY feedback_select_admin ON public.feedback_messages AS PERMISSIVE FOR SELECT TO public
  USING ((EXISTS ( SELECT 1
   FROM profiles adm
  WHERE ((adm.id = auth.uid()) AND (adm.role = 'admin'::text)))));

CREATE POLICY feedback_update_admin ON public.feedback_messages AS PERMISSIVE FOR UPDATE TO public
  USING ((EXISTS ( SELECT 1
   FROM profiles adm
  WHERE ((adm.id = auth.uid()) AND (adm.role = 'admin'::text)))));

CREATE POLICY journey_entries_delete_own ON public.journey_entries AS PERMISSIVE FOR DELETE TO public
  USING ((user_id = auth.uid()));

CREATE POLICY journey_entries_insert_own ON public.journey_entries AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((user_id = auth.uid()));

CREATE POLICY journey_entries_select_own ON public.journey_entries AS PERMISSIVE FOR SELECT TO public
  USING ((user_id = auth.uid()));

CREATE POLICY journey_entries_update_own ON public.journey_entries AS PERMISSIVE FOR UPDATE TO public
  USING ((user_id = auth.uid()));

CREATE POLICY notifications_delete_own ON public.notifications AS PERMISSIVE FOR DELETE TO public
  USING ((auth.uid() = user_id));

CREATE POLICY notifications_select_own ON public.notifications AS PERMISSIVE FOR SELECT TO public
  USING ((auth.uid() = user_id));

CREATE POLICY notifications_update_own ON public.notifications AS PERMISSIVE FOR UPDATE TO public
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY praise_insert_own ON public.praise_reports AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY praise_select_care ON public.praise_reports AS PERMISSIVE FOR SELECT TO public
  USING ((EXISTS ( SELECT 1
   FROM profiles adm
  WHERE ((adm.id = auth.uid()) AND (adm.role = ANY (ARRAY['admin'::text, 'prayer_team'::text, 'pastor'::text]))))));

CREATE POLICY praise_select_own ON public.praise_reports AS PERMISSIVE FOR SELECT TO public
  USING ((auth.uid() = user_id));

CREATE POLICY praise_update_care ON public.praise_reports AS PERMISSIVE FOR UPDATE TO public
  USING ((EXISTS ( SELECT 1
   FROM profiles adm
  WHERE ((adm.id = auth.uid()) AND (adm.role = ANY (ARRAY['admin'::text, 'prayer_team'::text, 'pastor'::text]))))));

CREATE POLICY praise_update_own ON public.praise_reports AS PERMISSIVE FOR UPDATE TO public
  USING ((auth.uid() = user_id));

CREATE POLICY "Admins can view all applications" ON public.prayer_care_applications AS PERMISSIVE FOR SELECT TO public
  USING ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = auth.uid()) AND (p.role = 'admin'::text)))));

CREATE POLICY "Users can submit their own application" ON public.prayer_care_applications AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can view their own applications" ON public.prayer_care_applications AS PERMISSIVE FOR SELECT TO public
  USING ((auth.uid() = user_id));

CREATE POLICY categories_select_all ON public.prayer_categories AS PERMISSIVE FOR SELECT TO public
  USING (true);

CREATE POLICY categories_write_care_team ON public.prayer_categories AS PERMISSIVE FOR ALL TO public
  USING (is_care_team())
  WITH CHECK (is_care_team());

CREATE POLICY reactions_insert_anyone ON public.prayer_reactions AS PERMISSIVE FOR INSERT TO public
  WITH CHECK (true);

CREATE POLICY reactions_select_all ON public.prayer_reactions AS PERMISSIVE FOR SELECT TO public
  USING (true);

CREATE POLICY requests_delete_admin ON public.prayer_requests AS PERMISSIVE FOR DELETE TO public
  USING ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));

CREATE POLICY requests_insert_anyone ON public.prayer_requests AS PERMISSIVE FOR INSERT TO public
  WITH CHECK (((user_id IS NULL) OR (user_id = auth.uid())));

CREATE POLICY requests_select_care_team ON public.prayer_requests AS PERMISSIVE FOR SELECT TO public
  USING (is_care_team());

CREATE POLICY requests_select_own ON public.prayer_requests AS PERMISSIVE FOR SELECT TO public
  USING ((auth.uid() = user_id));

CREATE POLICY requests_select_public ON public.prayer_requests AS PERMISSIVE FOR SELECT TO public
  USING ((is_public = true));

CREATE POLICY requests_update_care_team ON public.prayer_requests AS PERMISSIVE FOR UPDATE TO public
  USING (is_care_team())
  WITH CHECK (is_care_team());

CREATE POLICY requests_update_own ON public.prayer_requests AS PERMISSIVE FOR UPDATE TO public
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY updates_all_care_team ON public.prayer_updates AS PERMISSIVE FOR ALL TO public
  USING (is_care_team())
  WITH CHECK (is_care_team());

CREATE POLICY profiles_select_own_or_care_team ON public.profiles AS PERMISSIVE FOR SELECT TO public
  USING (((auth.uid() = id) OR is_care_team()));

CREATE POLICY profiles_update_own ON public.profiles AS PERMISSIVE FOR UPDATE TO public
  USING ((auth.uid() = id))
  WITH CHECK ((auth.uid() = id));

CREATE POLICY "Users manage their own push subscriptions" ON public.push_subscriptions AS PERMISSIVE FOR ALL TO public
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY push_subs_delete_own ON public.push_subscriptions AS PERMISSIVE FOR DELETE TO public
  USING ((auth.uid() = user_id));

CREATE POLICY push_subs_insert_own ON public.push_subscriptions AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY push_subs_select_own ON public.push_subscriptions AS PERMISSIVE FOR SELECT TO public
  USING ((auth.uid() = user_id));

CREATE POLICY testimonies_insert_own ON public.testimonies AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY testimonies_select_care ON public.testimonies AS PERMISSIVE FOR SELECT TO public
  USING ((EXISTS ( SELECT 1
   FROM profiles adm
  WHERE ((adm.id = auth.uid()) AND (adm.role = ANY (ARRAY['admin'::text, 'prayer_team'::text, 'pastor'::text]))))));

CREATE POLICY testimonies_select_own ON public.testimonies AS PERMISSIVE FOR SELECT TO public
  USING ((auth.uid() = user_id));

CREATE POLICY testimonies_update_care ON public.testimonies AS PERMISSIVE FOR UPDATE TO public
  USING ((EXISTS ( SELECT 1
   FROM profiles adm
  WHERE ((adm.id = auth.uid()) AND (adm.role = ANY (ARRAY['admin'::text, 'prayer_team'::text, 'pastor'::text]))))));

CREATE POLICY testimonies_update_own ON public.testimonies AS PERMISSIVE FOR UPDATE TO public
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can insert their own settings" ON public.user_settings AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can update their own settings" ON public.user_settings AS PERMISSIVE FOR UPDATE TO public
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can view their own settings" ON public.user_settings AS PERMISSIVE FOR SELECT TO public
  USING ((auth.uid() = user_id));
