import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import PrayerWallTicker from "@/components/PrayerWallTicker";
import PraiseTicker from "@/components/PraiseTicker";
import TestimonyTicker from "@/components/TestimonyTicker";

export default async function CommunityPage(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/login?next=%2Fcommunity");
 return <main className="lfp-page pb-24">
  <section className="relative overflow-hidden"><div aria-hidden className="lfp-grid absolute inset-0"/><div className="lfp-shell relative py-12 sm:py-16"><div className="max-w-4xl"><p className="lfp-eyebrow">Community</p><h1 className="mt-3 text-4xl font-black tracking-[-.045em] text-slate-950 sm:text-6xl">A social space built around <span className="lfp-gradient-text">something deeper.</span></h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">Not another feed to scroll. A place to notice people, carry needs, celebrate grace, tell the story, and move toward real relationships.</p></div><div className="mt-7 flex flex-wrap gap-3"><Link href="/prayer" className="lfp-button lfp-button-primary">Open Prayer</Link><Link href="/events" className="lfp-button lfp-button-secondary">Find a Gathering</Link><Link href="/ministries" className="lfp-button lfp-button-secondary">Ministry Spaces</Link></div></div></section>
  <div className="lfp-shell py-8 sm:py-12">
   <section className="mt-10 rounded-[2rem] bg-[rgb(var(--lfp-ink))] p-6 text-white sm:p-9"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[11px] font-black uppercase tracking-[.17em] text-sky-300">Prayer Pulse</p><h2 className="mt-2 text-3xl font-black">See what the community is carrying, celebrating, and remembering.</h2><p className="mt-3 max-w-3xl leading-7 text-slate-300">Prayer can become praise, and praise can become testimony. These are invitations to participate, not popularity metrics. Open a prayer to pray intentionally, celebrate a praise once, or encourage a testimony once.</p></div><Link href="/prayer" className="lfp-button bg-white text-slate-950">Open Prayer →</Link></div><div className="mt-7 grid gap-4 lg:grid-cols-3"><PulsePanel label="Prayer" copy="Return and pray again when a need stays on your heart."><PrayerWallTicker emptyMessage="No public prayer requests are waiting right now."/></PulsePanel><PulsePanel label="Praise" copy="Celebrate God's faithfulness without turning praise into a contest."><PraiseTicker/></PulsePanel><PulsePanel label="Testimony" copy="Remember what God has done and encourage the person who shared it."><TestimonyTicker/></PulsePanel></div></section>
   <section className="mt-10 grid gap-5 lg:grid-cols-3"><Link href="/events" className="lfp-card p-7"><p className="text-[11px] font-black uppercase tracking-[.17em] text-blue-700">Gatherings</p><h2 className="mt-3 text-2xl font-black">Show up with people.</h2><p className="mt-3 leading-7 text-slate-600">Find the next study, meeting, or ministry gathering connected to real relationships.</p><span className="mt-5 inline-flex font-black text-blue-700">See Gatherings →</span></Link><Link href="/ministries" className="lfp-card p-7"><p className="text-[11px] font-black uppercase tracking-[.17em] text-blue-700">Ministry Spaces</p><h2 className="mt-3 text-2xl font-black">Belong somewhere specific.</h2><p className="mt-3 leading-7 text-slate-600">Return to the ministry spaces where updates, gatherings, resources, and people stay connected.</p><span className="mt-5 inline-flex font-black text-blue-700">Open Ministry Spaces →</span></Link><div className="rounded-[2rem] bg-[rgb(var(--lfp-ink))] p-7 text-white"><p className="text-[11px] font-black uppercase tracking-[.17em] text-sky-300">Community standard</p><h2 className="mt-3 text-2xl font-black">Presence over performance.</h2><p className="mt-3 leading-7 text-slate-300">Prayer → Praise → Testimony is a story of people carrying one another and noticing God&apos;s faithfulness. Future groups and connections should lead toward meaningful relationships, not another feed.</p><ul className="mt-4 space-y-2 text-sm leading-6 text-slate-300"><li>Prayer can be marked repeatedly because prayer is an action.</li><li>Praise can be loved once per member.</li><li>Testimony can be encouraged once per member.</li><li>You cannot react to your own prayer, praise, or testimony.</li></ul><p className="mt-4 text-sm font-bold text-sky-300">These are signs of participation, not popularity metrics.</p></div></section>
  </div>
 </main>;
}

function PulsePanel({label,copy,children}:{label:string;copy:string;children:React.ReactNode}){return <div className="rounded-[1.5rem] bg-white p-4 text-slate-950"><div className="px-2 pb-3"><p className="text-[11px] font-black uppercase tracking-[.16em] text-blue-700">{label}</p><p className="mt-1 text-sm leading-6 text-slate-500">{copy}</p></div><div className="max-h-72 overflow-hidden">{children}</div></div>}
