import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

const spaces=[
 {href:"/prayer",icon:"♡",eyebrow:"Carry",title:"Prayer",description:"Needs the community can intentionally carry before God.",action:"Pray with someone"},
 {href:"/praise",icon:"✦",eyebrow:"Celebrate",title:"Praise",description:"Small and big reminders of God's faithfulness worth celebrating together.",action:"Celebrate with someone"},
 {href:"/testimonies",icon:"◎",eyebrow:"Remember",title:"Testimony",description:"Stories that preserve what God has done and give someone else hope.",action:"Read the stories"},
];

export default async function CommunityPage(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/login");
 return <main className="lfp-page pb-24">
  <section className="relative overflow-hidden"><div aria-hidden className="lfp-grid absolute inset-0"/><div className="lfp-shell relative py-12 sm:py-16"><div className="max-w-4xl"><p className="lfp-eyebrow">Community</p><h1 className="mt-3 text-4xl font-black tracking-[-.045em] text-slate-950 sm:text-6xl">A social space built around <span className="lfp-gradient-text">something deeper.</span></h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">Not another feed to scroll. A place to notice people, carry needs, celebrate grace, tell the story, and move toward real relationships.</p></div><div className="mt-7 flex flex-wrap gap-3"><Link href="/prayer/submit" className="lfp-button lfp-button-primary"><span>＋</span> Share a need</Link><Link href="/praise" className="lfp-button lfp-button-secondary">Share a praise</Link><Link href="/testimonies" className="lfp-button lfp-button-secondary">Tell your story</Link></div></div></section>
  <div className="lfp-shell py-8 sm:py-12">
   <section className="grid gap-4 md:grid-cols-3">{spaces.map(s=><Link key={s.href} href={s.href} className="lfp-card group p-6"><div className="flex items-center justify-between"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-2xl text-blue-700">{s.icon}</span><span className="text-xl text-slate-300 transition group-hover:translate-x-1 group-hover:text-blue-700">→</span></div><p className="mt-5 text-[11px] font-black uppercase tracking-[.16em] text-blue-700">{s.eyebrow}</p><h2 className="mt-1 text-2xl font-black text-slate-950">{s.title}</h2><p className="mt-2 leading-7 text-slate-600">{s.description}</p><p className="mt-4 text-sm font-black text-blue-700">{s.action}</p></Link>)}</section>
   <section className="mt-10 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-[2rem] bg-[rgb(var(--lfp-ink))] p-7 text-white sm:p-9"><p className="text-[11px] font-black uppercase tracking-[.17em] text-sky-300">The L&F difference</p><h2 className="mt-3 text-3xl font-black">The story shouldn't end when the prayer is answered.</h2><div className="mt-7 flex items-center gap-2 overflow-x-auto pb-2 text-sm font-black"><span className="whitespace-nowrap rounded-full bg-white/10 px-4 py-2">♡ Prayer</span><span className="text-slate-500">→</span><span className="whitespace-nowrap rounded-full bg-white/10 px-4 py-2">✦ Praise</span><span className="text-slate-500">→</span><span className="whitespace-nowrap rounded-full bg-white/10 px-4 py-2">◎ Testimony</span></div><p className="mt-5 leading-7 text-slate-300">The platform is being designed so a real need can become a visible story of God's faithfulness. That gives the community context, continuity, and a reason to return beyond passive scrolling.</p></div><div className="lfp-card p-7 sm:p-8"><p className="text-[11px] font-black uppercase tracking-[.17em] text-emerald-700">Community standard</p><h2 className="mt-3 text-2xl font-black text-slate-950">Presence over performance.</h2><p className="mt-3 leading-7 text-slate-600">L&F community features should help people be known and encouraged without turning faith into popularity metrics. Useful interaction wins over vanity numbers.</p><div className="mt-6 space-y-3 text-sm font-bold text-slate-700"><p>✓ Prayer interactions can reflect repeated, intentional prayer.</p><p>✓ Praise and testimony can be celebrated without becoming a contest.</p><p>✓ Future groups and connections should lead toward meaningful relationships.</p></div></div></section>
  </div>
 </main>;
}
