import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import PrayerWallTicker from "@/components/PrayerWallTicker";
import PraiseTicker from "@/components/PraiseTicker";
import TestimonyTicker from "@/components/TestimonyTicker";

const spaces=[
 {href:"/prayer",icon:"♡",eyebrow:"Carry",title:"Prayer",description:"Needs the community can intentionally carry before God.",action:"Pray with someone"},
 {href:"/praise",icon:"✦",eyebrow:"Celebrate",title:"Praise",description:"Small and big reminders of God's faithfulness worth celebrating together.",action:"Celebrate with someone"},
 {href:"/testimonies",icon:"◎",eyebrow:"Remember",title:"Testimony",description:"Stories that preserve what God has done and give someone else hope.",action:"Read the stories"},
];

const communityActions=[
 {href:"/prayer/submit",icon:"♡",label:"Prayer",copy:"Share a need for the community to carry."},
 {href:"/praise",icon:"✦",label:"Praise",copy:"Celebrate what God is doing."},
 {href:"/testimonies",icon:"◎",label:"Testimony",copy:"Tell the story of God's faithfulness."},
 {href:"/events",icon:"□",label:"Gatherings",copy:"See what is coming up and where to join."},
];

export default async function CommunityPage(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/login?next=%2Fcommunity");
 return <main className="lfp-page pb-24">
  <section className="relative overflow-hidden"><div aria-hidden className="lfp-grid absolute inset-0"/><div className="lfp-shell relative py-12 sm:py-16"><div className="max-w-4xl"><p className="lfp-eyebrow">Community</p><h1 className="mt-3 text-4xl font-black tracking-[-.045em] text-slate-950 sm:text-6xl">A social space built around <span className="lfp-gradient-text">something deeper.</span></h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">Not another feed to scroll. A place to notice people, carry needs, celebrate grace, tell the story, and move toward real relationships.</p></div><div className="mt-7 flex flex-wrap gap-3"><Link href="/prayer/submit" className="lfp-button lfp-button-primary"><span>＋</span> Share a need</Link><Link href="/praise" className="lfp-button lfp-button-secondary">Share a praise</Link><Link href="/testimonies" className="lfp-button lfp-button-secondary">Tell your story</Link></div></div></section>
  <div className="lfp-shell py-8 sm:py-12">
   <section><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="lfp-eyebrow">Act now</p><h2 className="mt-2 text-3xl font-black text-slate-950">One action pattern across L&F.</h2><p className="mt-2 max-w-2xl leading-7 text-slate-600">The community should make participation easier than browsing. Start with the action you came here to take.</p></div></div><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{communityActions.map(a=><Link key={a.label} href={a.href} className="lfp-card p-5"><span className="text-2xl text-blue-700">{a.icon}</span><h3 className="mt-3 font-black text-slate-950">{a.label}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{a.copy}</p></Link>)}</div></section>
   <section className="mt-10 rounded-[2rem] bg-[rgb(var(--lfp-ink))] p-6 text-white sm:p-9"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[11px] font-black uppercase tracking-[.17em] text-sky-300">Prayer Pulse</p><h2 className="mt-2 text-3xl font-black">See what the community is carrying, celebrating, and remembering.</h2><p className="mt-3 max-w-3xl leading-7 text-slate-300">These are invitations to participate, not popularity metrics. Open a prayer to pray intentionally, celebrate a praise once, or encourage a testimony once.</p></div><Link href="/prayer" className="lfp-button bg-white text-slate-950">Open Prayer →</Link></div><div className="mt-7 grid gap-4 lg:grid-cols-3"><PulsePanel label="Prayer" copy="Return and pray again when a need stays on your heart."><PrayerWallTicker emptyMessage="No public prayer requests are waiting right now."/></PulsePanel><PulsePanel label="Praise" copy="Celebrate God's faithfulness without turning praise into a contest."><PraiseTicker/></PulsePanel><PulsePanel label="Testimony" copy="Remember what God has done and encourage the person who shared it."><TestimonyTicker/></PulsePanel></div></section>
   <section className="mt-10 grid gap-4 md:grid-cols-3">{spaces.map(s=><Link key={s.href} href={s.href} className="lfp-card group p-6"><div className="flex items-center justify-between"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-2xl text-blue-700">{s.icon}</span><span className="text-xl text-slate-300 transition group-hover:translate-x-1 group-hover:text-blue-700">→</span></div><p className="mt-5 text-[11px] font-black uppercase tracking-[.16em] text-blue-700">{s.eyebrow}</p><h2 className="mt-1 text-2xl font-black text-slate-950">{s.title}</h2><p className="mt-2 leading-7 text-slate-600">{s.description}</p><p className="mt-4 text-sm font-black text-blue-700">{s.action}</p></Link>)}</section>
   <section className="mt-10 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-[2rem] bg-[rgb(var(--lfp-ink))] p-7 text-white sm:p-9"><p className="text-[11px] font-black uppercase tracking-[.17em] text-sky-300">The L&F difference</p><h2 className="mt-3 text-3xl font-black">The story shouldn't end when the prayer is answered.</h2><div className="mt-7 flex items-center gap-2 overflow-x-auto pb-2 text-sm font-black"><span className="whitespace-nowrap rounded-full bg-white/10 px-4 py-2">♡ Prayer</span><span className="text-slate-500">→</span><span className="whitespace-nowrap rounded-full bg-white/10 px-4 py-2">✦ Praise</span><span className="text-slate-500">→</span><span className="whitespace-nowrap rounded-full bg-white/10 px-4 py-2">◎ Testimony</span></div><p className="mt-5 leading-7 text-slate-300">A real need can become a visible story of God's faithfulness. Prayer can become praise, and praise can become testimony, giving the community context, continuity, and a reason to return beyond passive scrolling.</p></div><div className="lfp-card p-7 sm:p-8"><p className="text-[11px] font-black uppercase tracking-[.17em] text-emerald-700">Community standard</p><h2 className="mt-3 text-2xl font-black text-slate-950">Presence over performance.</h2><p className="mt-3 leading-7 text-slate-600">L&F community features help people be known and encouraged without turning faith into popularity metrics. Useful interaction wins over vanity numbers.</p><div className="mt-6 space-y-3 text-sm font-bold text-slate-700"><p>✓ Prayer can be marked repeatedly because prayer is an ongoing action.</p><p>✓ Praise can be loved once per member.</p><p>✓ Testimony can be encouraged once per member.</p><p>✓ You cannot react to your own prayer, praise, or testimony.</p><p>✓ Future groups and connections should lead toward meaningful relationships.</p></div></div></section>
  </div>
 </main>;
}

function PulsePanel({label,copy,children}:{label:string;copy:string;children:React.ReactNode}){return <div className="rounded-[1.5rem] bg-white p-4 text-slate-950"><div className="px-2 pb-3"><p className="text-[11px] font-black uppercase tracking-[.16em] text-blue-700">{label}</p><p className="mt-1 text-sm leading-6 text-slate-500">{copy}</p></div><div className="max-h-72 overflow-hidden">{children}</div></div>}
