import Link from "next/link";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";
import {hasPlatformRole} from "@/lib/access-control";
import {claimInitialOwner,grantPlatformRole,revokePlatformRole,grantMinistryRole,revokeMinistryRole} from "./actions";

export default async function AccessPage(){
 const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)redirect("/login");
 const isOwner=await hasPlatformRole(["owner"]);const isAdmin=isOwner||await hasPlatformRole(["admin"]);if(!isAdmin)redirect("/dashboard");
 const admin=createAdminClient();
 const [{data:platform},{data:ministry},{data:profiles}]=await Promise.all([
  admin.from("platform_role_assignments").select("id,user_id,role_key,granted_at").is("revoked_at",null).order("granted_at",{ascending:false}),
  admin.from("ministry_role_assignments").select("id,user_id,ministry_key,role_key,granted_at").is("revoked_at",null).order("granted_at",{ascending:false}),
  admin.from("profiles").select("id,full_name,email,is_active")
 ]);
 const people=new Map((profiles??[]).map((p:any)=>[p.id,p]));const ownerExists=(platform??[]).some((r:any)=>r.role_key==="owner");
 return <main className="lfp-page pb-24"><section className="bg-slate-950 text-white"><div className="lfp-shell py-10"><Link href="/admin" className="text-sm font-black text-sky-200">← Administration Center</Link><p className="mt-6 text-xs font-black uppercase tracking-[.2em] text-amber-300">Access Control</p><h1 className="mt-2 text-4xl font-black">Roles & ministry assignments</h1><p className="mt-3 max-w-3xl text-slate-300">Grant only the authority a person needs. Ministry responsibility stays scoped to its ministry; platform authority stays separate.</p></div></section><div className="lfp-shell py-8 space-y-10">
 {!ownerExists&&<section className="rounded-3xl border border-amber-300 bg-amber-50 p-6"><p className="text-xs font-black uppercase tracking-[.15em] text-amber-800">One-time setup</p><h2 className="mt-2 text-2xl font-black">No Platform Owner exists yet</h2><p className="mt-2 max-w-3xl text-slate-700">An existing legacy administrator may claim the initial Owner role once. After the first Owner exists, this bootstrap closes permanently.</p><form action={claimInitialOwner} className="mt-4"><button className="lfp-button bg-slate-950 text-white">Claim Initial Owner Role</button></form></section>}
 <section className="grid gap-5 lg:grid-cols-2"><article className="lfp-card p-6"><p className="lfp-eyebrow">Platform role</p><h2 className="mt-1 text-2xl font-black">Grant elevated platform access</h2><p className="mt-2 text-sm text-slate-600">{isOwner?"Owners may grant Admin or Content Editor. Owner itself is intentionally not grantable here.":"Admins may grant Content Editor only."}</p><form action={grantPlatformRole} className="mt-5 grid gap-3"><input required type="email" name="email" placeholder="member@email.com" className="rounded-xl border p-3"/><select required name="role_key" className="rounded-xl border p-3">{isOwner&&<option value="admin">Admin</option>}<option value="content_editor">Content Editor</option></select><button className="lfp-button bg-slate-950 text-white">Grant Platform Role</button></form></article>
 <article className="lfp-card p-6"><p className="lfp-eyebrow">Ministry assignment</p><h2 className="mt-1 text-2xl font-black">Grant ministry-specific access</h2><p className="mt-2 text-sm text-slate-600">Admins and Owners may assign Participants, Facilitators, or Leaders without giving them platform administration.</p><form action={grantMinistryRole} className="mt-5 grid gap-3"><input required type="email" name="email" placeholder="member@email.com" className="rounded-xl border p-3"/><input required name="ministry_key" placeholder="hearth or foundry" className="rounded-xl border p-3"/><select required name="role_key" className="rounded-xl border p-3"><option value="participant">Participant</option><option value="facilitator">Facilitator</option><option value="leader">Ministry Leader</option></select><button className="lfp-button bg-slate-950 text-white">Grant Ministry Role</button></form></article></section>
 <section><p className="lfp-eyebrow">Platform assignments</p><div className="mt-4 grid gap-3">{platform?.map((r:any)=>{const p=people.get(r.user_id);return <article key={r.id} className="lfp-card flex flex-wrap items-center justify-between gap-3 p-5"><div><h3 className="font-black">{p?.full_name||p?.email||r.user_id}</h3><p className="text-sm text-slate-500">{p?.email} · {r.role_key.replace("_"," ")}</p></div>{r.role_key!=="owner"&&<form action={revokePlatformRole}><input type="hidden" name="user_id" value={r.user_id}/><input type="hidden" name="role_key" value={r.role_key}/><button className="rounded-xl border px-3 py-2 text-sm font-black">Revoke</button></form>}</article>})}</div></section>
 <section><p className="lfp-eyebrow">Ministry assignments</p><div className="mt-4 grid gap-3">{ministry?.map((r:any)=>{const p=people.get(r.user_id);return <article key={r.id} className="lfp-card flex flex-wrap items-center justify-between gap-3 p-5"><div><h3 className="font-black">{p?.full_name||p?.email||r.user_id}</h3><p className="text-sm text-slate-500">{p?.email} · {r.ministry_key} · {r.role_key}</p></div><form action={revokeMinistryRole}><input type="hidden" name="user_id" value={r.user_id}/><input type="hidden" name="ministry_key" value={r.ministry_key}/><input type="hidden" name="role_key" value={r.role_key}/><button className="rounded-xl border px-3 py-2 text-sm font-black">Revoke</button></form></article>})}</div></section>
 <aside className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-slate-700"><strong>Owner protection:</strong> after bootstrap, Owner cannot be assigned or revoked from this screen. Owner transfer remains a deliberate out-of-band security operation.</aside>
 </div></main>;
}
