export type LanguageQuestion={
 id:string; verse:string; focus:string; original:string; transliteration:string;
 question:string; choices:string[]; correct:string; teaching:string; guardrail?:string;
};
export const ephesiansTwoLesson={
 slug:"ephesians-2-1-10",
 title:"From Death to Life",
 passage:"Ephesians 2:1–10",
 intro:"Read Ephesians 2:1–10 before beginning. The questions below follow Paul's movement from humanity's former condition to God's saving action and the life He creates afterward.",
 questions:[
 {id:"walked",verse:"Ephesians 2:2",focus:"walked",original:"περιπατέω",transliteration:"peripateō",question:"When Paul says believers once “walked” in trespasses and sins, what does the verb most naturally describe?",choices:["A literal journey","A habitual way of life","A religious pilgrimage","A single failure"],correct:"A habitual way of life",teaching:"Peripateō literally can mean to walk, but Paul often uses it figuratively for one's manner of life. Here the context is not one isolated act but the pattern in which they formerly lived."},
 {id:"age",verse:"Ephesians 2:2",focus:"course / age",original:"αἰών",transliteration:"aiōn",question:"The phrase often translated “course of this world” contains aiōn. What idea fits this context best?",choices:["A physical road","The present age and its prevailing pattern","Eternity in every possible sense","A calendar year"],correct:"The present age and its prevailing pattern",teaching:"Aiōn can refer to an age or era. In Ephesians 2:2 Paul is describing the present order that shapes rebellion against God, not defining every possible meaning of the word."},
 {id:"mercy",verse:"Ephesians 2:4",focus:"mercy",original:"ἔλεος",transliteration:"eleos",question:"Why does “mercy” matter at the turning point of this passage?",choices:["It explains God's response to human misery and guilt","It means God ignored sin","It refers only to emotional sympathy","It means people rescued themselves"],correct:"It explains God's response to human misery and guilt",teaching:"Eleos commonly carries the idea of mercy or compassionate help. In this paragraph it highlights God's action toward people who were helpless in their former condition."},
 {id:"grace",verse:"Ephesians 2:5,8",focus:"grace",original:"χάρις",transliteration:"charis",question:"In Ephesians 2, what does charis emphasize most clearly?",choices:["God's unearned favor and saving generosity","A reward earned by good works","A pleasant personality","Human potential"],correct:"God's unearned favor and saving generosity",teaching:"Charis has a broader semantic range than one English gloss, but verses 5 and 8 make the sense clear: salvation comes from God's gracious initiative, not human merit."},
 {id:"saved",verse:"Ephesians 2:5,8",focus:"saved",original:"σῴζω",transliteration:"sōzō",question:"What is Paul emphasizing with “you have been saved” in this passage?",choices:["God has rescued them from their former condition","They became morally perfect","They escaped every hardship","They gained political freedom"],correct:"God has rescued them from their former condition",teaching:"Sōzō can mean save, rescue, or deliver. The paragraph defines the rescue: from death in sins into life with Christ, by God's grace."},
 {id:"gift",verse:"Ephesians 2:8",focus:"gift",original:"δῶρον",transliteration:"dōron",question:"What role does “gift” play in Paul's argument in verse 8?",choices:["It reinforces that salvation is received, not earned","It describes a temple sacrifice only","It refers to money given to Paul","It means faith is unnecessary"],correct:"It reinforces that salvation is received, not earned",teaching:"Dōron means gift. In context it supports Paul's contrast between God's saving action and human boasting. The verse should be read as a whole rather than forcing the noun to settle every grammatical debate by itself.",guardrail:"Do not make dōron carry more grammatical weight than the sentence allows. Paul's main point is clear even where interpreters debate the precise antecedent of “this.”"},
 {id:"works",verse:"Ephesians 2:9",focus:"works",original:"ἔργον",transliteration:"ergon",question:"Why does Paul exclude “works” in verse 9?",choices:["To rule out boasting in human achievement as the basis of salvation","Because obedience never matters","Because work is sinful","Because Christians should avoid service"],correct:"To rule out boasting in human achievement as the basis of salvation",teaching:"Ergon means work or deed. Verse 9 excludes works as the ground of salvation. Verse 10 immediately shows that good works still matter as the result of God's saving work."},
 {id:"workmanship",verse:"Ephesians 2:10",focus:"workmanship",original:"ποίημα",transliteration:"poiēma",question:"What does poiēma communicate in “we are his workmanship”?",choices:["Something made or produced","A secret poem hidden in every believer","A legal verdict only","A religious building"],correct:"Something made or produced",teaching:"Poiēma refers to something made or created. Paul is emphasizing God's craftsmanship and initiative. The English word “poem” is historically related, but the verse does not literally call believers God's poem.",guardrail:"Avoid the popular overstatement “you are God's poem.” The connection is memorable, but it is not the lexical meaning Paul is asserting here."},
 {id:"created",verse:"Ephesians 2:10",focus:"created",original:"κτίζω",transliteration:"ktizō",question:"What does “created in Christ Jesus” contribute to Paul's logic?",choices:["Salvation produces a new God-created life","Believers existed before creation","Good works create salvation","Only physical creation matters"],correct:"Salvation produces a new God-created life",teaching:"Ktizō means create. After describing rescue by grace, Paul presents the believer's new life as God's creative work in Christ."},
 {id:"prepared",verse:"Ephesians 2:10",focus:"prepared beforehand",original:"προετοιμάζω",transliteration:"proetoimazō",question:"What does “prepared beforehand” say about the good works in verse 10?",choices:["God intended a life of faithful obedience for those He saves","Believers earn salvation by planning good deeds","Every decision is mechanically predetermined","Only church activities count"],correct:"God intended a life of faithful obedience for those He saves",teaching:"Proetoimazō means prepare beforehand. Paul's sequence matters: grace saves; then the saved are God's workmanship, created for a life shaped by good works."}
 ] as LanguageQuestion[]
};