import type {LanguageQuestion} from "./ephesians-2-1-10";
export const psalmTwentyThreeLesson={
 slug:"psalm-23",
 title:"The Shepherd and His Guest",
 passage:"Psalm 23",
 intro:"Read Psalm 23 as a whole before beginning. This lesson uses Hebrew words, poetic imagery, and repeated relationships in the psalm to show how language works differently in poetry than in an epistle.",
 questions:[
 {id:"shepherd",verse:"Psalm 23:1",focus:"shepherd",original:"רֹעִי",transliteration:"ro‘i",question:"When David calls the LORD “my shepherd,” what does the image primarily communicate in this psalm?",choices:["Only David's former occupation","The LORD's personal care, guidance, provision, and protection","That God is literally a human shepherd","A title for Israel's king only"],correct:"The LORD's personal care, guidance, provision, and protection",teaching:"The noun comes from the Hebrew shepherding vocabulary. Psalm 23 develops the metaphor through provision, guidance, protection, and presence. The possessive “my” makes the confession personal without making it private or individualistic."},
 {id:"lack",verse:"Psalm 23:1",focus:"I shall not lack",original:"לֹא אֶחְסָר",transliteration:"lo ’eḥsar",question:"What does “I shall not want/lack” mean in the flow of Psalm 23?",choices:["David will receive every desire","Under the Shepherd's care he is not abandoned without what the Shepherd knows he needs","Believers will never experience poverty","Faith eliminates hardship"],correct:"Under the Shepherd's care he is not abandoned without what the Shepherd knows he needs",teaching:"The verb ḥaser concerns lacking or being deficient. The following lines define the confidence through pasture, water, restoration, guidance, protection, and presence—not unlimited acquisition."},
 {id:"restores",verse:"Psalm 23:3",focus:"restores",original:"יְשׁוֹבֵב",transliteration:"yeshovev",question:"The verb behind “restores my soul/life” comes from shuv. What range fits the poetic context?",choices:["He brings me back / revives me","He gives me a new personality","He erases memory","He guarantees physical healing"],correct:"He brings me back / revives me",teaching:"Shuv often carries the idea of turning or returning. Here the shepherd image can convey bringing the sheep back, reviving life, or restoring vitality. Translation choices such as “restores my soul” should not make us assume the Hebrew word for “soul” means only an immaterial part of a person."},
 {id:"nephesh",verse:"Psalm 23:3",focus:"my soul / life",original:"נַפְשִׁי",transliteration:"nafshi (nephesh)",question:"In “he restores my nephesh,” what should we avoid assuming?",choices:["That nephesh always means an immortal inner soul separated from the body","That David is speaking about himself","That Hebrew poetry uses imagery","That restoration matters"],correct:"That nephesh always means an immortal inner soul separated from the body",teaching:"Nephesh can refer to life, self, person, throat, or living being depending on context. Here many translations keep the traditional “soul,” while “life” or “me” can help readers hear the whole-person sense. Context—not a one-word English equation—determines the nuance.",guardrail:"Do not replace every occurrence of nephesh with one preferred gloss. Its meaning is contextual."},
 {id:"paths",verse:"Psalm 23:3",focus:"paths of righteousness",original:"מַעְגְּלֵי־צֶדֶק",transliteration:"ma‘gelei-tsedeq",question:"What does the phrase “paths of righteousness” most naturally picture?",choices:["Right paths under the Shepherd's guidance","A secret map of future decisions","Only moral perfection","Roads leading to Jerusalem"],correct:"Right paths under the Shepherd's guidance",teaching:"The phrase combines track/path imagery with tsedeq, a word associated with rightness or righteousness. In the shepherd poem, God leads along the right tracks; moral faithfulness and safe/right guidance are related ideas, but the image should be allowed to remain poetic."},
 {id:"name",verse:"Psalm 23:3",focus:"for his name's sake",original:"לְמַעַן שְׁמוֹ",transliteration:"lema‘an shemo",question:"Why does David say the Shepherd leads him rightly “for his name's sake”?",choices:["God's action is consistent with His own character and reputation","David knows a secret divine pronunciation","People must make God famous","The phrase is unrelated to the shepherd image"],correct:"God's action is consistent with His own character and reputation",teaching:"In biblical usage, a “name” can represent identity, character, and reputation. David grounds the Shepherd's faithful guidance in who the LORD is, not in David's ability to earn care."},
 {id:"shadow",verse:"Psalm 23:4",focus:"deepest darkness / shadow of death",original:"צַלְמָוֶת",transliteration:"tsalmavet",question:"Why do translations differ between “shadow of death” and “deep darkness” in verse 4?",choices:["The Hebrew term can denote deathly or deep darkness","One translation removed the Hebrew text","David wrote two different psalms","The word literally means a specific valley near Jerusalem"],correct:"The Hebrew term can denote deathly or deep darkness",teaching:"Tsalmavet is traditionally rendered “shadow of death,” while many modern translations use “deep darkness.” Either way, the poetic point is extreme danger and darkness. The psalm does not identify a geographic place called the Valley of the Shadow of Death.",guardrail:"Do not turn the poetic phrase into a named biblical location unless the text gives one."},
 {id:"you",verse:"Psalm 23:4",focus:"you are with me",original:"אַתָּה עִמָּדִי",transliteration:"attah ‘immadi",question:"What important shift happens when David reaches the darkest valley?",choices:["He changes from speaking about God to speaking directly to God","He stops believing in the Shepherd","He changes narrators","He begins a new psalm"],correct:"He changes from speaking about God to speaking directly to God",teaching:"Verses 1-3 repeatedly speak of “he.” In verse 4 David says “you are with me.” The grammatical shift intensifies the sense of presence: in danger, the poem moves from testimony about the Shepherd to address of the Shepherd."},
 {id:"comfort",verse:"Psalm 23:4",focus:"comfort",original:"יְנַחֲמֻנִי",transliteration:"yenaḥamuni",question:"What kind of comfort is pictured by the rod and staff?",choices:["Reassurance through the Shepherd's protective and guiding presence","Avoidance of every dangerous valley","A comfortable lifestyle","A promise that discipline never occurs"],correct:"Reassurance through the Shepherd's protective and guiding presence",teaching:"The verb naḥam can express comfort or consolation. Here the instruments associated with shepherding reinforce that David's courage comes from the Shepherd being present and equipped to guide and protect."},
 {id:"hesed",verse:"Psalm 23:6",focus:"steadfast love / goodness",original:"חֶסֶד",transliteration:"ḥesed",question:"What does ḥesed contribute to the closing confidence of Psalm 23?",choices:["The LORD's loyal, steadfast covenant love","A temporary emotion","David's own moral goodness","Material wealth only"],correct:"The LORD's loyal, steadfast covenant love",teaching:"Ḥesed is a rich Hebrew word often rendered steadfast love, lovingkindness, mercy, or loyal love. No single English gloss captures every occurrence. Here it accompanies “goodness” and pursues David throughout his life, completing the psalm's portrait of faithful divine care.",guardrail:"Do not claim ḥesed has one exhaustive English definition. Its covenantal and relational force is learned from usage and context."}
 ] as LanguageQuestion[]
};