import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
const root=process.cwd();const source=(...parts)=>readFile(path.join(root,...parts),"utf8");

test("Learning Lab is a skill map with a single learning objective per Lab",async()=>{const learn=await source("app","learn","page.tsx");for(const label of ["Bible Trivia","Language Insights","Context Lab","Bible Geography","Connections","People","Timeline","Bible Books","Observation","Study Skills"])assert.match(learn,new RegExp(label));assert.match(learn,/Read → Discover → Learn → Practice → Remember/);assert.match(learn,/What am I learning here/);});
test("Trivia excludes material that belongs to specialist Labs",async()=>{const page=await source("app","trivia","page.tsx");assert.match(page,/NON_TRIVIA/);for(const id of ["language-insights","bible-context","bible-geography","connections"])assert.match(page,new RegExp(id));assert.match(page,/Trivia has one job/);assert.match(page,/biblical facts/);});
test("Language Insights has a dedicated passage-first route and guardrails",async()=>{const page=await source("app","learn","language","page.tsx");assert.match(page,/Passage → Notice → Word → Context → Practice/);assert.match(page,/semantic range is not a menu of meanings/);assert.match(page,/grammar, sentence, author, genre/);assert.match(page,/never force a fixed number/);});
test("Learning Lab preserves Memory, L&F Studies, and Emmaus as distinct next steps",async()=>{const learn=await source("app","learn","page.tsx");assert.match(learn,/\/memory/);assert.match(learn,/\/library\?type=study/);assert.match(learn,/\/auth\/emmaus\?next=\/study/);assert.match(learn,/Emmaus remains the deeper investigation environment/);});
test("Memory Verse mode remains member progress based and WEB sourced",async()=>{const [page,migration]=await Promise.all([source("app","memory","page.tsx"),source("supabase","migrations","20260912195700_add_member_learning_modes.sql")]);assert.match(page,/memory_verse_progress/);assert.match(page,/mastery/);assert.match(migration,/translation text not null default 'WEB'/);});