import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import path from "node:path";
import test from "node:test";

const root = process.cwd();
async function routeFiles(directory){const entries=await readdir(directory,{withFileTypes:true});const nested=await Promise.all(entries.map(async(entry)=>{const fullPath=path.join(directory,entry.name);if(entry.isDirectory())return routeFiles(fullPath);return entry.name==="route.ts"?[fullPath]:[]}));return nested.flat()}
async function sourceFiles(directory){const entries=await readdir(directory,{withFileTypes:true});const nested=await Promise.all(entries.map(async(entry)=>{const fullPath=path.join(directory,entry.name);if(entry.isDirectory())return sourceFiles(fullPath);return /\.(?:ts|tsx)$/.test(entry.name)?[fullPath]:[]}));return nested.flat()}

test("all admin routes using the service role verify the caller is an admin",async()=>{const files=await routeFiles(path.join(root,"app","api","admin"));for(const file of files){const source=await readFile(file,"utf8");if(!source.includes("createAdminClient"))continue;assert.match(source,/auth\.getUser\(\)/,`${file} must authenticate`);assert.match(source,/callerProfile\?\.role !== "admin"/,`${file} must verify the admin role`)}});

test("non-admin page requests leave the admin navigation area",async()=>{const adminPages=["page.tsx","analytics/page.tsx","content/page.tsx","feedback/page.tsx","users/page.tsx"];for(const relativePath of adminPages){const file=path.join(root,"app","admin",relativePath);const source=await readFile(file,"utf8");assert.match(source,/if\s*\((?:!isAdmin|effectiveRole\s*!==\s*"admin")\)\s*(?:\{\s*)?redirect\("\/dashboard"\);?(?:\s*\})?/,`${file} must redirect ordinary members away from admin navigation`)}});

test("every scheduled cron route fails closed and verifies the Vercel cron bearer secret",async()=>{const config=JSON.parse(await readFile(path.join(root,"vercel.json"),"utf8"));assert.ok(config.crons.length>0,"expected a scheduled cron route");for(const cron of config.crons){const file=path.join(root,"app",...cron.path.split("/").filter(Boolean),"route.ts");const source=await readFile(file,"utf8");assert.match(source,/const cronSecret = process\.env\.CRON_SECRET/,`${file} must load CRON_SECRET explicitly`);assert.match(source,/authorization/,`${file} must read authorization`);assert.match(source,/if \(!cronSecret \|\| authHeader !== `Bearer \$\{cronSecret\}`\)/,`${file} must fail closed when CRON_SECRET is missing or invalid`);assert.match(source,/status:\s*401/,`${file} must reject invalid callers`)}});

test("service-role credentials never appear in public environment variables",async()=>{const source=await readFile(path.join(root,".env.example"),"utf8");assert.doesNotMatch(source,/NEXT_PUBLIC_[A-Z0-9_]*SERVICE_ROLE/);assert.match(source,/^SUPABASE_SERVICE_ROLE_KEY=$/m)});

test("Rare Network branding stays out of the L&F runtime surface",async()=>{const roots=[path.join(root,"app"),path.join(root,"components")];for(const directory of roots){const files=await sourceFiles(directory);for(const file of files){const source=await readFile(file,"utf8");assert.doesNotMatch(source,/Rare Network|Rare of Breed/i,`${file} must not expose Rare branding or product references inside L&F`)}}});

test("new-member operational notifications are admin-only",async()=>{const migrationSource=await readFile(path.join(root,"supabase","migrations","20260730163402_admin_only_member_notifications.sql"),"utf8");const buildInfoSource=await readFile(path.join(root,"app","api","build-info","route.ts"),"utf8");assert.match(migrationSource,/where prof\.role = 'admin'/);assert.doesNotMatch(migrationSource,/prof\.role in \('admin','pastor','prayer_team'\)/);assert.match(migrationSource,/n\.type = 'new_member'/);assert.match(migrationSource,/recipient\.role <> 'admin'/);assert.match(migrationSource,/to_regclass\('public\.notifications'\) is not null/);assert.match(migrationSource,/to_regclass\('public\.profiles'\) is not null/);assert.match(buildInfoSource,/VERCEL_GIT_COMMIT_SHA/);assert.doesNotMatch(buildInfoSource,/callerProfile/)});

test("legacy assignment notification links are migrated to Community Prayer",async()=>{const s=await readFile(path.join(root,"supabase","migrations","20260817005006_retire_prayer_care_architecture.sql"),"utf8");assert.match(s,/when type in \('prayed_for', 'status_change', 'check_in_needed'\)/);assert.match(s,/then '\/prayer\/my-requests'/);assert.match(s,/else '\/prayer'/);assert.match(s,/legacy Prayer Care notification is retained for your history/)});

test("legacy standalone product boundary remains represented for migration safety",async()=>{const s=await readFile(path.join(root,"app","programs","page.tsx"),"utf8");for(const program of ["EMAS / Emmaus","Bible Trivia","Devotions"])assert.match(s,new RegExp(`title: "${program}"`));assert.match(s,/const separateProducts =/)});

test("prayer submission does not invoke the retired assignment notifier",async()=>{const s=await readFile(path.join(root,"app","prayer","submit","page.tsx"),"utf8");assert.doesNotMatch(s,/notify-assignment|assigneeId|get_prayer_request_assignment/);assert.match(s,/href="\/prayer\/my-requests"/);assert.doesNotMatch(s,/JSON\.stringify\(\{[\s\S]*assigneeId:/);assert.doesNotMatch(s,/\.rpc\(\s*"get_prayer_request_assignment"/)});

test("signed-in users can reach role-aware help manuals from the account menu",async()=>{const menu=await readFile(path.join(root,"components","AuthControls.tsx"),"utf8");const help=await readFile(path.join(root,"app","help","page.tsx"),"utf8");assert.match(menu,/href:\s*"\/help"/);assert.match(menu,/label:\s*"Help & User Manuals"/);assert.match(help,/showAdminGuide=\{effectiveRole === "admin"\}/);assert.doesNotMatch(help,/prayer_team|pastor|showPrayerTeamGuide/)});

test("members update or withdraw only their own prayer requests",async()=>{const client=await readFile(path.join(root,"components","MyPrayerRequestsClient.tsx"),"utf8");const route=await readFile(path.join(root,"app","api","prayer-requests","mine","update","route.ts"),"utf8");assert.match(client,/fetch\("\/api\/prayer-requests\/mine\/update"/);assert.doesNotMatch(client,/\.from\("prayer_requests"\)/);assert.match(route,/auth\.getUser\(\)/);assert.match(route,/\.eq\("user_id", user\.id\)/);assert.match(route,/status: "Withdrawn", archived: true, is_public: false/)});

test("linked praise reports can only answer the requester's own prayer",async()=>{const client=await readFile(path.join(root,"components","PraiseSubmitClient.tsx"),"utf8");const route=await readFile(path.join(root,"app","api","praise-reports","submit","route.ts"),"utf8");assert.match(client,/fetch\("\/api\/praise-reports\/submit"/);assert.doesNotMatch(client,/\.from\("prayer_requests"\)/);assert.match(route,/auth\.getUser\(\)/);assert.match(route,/\.from\("prayer_requests"\)[\s\S]*\.eq\("id", prayerRequestId\)[\s\S]*\.eq\("user_id", user\.id\)/);assert.match(route,/\.update\(\{\s*answered:\s*true,\s*status:\s*"Resolved"\s*\}\)/)});

test("prayer assignment updates are permanently retired",async()=>{const s=await readFile(path.join(root,"app","api","prayer-assignments","update","route.ts"),"utf8");assert.match(s,/retiredPrayerCareResponse/);assert.doesNotMatch(s,/assigned_to|ALLOWED_FIELDS|prayer_requests/)});
