"use server";
import {redirect} from "next/navigation";import {revalidatePath} from "next/cache";import {createClient} from "@/lib/supabase/server";import {createAdminClient} from "@/lib/supabase/admin";
async function requireAdmin(){const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)redirect("/login");const{data:p}=await s.from("profiles").select("role").eq("id",user.id).single();if(p?.role!=="admin")redirect("/dashboard");return user}
export async function sendAdminNotification(f:FormData){const user=await requireAdmin();const admin=createAdminClient();const title=String(f.get("title")||"").trim(),body=String(f.get("body")||"").trim(),link=String(f.get("link")||"").trim()||null,audience=String(f.get("audience")||"all"),ministry=String(f.get("ministry")||"").trim()||null,confirm=String(f.get("confirm")||"");if(!title||!body)throw new Error("Title and message are required.");if(audience==="all"&&confirm!=="SEND TO ALL")throw new Error('Type "SEND TO ALL" to confirm a full-member broadcast.');let ids:string[]=[];
if(audience==="all"){const{data,error}=await admin.from("profiles").select("id");if(error)throw error;ids=(data||[]).map(x=>x.id)}
else if(audience==="admins"){const{data,error}=await admin.from("profiles").select("id").eq("role","admin");if(error)throw error;ids=(data||[]).map(x=>x.id)}
else if(audience==="ministry"){if(!ministry)throw new Error("Choose a ministry.");const{data,error}=await admin.from("ministry_memberships").select("user_id").eq("ministry_slug",ministry);if(error)throw error;ids=(data||[]).map(x=>x.user_id)}
else if(audience==="leaders"){const q=admin.from("ministry_memberships").select("user_id").eq("membership_role","leader");const{data,error}=ministry?await q.eq("ministry_slug",ministry):await q;if(error)throw error;ids=(data||[]).map(x=>x.user_id)}
else if(audience==="prayer_team"){const{data,error}=await admin.from("profiles").select("id").eq("rotation_status","active");if(error)throw error;ids=(data||[]).map(x=>x.id)}
ids=[...new Set(ids)];if(!ids.length)throw new Error("No recipients matched this audience.");const{data:campaign,error:campaignError}=await admin.from("notification_campaigns").insert({title,body,link,audience_type:audience,audience_value:ministry,created_by:user.id,recipient_count:ids.length}).select("id").single();if(campaignError)throw campaignError;const rows=ids.map(id=>({user_id:id,type:"admin_broadcast",title,body,link,campaign_id:campaign.id}));const{error}=await admin.from("notifications").insert(rows);if(error)throw error;revalidatePath("/admin/notifications");revalidatePath("/notifications");}
