import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { createStudy, endAndReleaseDailyPath, provisionLiveSession, toggleStudy } from "./actions";
import { ministryPortals } from "@/lib/ministry-hub";
import LiveStudySessionForm from "@/components/LiveStudySessionForm";

const slideExample='[{"title":"Opening","scripture":"Luke 15:1-7","body":"Teaching point...","discussion":"What stands out?","journal":"Where do you see yourself?","notes":"Leader talking point"}]';
const devotionalExample='[{"title":"Known by the Shepherd","scripture":"Luke 15:4","teaching":"Teaching point...","story":"Relatable story...","prompt":"Journal prompt..."}]';
function formatSessionTime(value:string|null){if(!value)return"Time not set";return new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:"America/New_York"}).format(new Date(value));}

export default async function Page(){
 const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)redirect("/login");const{data:p}=await s.from("profiles").select("role").eq("id",user.id).single();const isAdmin=p?.role==="admin";
 const{data:facilitatorMemberships}=await s.from("study_group_members").select("group_id").eq("user_id",user.id).eq("group_role","facilitator").eq("membership_status","active");const facilitatorGroupIds=new Set((facilitatorMemberships||[]).map(m=>m.group_id));if(!isAdmin&&facilitatorGroupIds.size===0)redirect("/dashboard");
 const db=createAdminClient();const[{data:studies},{data:allPeople},{data:allSessions},{data:allGroups},{data:allGroupMembers}]=await Promise.all([
  db.from("bible_studies").select("id,title,ministry_slug,is_published,created_at").order("created_at",{ascending:false}),
  db.from("profiles").select("id,full_name,email,is_active").eq("is_active",true).order("full_name",{ascending:true}),
  db.from("study_sessions").select("id,bible_study_id,ministry_slug,group_id,facilitator_user_id,scheduled_start,scheduled_end,status,daily_path_released_at,google_meeting_uri,google_meeting_code,google_organizer_email").order("scheduled_start",{ascending:false}).limit(60),
  db.from("study_groups").select("id,name,ministry_slug,status").eq("status","active").order("name"),
  db.from("study_group_members").select("group_id,user_id,group_role,membership_status").eq("membership_status","active")
 ]);
 const groups=(allGroups||[]).filter(g=>isAdmin||facilitatorGroupIds.has(g.id));const allowedGroupIds=new Set(groups.map(g=>g.id));const groupMembers=(allGroupMembers||[]).filter(m=>allowedGroupIds.has(m.group_id));const allowedPeopleIds=new Set(groupMembers.map(m=>m.user_id));const people=(allPeople||[]).filter(person=>isAdmin||allowedPeopleIds.has(person.id));const sessions=(allSessions||[]).filter(session=>isAdmin||(session.group_id&&allowedGroupIds.has(session.group_id)));
 const studyMap=new Map((studies||[]).map(x=>[x.id,x]));const peopleMap=new Map(people.map(x=>[x.id,x]));const groupMap=new Map(groups.map(x=>[x.id,x]));const published=(studies||[]).filter(x=>x.is_published);
 const groupsForForm=groups.map(g=>({id:g.id,name:g.name,ministry_slug:g.ministry_slug,memberIds:groupMembers.filter(m=>m.group_id===g.id).map(m=>m.user_id),facilitatorIds:groupMembers.filter(m=>m.group_id===g.id&&m.group_role==="facilitator").map(m=>m.user_id)}));
 return <main className="lfp-page pb-24"><div className="lfp-shell py-10"><Link href={isAdmin?"/admin":"/dashboard"} className="text-sm font-black text-indigo-700">← {isAdmin?"Admin Center":"My Path"}</Link><div className="mt-6 flex flex-wrap items-end justify-between gap-4"><div><p className="lfp-eyebrow">Bible Studies & Live Gatherings</p><h1 className="mt-2 text-4xl font-black">{isAdmin?"Study Publishing":"Facilitator Workspace"}</h1><p className="mt-3 max-w-3xl text-slate-600">Schedule gatherings, choose a saved group, select the final session roster, and carry that exact roster into notifications, My Path, and Daily Path.</p></div>{isAdmin&&<Link href="/admin/studies/groups" className="lfp-button border bg-white text-slate-950">Manage Study Groups</Link>}</div>
 <section className="mt-10 rounded-3xl border border-indigo-100 bg-indigo-50/50 p-5 sm:p-7"><p className="lfp-eyebrow">Live Studies</p><h2 className="mt-2 text-3xl font-black">Schedule a gathering</h2><p className="mt-2 max-w-2xl text-slate-600">Choose a saved group to preload its active roster, then include or remove individual members for this session. Facilitators only see groups they lead.</p><LiveStudySessionForm studies={published} facilitators={people} participants={people} ministries={ministryPortals.map(m=>({slug:m.slug,title:m.title}))} groups={groupsForForm}/>
 <div className="mt-8"><h3 className="text-xl font-black">Scheduled sessions</h3><div className="mt-4 grid gap-3">{!sessions.length&&<div className="rounded-2xl border border-dashed bg-white p-6 text-sm font-bold text-slate-500">No live studies are scheduled yet.</div>}{sessions.map(session=>{const study=studyMap.get(session.bible_study_id);const facilitator=session.facilitator_user_id?peopleMap.get(session.facilitator_user_id):null;const group=session.group_id?groupMap.get(session.group_id):null;return <article key={session.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-widest text-indigo-700">{session.ministry_slug}{group?` · ${group.name}`:""}</p><h4 className="mt-1 text-lg font-black">{study?.title||"Bible Study"}</h4><p className="mt-1 text-sm font-bold text-slate-600">{formatSessionTime(session.scheduled_start)} ET{session.scheduled_end?` – ${formatSessionTime(session.scheduled_end)} ET`:""}</p><p className="mt-1 text-sm text-slate-500">Facilitator: {facilitator?.full_name||facilitator?.email||"Organizer only"}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black uppercase text-slate-600">{session.status}</span></div><div className="mt-4 flex flex-wrap gap-2 border-t pt-4">{session.google_meeting_uri?<><a href={session.google_meeting_uri} target="_blank" rel="noreferrer" className="lfp-button bg-indigo-700 text-white">Open Google Meet</a><span className="rounded-xl bg-emerald-50 px-3 py-2 text-sm font-black text-emerald-700">Meet ready{session.google_meeting_code?` · ${session.google_meeting_code}`:""}</span></>:session.status!=="completed"&&<form action={provisionLiveSession}><input type="hidden" name="session_id" value={session.id}/><button className="lfp-button bg-amber-300 text-slate-950">Create Google Meet</button></form>}{session.daily_path_released_at?<span className="rounded-xl bg-violet-50 px-3 py-2 text-sm font-black text-violet-700">Daily Path released</span>:session.status!=="cancelled"&&<form action={endAndReleaseDailyPath}><input type="hidden" name="session_id" value={session.id}/><button className="rounded-xl border border-violet-200 bg-violet-50 px-3 py-2 text-sm font-black text-violet-800">End Study & Release Daily Path</button></form>}{study?.is_published&&<Link href={`/studies/${study.id}`} className="rounded-xl border px-3 py-2 text-sm font-black">View member study</Link>}</div></article>})}</div></div></section>
 {isAdmin&&<><section className="mt-12"><p className="lfp-eyebrow">Study Builder</p><h2 className="mt-2 text-2xl font-black">Create a Bible study</h2><form action={createStudy} className="lfp-card mt-6 grid gap-4 p-6 sm:grid-cols-2"><label className="text-sm font-bold">Title<input required name="title" className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-bold">Subtitle<input name="subtitle" className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-bold">Ministry<select name="ministry_slug" className="mt-1 w-full rounded-xl border p-3"><option value="">L&F General</option>{ministryPortals.map(m=><option key={m.slug} value={m.slug}>{m.title}</option>)}</select></label><label className="text-sm font-bold">Scripture references, one per line<textarea name="scripture_refs" rows={3} className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-bold sm:col-span-2">Description<textarea name="description" rows={3} className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-bold sm:col-span-2">Study slides (JSON)<textarea required name="slides" defaultValue={slideExample} rows={8} className="mt-1 w-full rounded-xl border p-3 font-mono text-xs"/></label><label className="text-sm font-bold sm:col-span-2">Daily Path cards (JSON)<textarea name="devotional_cards" defaultValue={devotionalExample} rows={7} className="mt-1 w-full rounded-xl border p-3 font-mono text-xs"/></label><label className="flex items-center gap-2 font-bold"><input type="checkbox" name="is_published"/> Publish now</label><button className="lfp-button bg-slate-950 text-white sm:col-span-2">Create Bible Study</button></form></section>
 <section className="mt-10"><h2 className="text-2xl font-black">Study Library</h2><div className="mt-4 grid gap-3">{studies?.map(st=><div key={st.id} className="lfp-card flex flex-wrap items-center justify-between gap-3 p-5"><div><h3 className="font-black">{st.title}</h3><p className="text-sm text-slate-500">{st.ministry_slug||"L&F General"} · {st.is_published?"Published":"Draft"}</p></div><div className="flex gap-2">{st.is_published&&<Link href={`/studies/${st.id}`} className="rounded-xl border px-3 py-2 text-sm font-bold">View</Link>}<form action={toggleStudy}><input type="hidden" name="id" value={st.id}/><input type="hidden" name="published" value={String(st.is_published)}/><button className="rounded-xl border px-3 py-2 text-sm font-bold">{st.is_published?"Unpublish":"Publish"}</button></form></div></div>)}</div></section></>}
 </div></main>;
}
