import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

const modes=[
 {href:"/trivia",icon:"?",title:"Bible Trivia",eyebrow:"Play + learn",description:"Use the existing L&F question bank, shuffled from approved categories, with Scripture and teaching after every answer."},
 {href:"/trivia",icon:"α",title:"Language Insights",eyebrow:"Hebrew + Greek",description:"Learn important original-language concepts while staying anchored to context instead of one-word shortcuts."},
 {href:"/memory",icon:"✦",title:"Memory Verses",eyebrow:"Remember",description:"Read, fill missing words, recall from memory, and return through spaced review."},
 {href:"/library?type=study",icon:"▤",title:"L&F Studies",eyebrow:"Go deeper",description:"Open curated studies or launch into Emmaus when the study belongs there."}
];
export default async function LearnPage(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");return <main className="lfp-page pb-24"><section className="relative overflow-hidden"><div aria-hidden className="lfp-grid absolute inset-0"/><div className="lfp-shell relative py-10 sm:py-14"><p className="lfp-eyebrow">Member Learning Lab</p><h1 className="mt-3 max-w-4xl text-4xl font-black tracking-[-.045em] text-slate-950 sm:text-6xl">Play. Learn. Remember. <span className="lfp-gradient-text">Dig deeper.</span></h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">This is an authenticated member experience. The learning content itself is not exposed on the public website.</p></div></section><div className="lfp-shell py-8"><div className="grid gap-4 md:grid-cols-2">{modes.map(m=><Link key={m.title} href={m.href} className="lfp-card p-6 sm:p-7"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-xl font-black text-blue-700">{m.icon}</span><p className="mt-5 text-[11px] font-black uppercase tracking-[.17em] text-blue-700">{m.eyebrow}</p><h2 className="mt-1 text-2xl font-black text-slate-950">{m.title}</h2><p className="mt-3 leading-7 text-slate-600">{m.description}</p><span className="mt-5 inline-flex font-black text-blue-700">Open →</span></Link>)}</div><section className="mt-8 rounded-[2rem] bg-[rgb(var(--lfp-ink))] p-7 text-white sm:p-8"><p className="text-[11px] font-black uppercase tracking-[.17em] text-sky-300">Learning philosophy</p><h2 className="mt-2 text-3xl font-black">Knowledge should lead somewhere.</h2><p className="mt-3 max-w-3xl leading-7 text-slate-300">Trivia, Language Insights, memory work, Emmaus, and L&F studies are being connected so a quick interaction can become deeper Scripture study and practical application.</p></section></div></main>}
