import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

const modes=[
 {href:"/trivia",icon:"✦",title:"Daily Challenge",eyebrow:"Come back daily",description:"A rotating seven-question challenge drawn from the approved L&F Bible learning bank."},
 {href:"/trivia",icon:"?",title:"Bible Trivia",eyebrow:"Play + learn",description:"Choose categories and difficulty, then learn from Scripture and an After the Answer teaching note."},
 {href:"/trivia",icon:"α",title:"Language Insights",eyebrow:"Hebrew + Greek",description:"Learn original-language concepts with context, grammar, and guardrails against shallow word-study shortcuts."},
 {href:"/memory",icon:"▤",title:"Memory Verses",eyebrow:"Remember",description:"Read, retrieve missing words, recall from memory, and return through spaced review as mastery grows."},
 {href:"/library?type=study",icon:"◇",title:"L&F Studies",eyebrow:"Understand",description:"Move from quick learning into curated studies, application, discussion, journaling, and devotional follow-up."},
 {href:"/auth/emmaus?next=/study",icon:"→",title:"Emmaus",eyebrow:"Dig deeper",description:"Carry a question or Scripture insight into the full Emmaus study environment without another login."}
];
export default async function LearnPage(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const [{count:questions},{count:verses}]=await Promise.all([supabase.from("trivia_questions").select("id",{count:"exact",head:true}).eq("status","approved"),supabase.from("memory_verses").select("id",{count:"exact",head:true}).eq("is_active",true)]);return <main className="lfp-page pb-24"><section className="relative overflow-hidden"><div aria-hidden className="lfp-grid absolute inset-0"/><div className="lfp-shell relative py-10 sm:py-14"><p className="lfp-eyebrow">Member Learning Lab</p><h1 className="mt-3 max-w-4xl text-4xl font-black tracking-[-.045em] text-slate-950 sm:text-6xl">Play. Learn. Remember. <span className="lfp-gradient-text">Understand. Apply.</span></h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">Fast Bible learning should create curiosity, not stop it. Every mode is designed to move you toward Scripture, context, memory, and faithful application.</p><div className="mt-8 grid grid-cols-2 gap-3 sm:max-w-xl"><Stat value={String(questions??0)} label="Approved questions"/><Stat value={String(verses??0)} label="Memory verses"/></div></div></section><div className="lfp-shell py-8"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{modes.map(m=><Link key={m.title} href={m.href} className="lfp-card p-6 sm:p-7"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-xl font-black text-blue-700">{m.icon}</span><p className="mt-5 text-[11px] font-black uppercase tracking-[.17em] text-blue-700">{m.eyebrow}</p><h2 className="mt-1 text-2xl font-black text-slate-950">{m.title}</h2><p className="mt-3 leading-7 text-slate-600">{m.description}</p><span className="mt-5 inline-flex font-black text-blue-700">Open →</span></Link>)}</div><section className="mt-8 rounded-[2rem] bg-[rgb(var(--lfp-ink))] p-7 text-white sm:p-8"><p className="text-[11px] font-black uppercase tracking-[.17em] text-sky-300">Learning pathway</p><h2 className="mt-2 text-3xl font-black">Play → Learn → Remember → Understand → Apply</h2><p className="mt-3 max-w-3xl leading-7 text-slate-300">Trivia can expose a gap. Language Insights can sharpen observation. Memory work can make Scripture portable. Emmaus and L&F Studies can provide context and depth. The destination is faithful living—not a leaderboard.</p></section></div></main>}
function Stat({value,label}:{value:string;label:string}){return <div className="lfp-glass rounded-2xl p-4"><p className="text-2xl font-black text-slate-950">{value}</p><p className="text-xs font-bold text-slate-500">{label}</p></div>}
