import Link from "next/link";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";
import {getMinistryAssignments} from "@/lib/access-control";
import {grantMinistryMemberRole,revokeMinistryMemberRole} from "./actions";

export default async function MinistryAccessPage(){
 const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)redirect("/login");
 const assignments=await getMinistryAssignments();const led=[...new Set(assignments.filter((r:any)=>r.role_key==="leader").map((r:any)=>r.ministry_key))];if(!led.length)redirect("/dashboard");
 const {data:rows}=await s.from("ministry_role_assignments").select("id,user_id,ministry_key,role_key,granted_at").in("ministry_key",led).is("revoked_at",null).order("granted_at",{ascending:false});
 const admin=createAdminClient();const userIds=[...new Set((rows??[]).map((r:any)=>r.user_id))];const {data:profiles}=userIds.length?await admin.from("profiles").select("id,full_name,email").in("id",userIds):{data:[] as any[]};const people=new Map((profiles??[]).map((p:any)=>[p.id,p]));
 return <main className="lfp-page pb-24"><section className="bg-slate-950 text-white"><div className="lfp-shell py-10"><Link href="/dashboard" className="text-sm font-black text-sky-200">← Dashboard</Link><p className="mt-6 text-xs font-black uppercase tracking-[.2em] text-amber-300">Ministry Access</p><h1 className="mt-2 text-4xl font-black">Participants & facilitators</h1><p className="mt-3 max-w-3xl text-slate-300">Manage people only inside ministries you lead. Ministry Leader authority cannot be granted from this screen.</p></div></section><div className="lfp-shell py-8 space-y-8"><section className="lfp-card p-6"><h2 className="text-2xl font-black">Add ministry access</h2><form action={grantMinistryMemberRole} className="mt-5 grid gap-3 sm:grid-cols-2"><input required type="email" name="email" placeholder="member@email.com" className="rounded-xl border p-3"/><select required name="ministry_key" className="rounded-xl border p-3">{led.map((m:string)=><option key={m} value={m}>{m}</option>)}</select><select required name="role_key" className="rounded-xl border p-3"><option value="participant">Participant</option><option value="facilitator">Facilitator</option></select><button className="lfp-button bg-slate-950 text-white">Grant Access</button></form></section><section><p className="lfp-eyebrow">Current assignments</p><div className="mt-4 grid gap-3">{rows?.map((r:any)=>{const p=people.get(r.user_id);return <article key={r.id} className="lfp-card flex flex-wrap items-center justify-between gap-3 p-5"><div><h3 className="font-black">{p?.full_name||p?.email||r.user_id}</h3><p className="text-sm text-slate-500">{p?.email} · {r.ministry_key} · {r.role_key}</p></div>{r.role_key!=="leader"&&<form action={revokeMinistryMemberRole}><input type="hidden" name="user_id" value={r.user_id}/><input type="hidden" name="ministry_key" value={r.ministry_key}/><input type="hidden" name="role_key" value={r.role_key}/><button className="rounded-xl border px-3 py-2 text-sm font-black">Revoke</button></form>}</article>})}</div></section></div></main>;
}
