import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getEffectiveRole } from "@/lib/effective-role";

const lanes=[
 {href:"/admin/library",eyebrow:"Discover & Library",title:"Library, collections & media",description:"Create L&F Original resources, curate L&F Approved material, and register Emmaus handoffs without duplicating Emmaus content.",icon:"▦"},
 {href:"/admin/study-journeys",eyebrow:"Bible Study",title:"Facilitator Study Center",description:"Select an approved live study, conduct the gathering, and launch its 14-day app discipleship journey.",icon:"▣"},
 {href:"/admin/ministries",eyebrow:"Ministry Spaces",title:"Ministry publishing",description:"Publish gatherings, announcements, resources, studies, and service opportunities into Interactive Ministry Spaces.",icon:"⌂"},
 {href:"/admin/content",eyebrow:"Community",title:"Community moderation",description:"Review praise reports and testimonies separately from editorial publishing so moderation never gets confused with content creation.",icon:"◇"},
];
export default async function CreatorStudioPage(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const{data:profile}=await supabase.from("profiles").select("role,preview_role").eq("id",user.id).single();if(getEffectiveRole(profile?.role,profile?.preview_role)!=="admin")redirect("/dashboard");const[{data:catalog},{data:studies},{data:ministryContent}]=await Promise.all([supabase.from("content_catalog").select("id,is_published,is_featured,content_type,provenance"),supabase.from("bible_studies").select("id,status"),supabase.from("ministry_content").select("id,is_published,is_featured,content_type")]);const catalogRows=catalog??[],studyRows=studies??[],ministryRows=ministryContent??[];const liveCatalog=catalogRows.filter((x:any)=>x.is_published).length;const draftCatalog=catalogRows.length-liveCatalog;const liveStudies=studyRows.filter((x:any)=>x.status==="approved").length;const liveMinistry=ministryRows.filter((x:any)=>x.is_published).length;const featured=catalogRows.filter((x:any)=>x.is_featured).length+ministryRows.filter((x:any)=>x.is_featured).length;return <main className="lfp-page pb-24"><section className="relative overflow-hidden bg-slate-950 text-white"><div className="lfp-shell relative py-10 sm:py-14"><Link href="/admin" className="text-sm font-black text-sky-200">← Administration Center</Link><p className="mt-7 text-xs font-black uppercase tracking-[.2em] text-amber-300">Creator Studio</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">Create once. Publish into the L&F ecosystem.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">Creator Studio is the editorial control room for Discover, the Library, Bible studies, and ministry spaces.</p><div className="mt-8 grid grid-cols-2 gap-3 lg:grid-cols-5"><Stat label="Live catalog items" value={liveCatalog}/><Stat label="Catalog drafts" value={draftCatalog}/><Stat label="Approved studies" value={liveStudies}/><Stat label="Live ministry posts" value={liveMinistry}/><Stat label="Featured items" value={featured}/></div></div></section><div className="lfp-shell py-8 sm:py-12"><p className="lfp-eyebrow">Publishing lanes</p><h2 className="mt-2 text-3xl font-black">Choose what you are creating.</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{lanes.map(l=><Link key={l.href} href={l.href} className="lfp-card group p-6"><span className="text-2xl text-blue-700">{l.icon}</span><p className="mt-5 text-[11px] font-black uppercase tracking-[.16em] text-blue-700">{l.eyebrow}</p><h3 className="mt-1 text-2xl font-black">{l.title}</h3><p className="mt-2 leading-7 text-slate-600">{l.description}</p></Link>)}</div></div></main>}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-white/10 bg-white/[.07] p-4"><p className="text-2xl font-black">{value}</p><p className="mt-1 text-xs text-indigo-100/70">{label}</p></div>}
