"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

async function currentUser(){const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)redirect("/login");return{s,user};}
const t=(f:FormData,k:string)=>String(f.get(k)||"").trim();
async function assertParticipant(s:any,userId:string,sessionId:string){const{data}=await s.from("study_session_participants").select("study_session_id").eq("study_session_id",sessionId).eq("user_id",userId).maybeSingle();if(!data)throw new Error("You are not assigned to this study session.");}
export async function savePrivateJournal(f:FormData){const{s,user}=await currentUser();const sessionId=t(f,"session_id"),day=Number(t(f,"day_number")),response=t(f,"response_text");await assertParticipant(s,user.id,sessionId);const{error}=await s.from("study_daily_responses").upsert({study_session_id:sessionId,user_id:user.id,day_number:day,response_type:"private_journal",response_text:response},{onConflict:"study_session_id,user_id,day_number,response_type"});if(error)throw new Error(error.message);revalidatePath(`/study-path/${sessionId}/${day}`);}
export async function lockGroupResponse(f:FormData){const{s,user}=await currentUser();const sessionId=t(f,"session_id"),day=Number(t(f,"day_number")),response=t(f,"response_text");if(!response)throw new Error("Write your response before revealing the group.");await assertParticipant(s,user.id,sessionId);const{data:existing}=await s.from("study_daily_responses").select("locked_at").eq("study_session_id",sessionId).eq("user_id",user.id).eq("day_number",day).eq("response_type","group_response").maybeSingle();if(existing?.locked_at)throw new Error("Your group response is already locked.");const{error}=await s.from("study_daily_responses").upsert({study_session_id:sessionId,user_id:user.id,day_number:day,response_type:"group_response",response_text:response,locked_at:new Date().toISOString()},{onConflict:"study_session_id,user_id,day_number,response_type"});if(error)throw new Error(error.message);revalidatePath(`/study-path/${sessionId}/${day}`);}
export async function savePersonalReflection(f:FormData){const{s,user}=await currentUser();const sessionId=t(f,"session_id"),day=Number(t(f,"day_number")),response=t(f,"response_text");await assertParticipant(s,user.id,sessionId);const{error}=await s.from("study_daily_responses").upsert({study_session_id:sessionId,user_id:user.id,day_number:day,response_type:"personal_reflection",response_text:response},{onConflict:"study_session_id,user_id,day_number,response_type"});if(error)throw new Error(error.message);revalidatePath(`/study-path/${sessionId}/${day}`);}
export async function completeDailyStudy(f:FormData){const{s,user}=await currentUser();const sessionId=t(f,"session_id"),day=Number(t(f,"day_number"));await assertParticipant(s,user.id,sessionId);const{error}=await s.from("study_daily_progress").upsert({study_session_id:sessionId,user_id:user.id,day_number:day,opened_at:new Date().toISOString(),completed_at:new Date().toISOString()},{onConflict:"study_session_id,user_id,day_number"});if(error)throw new Error(error.message);revalidatePath(`/study-path/${sessionId}/${day}`);revalidatePath("/dashboard");}
