import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { completeDailyStudy, lockGroupResponse, savePersonalReflection, savePrivateJournal } from "./actions";

export default async function DailyStudyPage({params}:{params:Promise<{sessionId:string;day:string}>}){
 const {sessionId,day:dayRaw}=await params;const day=Number(dayRaw);if(!Number.isInteger(day)||day<1||day>31)notFound();
 const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)redirect(`/login?next=/study-path/${sessionId}/${day}`);
 const [{data:participant},{data:session}]=await Promise.all([s.from("study_session_participants").select("study_session_id").eq("study_session_id",sessionId).eq("user_id",user.id).maybeSingle(),s.from("study_sessions").select("id,bible_study_id,scheduled_start,daily_path_released_at,status,bible_studies(id,title,subtitle,devotional_cards)").eq("id",sessionId).maybeSingle()]);
 if(!participant||!session)notFound();const study:any=Array.isArray((session as any).bible_studies)?(session as any).bible_studies[0]:(session as any).bible_studies;const cards=Array.isArray(study?.devotional_cards)?study.devotional_cards:[];const card=cards[day-1];if(!card)notFound();
 if(!session.daily_path_released_at)redirect("/dashboard");const release=new Date(session.daily_path_released_at);const unlockDay=Math.min(cards.length,Math.max(1,Math.floor((Date.now()-release.getTime())/86400000)+1));if(day>unlockDay)redirect(`/study-path/${sessionId}/${unlockDay}`);
 const [{data:responses},{data:progress}]=await Promise.all([s.from("study_daily_responses").select("id,user_id,response_type,response_text,locked_at,created_at").eq("study_session_id",sessionId).eq("day_number",day),s.from("study_daily_progress").select("completed_at").eq("study_session_id",sessionId).eq("user_id",user.id).eq("day_number",day).maybeSingle()]);
 const own=(responses||[]).filter((r:any)=>r.user_id===user.id);const privateJournal=own.find((r:any)=>r.response_type==="private_journal");const groupMine=own.find((r:any)=>r.response_type==="group_response");const reflection=own.find((r:any)=>r.response_type==="personal_reflection");const revealed=Boolean(groupMine?.locked_at);
 let groupResponses:any[]=[];let names=new Map<string,string>();if(revealed){const{data:gr}=await s.from("study_daily_responses").select("user_id,response_text,created_at").eq("study_session_id",sessionId).eq("day_number",day).eq("response_type","group_response").not("locked_at","is",null).order("created_at");groupResponses=gr||[];const ids=Array.from(new Set(groupResponses.map(r=>r.user_id)));if(ids.length){const{data:ps}=await s.from("profiles").select("id,full_name").in("id",ids);names=new Map((ps||[]).map((p:any)=>[p.id,p.full_name||"Group member"]));}}
 const nextDay=day<cards.length?day+1:null;
 return <main className="lfp-page pb-24"><div className="lfp-shell max-w-4xl py-10"><Link href="/dashboard" className="text-sm font-black text-indigo-700">← My Path</Link><p className="lfp-eyebrow mt-6">Daily Path · Day {day} of {cards.length}</p><h1 className="mt-2 text-4xl font-black">{card.title||`Day ${day}`}</h1><p className="mt-2 text-sm font-bold text-slate-500">{study?.title}</p>
 <section className="lfp-card mt-7 p-6"><p className="text-xs font-black uppercase tracking-widest text-indigo-700">Read</p><h2 className="mt-2 text-2xl font-black">{card.scripture||"Scripture"}</h2>{card.teaching&&<><p className="mt-6 text-xs font-black uppercase tracking-widest text-indigo-700">Learn</p><p className="mt-2 text-lg leading-8 text-slate-700">{card.teaching}</p></>}{card.story&&<><p className="mt-6 text-xs font-black uppercase tracking-widest text-indigo-700">Connect</p><p className="mt-2 leading-7 text-slate-600">{card.story}</p></>}{card.prompt&&<><p className="mt-6 text-xs font-black uppercase tracking-widest text-indigo-700">Reflect</p><p className="mt-2 text-xl font-black">{card.prompt}</p></>}</section>
 <section className="lfp-card mt-5 p-6"><h2 className="text-2xl font-black">My Journal</h2><p className="mt-1 text-sm text-slate-500">Private. Only you can see this entry.</p><form action={savePrivateJournal} className="mt-4"><input type="hidden" name="session_id" value={sessionId}/><input type="hidden" name="day_number" value={day}/><textarea name="response_text" defaultValue={privateJournal?.response_text||""} rows={5} className="w-full rounded-2xl border p-4" placeholder="Write what you are noticing, questioning, or praying through…"/><button className="lfp-button mt-3 border bg-white text-slate-950">Save private journal</button></form></section>
 <section className="mt-5 rounded-[1.7rem] border border-indigo-100 bg-indigo-50/60 p-6"><h2 className="text-2xl font-black">Group Response</h2><p className="mt-1 text-sm text-slate-600">Write your own answer first. Once you lock it in, the other responses from this session are revealed. Your original group answer cannot be edited after reveal.</p>{!revealed?<form action={lockGroupResponse} className="mt-4"><input type="hidden" name="session_id" value={sessionId}/><input type="hidden" name="day_number" value={day}/><textarea required name="response_text" defaultValue={groupMine?.response_text||""} rows={5} className="w-full rounded-2xl border bg-white p-4" placeholder="Your answer before seeing the group…"/><button className="lfp-button mt-3 bg-indigo-700 text-white">Lock In My Answer & Reveal Group</button></form>:<><div className="mt-4 rounded-2xl bg-white p-4"><p className="text-xs font-black uppercase tracking-widest text-emerald-700">Your locked response</p><p className="mt-2 whitespace-pre-wrap leading-7">{groupMine.response_text}</p></div><div className="mt-4 grid gap-3">{groupResponses.filter(r=>r.user_id!==user.id).map((r:any,i:number)=><article key={`${r.user_id}-${i}`} className="rounded-2xl bg-white p-4"><p className="text-sm font-black text-indigo-700">{names.get(r.user_id)||"Group member"}</p><p className="mt-2 whitespace-pre-wrap leading-7 text-slate-700">{r.response_text}</p></article>)}{groupResponses.filter(r=>r.user_id!==user.id).length===0&&<p className="rounded-2xl bg-white p-4 text-sm font-bold text-slate-500">No one else has locked an answer yet. Their responses will appear here after they do.</p>}</div></>}</section>
 {revealed&&<section className="lfp-card mt-5 p-6"><h2 className="text-2xl font-black">What I Learned Afterward</h2><p className="mt-1 text-sm text-slate-500">Private follow-up after reading the group.</p><form action={savePersonalReflection} className="mt-4"><input type="hidden" name="session_id" value={sessionId}/><input type="hidden" name="day_number" value={day}/><textarea name="response_text" defaultValue={reflection?.response_text||""} rows={4} className="w-full rounded-2xl border p-4"/><button className="lfp-button mt-3 border bg-white text-slate-950">Save reflection</button></form></section>}
 <form action={completeDailyStudy} className="mt-6"><input type="hidden" name="session_id" value={sessionId}/><input type="hidden" name="day_number" value={day}/><button className="lfp-button w-full bg-slate-950 text-white">{progress?.completed_at?"Completed ✓":"Complete Today"}</button></form>{nextDay&&nextDay<=unlockDay&&<Link href={`/study-path/${sessionId}/${nextDay}`} className="mt-4 block text-center font-black text-indigo-700">Continue to Day {nextDay} →</Link>}
 </div></main>
}
