import Link from "next/link";
import { createAdminClient } from "@/lib/supabase/admin";
import { ministryPortals } from "@/lib/ministry-hub";
import { requireAppCapability } from "@/lib/role-access";
import { archiveStudyGroup, createStudyGroup, saveGroupMembers } from "./actions";

type Props={searchParams?:Promise<{saved?:string;count?:string}>};
export default async function StudyGroupsPage({searchParams}:Props){
 const params=await searchParams;const savedGroup=params?.saved||"";const savedCount=Number(params?.count||0);await requireAppCapability("study_groups");
 const db=createAdminClient();const[{data:groups},{data:people},{data:members}]=await Promise.all([
  db.from("study_groups").select("*").eq("status","active").order("name"),
  db.from("profiles").select("id,full_name,email,is_active").eq("is_active",true).order("full_name"),
  db.from("study_group_members").select("group_id,user_id,group_role,membership_status").eq("membership_status","active")
 ]);
 const byGroup=new Map<string,any[]>();for(const m of members||[]){if(!byGroup.has(m.group_id))byGroup.set(m.group_id,[]);byGroup.get(m.group_id)!.push(m)}
 return <main className="lfp-page pb-24"><div className="lfp-shell py-10"><Link href="/admin/studies" className="text-sm font-black text-indigo-700">← Live Studies & Publishing</Link><p className="lfp-eyebrow mt-6">Study Groups</p><h1 className="mt-2 text-4xl font-black">Manage groups</h1><p className="mt-3 max-w-3xl text-slate-600">Create recurring groups, assign facilitators and members, then use the group as the starting roster for each live study session.</p>
 <section className="lfp-card mt-8 p-6"><h2 className="text-2xl font-black">Create a group</h2><form action={createStudyGroup} className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Group name<input name="name" required className="mt-1 w-full rounded-xl border p-3" placeholder="Tuesday Men’s Group"/></label><label className="text-sm font-bold">Ministry<select name="ministry_slug" required className="mt-1 w-full rounded-xl border p-3"><option value="">Choose ministry</option>{ministryPortals.map(m=><option key={m.slug} value={m.slug}>{m.title}</option>)}</select></label><label className="text-sm font-bold sm:col-span-2">Description<textarea name="description" rows={2} className="mt-1 w-full rounded-xl border p-3"/></label><button className="lfp-button bg-slate-950 text-white sm:col-span-2">Create group</button></form></section>
 <section className="mt-8 grid gap-5">{(groups||[]).map(g=>{const current=byGroup.get(g.id)||[];const currentIds=new Set(current.map(x=>x.user_id));const facilitatorIds=new Set(current.filter(x=>x.group_role==="facilitator").map(x=>x.user_id));const justSaved=savedGroup===g.id;return <details key={g.id} className="lfp-card p-6" open={!justSaved}><summary className="cursor-pointer list-none"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-widest text-indigo-700">{g.ministry_slug}</p><h2 className="mt-1 text-2xl font-black">{g.name}</h2>{g.description&&<p className="mt-2 text-slate-600">{g.description}</p>}<p className="mt-2 text-sm font-bold text-slate-500">{current.length} active member{current.length===1?"":"s"}</p></div><span className="rounded-xl border px-3 py-2 text-sm font-bold text-indigo-700">Open / Close</span></div>{justSaved&&<div role="status" className="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 font-bold text-emerald-800">✓ Group membership saved — {savedCount} active member{savedCount===1?"":"s"}. Select the group to reopen it.</div>}</summary><div className="mt-5 border-t pt-5"><div className="flex justify-end"><form action={archiveStudyGroup}><input type="hidden" name="group_id" value={g.id}/><button className="rounded-xl border px-3 py-2 text-sm font-bold text-slate-600">Archive</button></form></div><form action={saveGroupMembers} className="mt-4"><input type="hidden" name="group_id" value={g.id}/><div className="grid max-h-96 gap-2 overflow-y-auto rounded-2xl border bg-slate-50 p-3 md:grid-cols-2">{(people||[]).map(person=><label key={person.id} className="rounded-xl bg-white p-3 text-sm shadow-sm"><div className="flex items-center gap-3"><input type="checkbox" name="member_user_id" value={person.id} defaultChecked={currentIds.has(person.id)}/><span><strong>{person.full_name||"L&F member"}</strong>{person.email&&<small className="block text-slate-500">{person.email}</small>}</span></div><div className="mt-2 pl-7"><label className="flex items-center gap-2 text-xs font-bold text-indigo-700"><input type="checkbox" name="facilitator_user_id" value={person.id} defaultChecked={facilitatorIds.has(person.id)}/> Facilitator</label></div></label>)}</div><button className="lfp-button mt-4 bg-indigo-700 text-white">Save membership</button></form></div></details>})}</section>
 </div></main>
}
