"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

async function requireAdmin() { const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect("/login"); const {data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).single(); if(profile?.role!=="admin") redirect("/dashboard"); return {supabase,user}; }
function value(formData:FormData,key:string){return String(formData.get(key)||"").trim()||null;}
function refresh(slug:string){revalidatePath("/admin/ministries");revalidatePath(`/ministries/${slug}`);revalidatePath("/events");}

export async function createMinistryContent(formData:FormData){const {supabase,user}=await requireAdmin();const ministry_slug=String(formData.get("ministry_slug")||"");const title=value(formData,"title");if(!title)return;const {error}=await supabase.from("ministry_content").insert({ministry_slug,content_type:String(formData.get("content_type")||""),title,summary:value(formData,"summary"),body:value(formData,"body"),link_url:value(formData,"link_url"),location:value(formData,"location"),starts_at:value(formData,"starts_at"),ends_at:value(formData,"ends_at"),action_label:value(formData,"action_label"),is_published:formData.get("is_published")==="on",is_featured:formData.get("is_featured")==="on",created_by:user.id});if(error)throw new Error(error.message);refresh(ministry_slug);}
export async function updateMinistryContent(formData:FormData){const {supabase}=await requireAdmin();const id=String(formData.get("id")||"");const ministry_slug=String(formData.get("ministry_slug")||"");const title=value(formData,"title");if(!id||!title)return;const {error}=await supabase.from("ministry_content").update({content_type:String(formData.get("content_type")||""),title,summary:value(formData,"summary"),body:value(formData,"body"),link_url:value(formData,"link_url"),location:value(formData,"location"),starts_at:value(formData,"starts_at"),ends_at:value(formData,"ends_at"),action_label:value(formData,"action_label"),is_featured:formData.get("is_featured")==="on",updated_at:new Date().toISOString()}).eq("id",id);if(error)throw new Error(error.message);refresh(ministry_slug);}
export async function toggleMinistryContent(formData:FormData){const {supabase}=await requireAdmin();const id=String(formData.get("id"));const ministry_slug=String(formData.get("ministry_slug"));const is_published=formData.get("is_published")==="true";const {error}=await supabase.from("ministry_content").update({is_published:!is_published,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw new Error(error.message);refresh(ministry_slug);}
export async function deleteMinistryContent(formData:FormData){const {supabase}=await requireAdmin();const id=String(formData.get("id"));const ministry_slug=String(formData.get("ministry_slug"));const {error}=await supabase.from("ministry_content").delete().eq("id",id);if(error)throw new Error(error.message);refresh(ministry_slug);}
