"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

async function requireManager(slug?:string){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const {data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(profile?.role==="admin")return{supabase,user,isAdmin:true};if(slug){const {data:lead}=await supabase.from("ministry_memberships").select("id").eq("user_id",user.id).eq("ministry_slug",slug).eq("membership_role","leader").maybeSingle();if(lead)return{supabase,user,isAdmin:false};}redirect("/dashboard");}
function value(formData:FormData,key:string){return String(formData.get(key)||"").trim()||null;}
function refresh(slug:string){revalidatePath("/admin/ministries");revalidatePath(`/ministries/${slug}`);revalidatePath("/events");revalidatePath("/notifications");revalidatePath("/dashboard");}
async function notifyFollowers(supabase:any,slug:string,title:string,contentType:string){const {data:members}=await supabase.from("ministry_memberships").select("user_id").eq("ministry_slug",slug);if(!members?.length)return;const name=slug==="hearth"?"The Hearth":slug==="foundry"?"The Foundry":"Men's Study";const rows=members.map((m:any)=>({user_id:m.user_id,type:"ministry_update",title:`New ${contentType} in ${name}`,body:title,link:`/ministries/${slug}`}));const {error}=await supabase.from("notifications").insert(rows);if(error)throw new Error(error.message);}

export async function createMinistryContent(formData:FormData){const ministry_slug=String(formData.get("ministry_slug")||"");const {supabase,user}=await requireManager(ministry_slug);const title=value(formData,"title");if(!title)return;const publish=formData.get("is_published")==="on";const contentType=String(formData.get("content_type")||"");const {error}=await supabase.from("ministry_content").insert({ministry_slug,content_type:contentType,title,summary:value(formData,"summary"),body:value(formData,"body"),link_url:value(formData,"link_url"),location:value(formData,"location"),starts_at:value(formData,"starts_at"),ends_at:value(formData,"ends_at"),action_label:value(formData,"action_label"),is_published:publish,is_featured:formData.get("is_featured")==="on",created_by:user.id});if(error)throw new Error(error.message);if(publish)await notifyFollowers(supabase,ministry_slug,title,contentType);refresh(ministry_slug);}
export async function updateMinistryContent(formData:FormData){const id=String(formData.get("id")||"");const ministry_slug=String(formData.get("ministry_slug")||"");const {supabase}=await requireManager(ministry_slug);const title=value(formData,"title");if(!id||!title)return;const {error}=await supabase.from("ministry_content").update({content_type:String(formData.get("content_type")||""),title,summary:value(formData,"summary"),body:value(formData,"body"),link_url:value(formData,"link_url"),location:value(formData,"location"),starts_at:value(formData,"starts_at"),ends_at:value(formData,"ends_at"),action_label:value(formData,"action_label"),is_featured:formData.get("is_featured")==="on",updated_at:new Date().toISOString()}).eq("id",id).eq("ministry_slug",ministry_slug);if(error)throw new Error(error.message);refresh(ministry_slug);}
export async function toggleMinistryContent(formData:FormData){const id=String(formData.get("id"));const ministry_slug=String(formData.get("ministry_slug"));const {supabase}=await requireManager(ministry_slug);const is_published=formData.get("is_published")==="true";const {data:item,error}=await supabase.from("ministry_content").update({is_published:!is_published,updated_at:new Date().toISOString()}).eq("id",id).eq("ministry_slug",ministry_slug).select("title,content_type").single();if(error)throw new Error(error.message);if(!is_published&&item)await notifyFollowers(supabase,ministry_slug,item.title,item.content_type);refresh(ministry_slug);}
export async function deleteMinistryContent(formData:FormData){const id=String(formData.get("id"));const ministry_slug=String(formData.get("ministry_slug"));const {supabase}=await requireManager(ministry_slug);const {error}=await supabase.from("ministry_content").delete().eq("id",id).eq("ministry_slug",ministry_slug);if(error)throw new Error(error.message);refresh(ministry_slug);}
export async function setMinistryLeader(formData:FormData){const {supabase}=await requireManager();const userId=String(formData.get("user_id")||"");const slug=String(formData.get("ministry_slug")||"");const makeLeader=formData.get("make_leader")==="true";if(!userId||!slug)return;const {error}=await supabase.from("ministry_memberships").upsert({user_id:userId,ministry_slug:slug,membership_role:makeLeader?"leader":"member"},{onConflict:"ministry_slug,user_id"});if(error)throw new Error(error.message);revalidatePath("/admin/ministries");}
