import { redirect } from "next/navigation";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { ministryPortals } from "@/lib/ministry-hub";
import { createMinistryContent, deleteMinistryContent, toggleMinistryContent, updateMinistryContent } from "./actions";
const Types=()=> <><option value="announcement">Announcement</option><option value="gathering">Gathering</option><option value="resource">Resource</option><option value="study">Study</option><option value="serve">Serve opportunity</option></>;
export default async function AdminMinistriesPage(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const {data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(profile?.role!=="admin")redirect("/dashboard");const {data:items}=await supabase.from("ministry_content").select("*").order("created_at",{ascending:false});return <main className="lfp-page pb-24"><div className="lfp-shell py-10"><Link href="/admin" className="text-sm font-black text-indigo-700">← Admin Center</Link><p className="lfp-eyebrow mt-6">Ministry CMS</p><h1 className="mt-2 text-4xl font-black">Manage the Ministry Hub</h1>
<section className="mt-8 grid gap-4 md:grid-cols-3">{ministryPortals.map(m=><Link key={m.slug} href={`/ministries/${m.slug}`} className="lfp-card p-5"><span className="text-2xl">{m.icon}</span><h2 className="mt-3 text-xl font-black">{m.title}</h2><p className="mt-1 text-sm text-slate-600">Preview member portal →</p></Link>)}</section>
<details open className="lfp-card mt-8 p-6"><summary className="cursor-pointer text-xl font-black">Add ministry content</summary><Editor action={createMinistryContent}/></details>
<section className="mt-8"><h2 className="text-2xl font-black">Content library</h2><div className="mt-4 space-y-3">{(items??[]).length===0?<div className="lfp-card p-6 text-slate-600">No ministry content yet.</div>:(items??[]).map((item:any)=><details key={item.id} className="lfp-card p-5"><summary className="cursor-pointer"><div className="inline-flex flex-wrap items-center gap-2"><span className="font-black">{item.title}</span><span className="rounded-full bg-indigo-50 px-2 py-1 text-xs font-black uppercase text-indigo-800">{item.ministry_slug}</span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-black uppercase">{item.content_type}</span></div></summary><Editor action={updateMinistryContent} item={item}/><div className="mt-4 flex gap-2"><form action={toggleMinistryContent}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="ministry_slug" value={item.ministry_slug}/><input type="hidden" name="is_published" value={String(item.is_published)}/><button className="rounded-xl border px-3 py-2 text-sm font-bold">{item.is_published?"Unpublish":"Publish"}</button></form><form action={deleteMinistryContent}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="ministry_slug" value={item.ministry_slug}/><button className="rounded-xl border border-red-200 px-3 py-2 text-sm font-bold text-red-700">Delete</button></form></div></details>)}</div></section></div></main>}
function Editor({action,item}:{action:(formData:FormData)=>Promise<void>,item?:any}){const dt=(v:any)=>v?new Date(v).toISOString().slice(0,16):"";return <form action={action} className="mt-6 grid gap-4 sm:grid-cols-2">{item&&<input type="hidden" name="id" value={item.id}/>}<label className="font-bold text-sm">Ministry<select name="ministry_slug" defaultValue={item?.ministry_slug} className="mt-1 w-full rounded-xl border p-3">{ministryPortals.map(m=><option key={m.slug} value={m.slug}>{m.title}</option>)}</select></label><label className="font-bold text-sm">Type<select name="content_type" defaultValue={item?.content_type} className="mt-1 w-full rounded-xl border p-3"><Types/></select></label><label className="font-bold text-sm sm:col-span-2">Title<input required name="title" defaultValue={item?.title||""} className="mt-1 w-full rounded-xl border p-3"/></label><label className="font-bold text-sm sm:col-span-2">Summary<textarea name="summary" defaultValue={item?.summary||""} rows={2} className="mt-1 w-full rounded-xl border p-3"/></label><label className="font-bold text-sm sm:col-span-2">Details<textarea name="body" defaultValue={item?.body||""} rows={4} className="mt-1 w-full rounded-xl border p-3"/></label><label className="font-bold text-sm">Link<input name="link_url" defaultValue={item?.link_url||""} className="mt-1 w-full rounded-xl border p-3"/></label><label className="font-bold text-sm">Button label<input name="action_label" defaultValue={item?.action_label||""} className="mt-1 w-full rounded-xl border p-3"/></label><label className="font-bold text-sm">Location<input name="location" defaultValue={item?.location||""} className="mt-1 w-full rounded-xl border p-3"/></label><label className="font-bold text-sm">Starts<input name="starts_at" type="datetime-local" defaultValue={dt(item?.starts_at)} className="mt-1 w-full rounded-xl border p-3"/></label><label className="font-bold text-sm">Ends<input name="ends_at" type="datetime-local" defaultValue={dt(item?.ends_at)} className="mt-1 w-full rounded-xl border p-3"/></label><label className="flex items-center gap-2 font-bold"><input name="is_featured" type="checkbox" defaultChecked={item?.is_featured}/> Feature</label>{!item&&<label className="flex items-center gap-2 font-bold"><input name="is_published" type="checkbox"/> Publish now</label>}<button className="lfp-button bg-slate-950 text-white sm:col-span-2">{item?"Save changes":"Add content"}</button></form>}
