export type ConnectionExercise={id:string;title:string;from:string;to:string;kind:"Explicit quotation"|"Explicit comparison"|"Author-developed argument"|"Narrative pattern";confidence:"Explicit"|"Strong textual pattern";question:string;choices:string[];correct:string;teaching:string;method:string};
export const connectionFoundations={
 title:"Connection Foundations",
 description:"Learn to trace how Scripture quotes, compares, develops, and echoes earlier Scripture without treating every resemblance as a hidden prediction.",
 exercises:[
 {id:"bronze-serpent",title:"When Jesus Makes the Connection",from:"Numbers 21:4–9",to:"John 3:14–15",kind:"Explicit comparison",confidence:"Explicit",question:"What earlier event does Jesus explicitly compare with the Son of Man being lifted up?",choices:["Moses lifting the bronze serpent","Moses receiving the tablets","Joshua crossing the Jordan","Elijah on Mount Carmel"],correct:"Moses lifting the bronze serpent",teaching:"This connection is unusually secure because Jesus states it: “as Moses lifted up the serpent… so must the Son of Man be lifted up.” The earlier story supplies the comparison; readers do not have to invent the link.",method:"Prefer connections the biblical author or speaker actually identifies. Start with the wording of the later passage, then return to the earlier passage and read it in full."},
 {id:"passover",title:"When an Author Names the Image",from:"Exodus 12",to:"1 Corinthians 5:6–8",kind:"Explicit comparison",confidence:"Explicit",question:"Which festival image does Paul explicitly apply to Christ in 1 Corinthians 5:7?",choices:["Passover","Purim","Booths","Dedication"],correct:"Passover",teaching:"Paul says, “Christ, our Passover lamb, has been sacrificed.” Exodus 12 therefore supplies real background for Paul's exhortation. The connection is textual, not merely a similarity noticed centuries later.",method:"When the New Testament names an Old Testament image, study both contexts. Ask which features the later author uses instead of assuming every detail of the earlier event maps onto Christ."},
 {id:"melchizedek",title:"Follow an Author's Whole Argument",from:"Genesis 14:17–20; Psalm 110:4",to:"Hebrews 5–7",kind:"Author-developed argument",confidence:"Explicit",question:"Hebrews develops Jesus' priesthood using which earlier biblical figure and psalmic promise?",choices:["Melchizedek and Psalm 110:4","Aaron and Psalm 23","Samuel and Psalm 1","Ezra and Psalm 119"],correct:"Melchizedek and Psalm 110:4",teaching:"Hebrews does more than mention Melchizedek. It brings Genesis 14 and Psalm 110 together in a sustained argument about Jesus' priesthood. The connection should be learned from Hebrews' reasoning, not from free association with the name.",method:"When a biblical author develops a connection across several chapters, follow the whole argument before summarizing the theology."},
 {id:"israel-son",title:"Recognize a Stated Fulfillment Pattern",from:"Hosea 11:1",to:"Matthew 2:13–15",kind:"Explicit quotation",confidence:"Explicit",question:"What earlier line does Matthew quote after Jesus returns from Egypt?",choices:["“Out of Egypt I called my son”","“The just shall live by faith”","“The LORD is my shepherd”","“A voice cries in the wilderness”"],correct:"“Out of Egypt I called my son”",teaching:"Hosea 11:1 looks backward to Israel's exodus: “When Israel was a child, I loved him, and out of Egypt I called my son.” Matthew knowingly applies that wording to Jesus. The connection shows Matthew presenting Jesus within Israel's story; it is not produced by pretending Hosea originally ignored Israel and spoke only about a future event.",method:"Read quoted Old Testament lines in their original paragraph. Then ask what the New Testament author is doing with that earlier text—quotation can involve pattern and fulfillment, not only one-to-one prediction."},
 {id:"wilderness-pattern",title:"Trace a Pattern Without Overclaiming",from:"Exodus 16–17; Deuteronomy 6–8",to:"Matthew 4:1–11",kind:"Narrative pattern",confidence:"Strong textual pattern",question:"What makes an Israel/wilderness connection in Matthew 4 stronger than a superficial resemblance?",choices:["Jesus answers wilderness tests with repeated quotations from Deuteronomy","Both stories contain sand","Later tradition says every detail matches","The word Israel appears in every verse"],correct:"Jesus answers wilderness tests with repeated quotations from Deuteronomy",teaching:"Matthew does not insert a label saying “Jesus is reenacting Israel,” but the surrounding son language, forty-day wilderness setting, and Jesus' repeated use of Deuteronomy 6–8 make the pattern textually strong. This is a responsible inference, not the same category as an explicit quotation explained by the author.",method:"Grade your confidence. Explicit quotations and comparisons deserve stronger language than patterns inferred from clusters of textual signals."}
 ] as ConnectionExercise[]
};