"use server";
import {revalidatePath} from "next/cache";import {redirect} from "next/navigation";import {createClient} from "@/lib/supabase/server";import {createAdminClient} from "@/lib/supabase/admin";import {canAccessFacilitatorCenter,hasMinistryRole,hasPlatformRole} from "@/lib/access-control";
async function ctx(){const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)redirect("/login");if(!(await canAccessFacilitatorCenter()))redirect("/dashboard");return{s,user,admin:createAdminClient()}}
async function mayUse(ministry:string){return await hasPlatformRole(["admin","owner"])||await hasMinistryRole(ministry,["facilitator","leader"])}
export async function createStudySession(fd:FormData){const{user,admin}=await ctx();const studyId=String(fd.get("study_id")||"");const ministry=String(fd.get("ministry_key")||"");if(!studyId||!ministry||!(await mayUse(ministry)))throw new Error("Not authorized for this ministry");const{error}=await admin.from("bible_study_sessions").insert({study_id:studyId,facilitator_id:user.id,ministry_key:ministry,status:"scheduled"});if(error)throw new Error(error.message);revalidatePath("/facilitator/studies")}
export async function startLiveSession(fd:FormData){const{s}=await ctx();const id=String(fd.get("session_id"));const{data:session}=await s.from("bible_study_sessions").select("ministry_key").eq("id",id).single();if(!session||!(await mayUse(session.ministry_key)))throw new Error("Not authorized");const admin=createAdminClient();const{error}=await admin.from("bible_study_sessions").update({status:"live",live_started_at:new Date().toISOString()}).eq("id",id);if(error)throw new Error(error.message);revalidatePath("/facilitator/studies")}
export async function endLiveSession(fd:FormData){const{s}=await ctx();const id=String(fd.get("session_id"));const{data:session}=await s.from("bible_study_sessions").select("ministry_key").eq("id",id).single();if(!session||!(await mayUse(session.ministry_key)))throw new Error("Not authorized");const admin=createAdminClient();const{error}=await admin.from("bible_study_sessions").update({live_ended_at:new Date().toISOString()}).eq("id",id);if(error)throw new Error(error.message);revalidatePath("/facilitator/studies")}
export async function startFollowUp(fd:FormData){const{s}=await ctx();const{error}=await s.rpc("start_bible_study_journey",{p_session_id:String(fd.get("session_id"))});if(error)throw new Error(error.message);revalidatePath("/facilitator/studies")}
export async function changeJourneyState(fd:FormData){const{s}=await ctx();const{error}=await s.rpc("set_bible_study_journey_state",{p_session_id:String(fd.get("session_id")),p_action:String(fd.get("action"))});if(error)throw new Error(error.message);revalidatePath("/facilitator/studies")}
