import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { completeJourneyDay } from "./actions";

export default async function StudyJourneyPage(){
 const supabase=await createClient(); const{data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/login");
 const {data:rows}=await supabase.from("bible_study_member_day_feed").select("*").eq("user_id",user.id).order("releases_at",{ascending:true});
 const now=Date.now(); const released=(rows??[]).filter((r:any)=>new Date(r.releases_at).getTime()<=now); const active=released.filter((r:any)=>!r.completed_at); const completed=released.filter((r:any)=>r.completed_at); const today=active.at(-1);
 return <main className="lfp-page pb-24"><section className="bg-slate-950 text-white"><div className="lfp-shell py-10 sm:py-14"><p className="text-xs font-black uppercase tracking-[.2em] text-amber-300">Your Bible Study Journey</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">Today</h1><p className="mt-3 max-w-2xl text-slate-300">One piece for today. No streaks. No catching up required. Meet God in the Scripture in front of you.</p></div></section><div className="lfp-shell py-8">
 {today?<article className="lfp-card mx-auto max-w-3xl overflow-hidden"><div className="border-b bg-amber-50 p-6"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs font-black uppercase tracking-[.16em] text-amber-800">Day {today.day_number} · {label(today.kind)}</p><span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-slate-600">{today.estimated_minutes} min</span></div><h2 className="mt-2 text-3xl font-black text-slate-950">{today.title}</h2></div><div className="space-y-6 p-6 sm:p-8">{today.scripture_refs?.length>0&&<Block title="Scripture"><p className="font-bold text-blue-800">{today.scripture_refs.join(" · ")}</p></Block>}{today.teaching&&<Block title="Teaching"><p>{today.teaching}</p></Block>}{today.story&&<Block title="Real Life"><p>{today.story}</p></Block>}{today.reflection_prompt&&<Block title="Reflect"><p>{today.reflection_prompt}</p></Block>}{today.challenge&&<Block title="Live It"><p>{today.challenge}</p></Block>}{today.prayer&&<Block title="Prayer"><p>{today.prayer}</p></Block>}<form action={completeJourneyDay}><input type="hidden" name="session_id" value={today.session_id}/><input type="hidden" name="journey_day_id" value={today.journey_day_id}/><button className="lfp-button w-full bg-slate-950 text-white">Mark Today Complete</button></form></div></article>:<div className="lfp-card mx-auto max-w-3xl p-8 text-center"><h2 className="text-2xl font-black">You’re current.</h2><p className="mt-2 text-slate-600">There is nothing you need to catch up on. Your next piece will appear here when it releases.</p></div>}
 <section className="mx-auto mt-10 grid max-w-5xl gap-5 lg:grid-cols-2"><div><p className="lfp-eyebrow">Active</p><h2 className="mt-1 text-2xl font-black">Available to revisit</h2><div className="mt-4 space-y-3">{active.filter((r:any)=>r.journey_day_id!==today?.journey_day_id).map((r:any)=><Mini key={`${r.session_id}-${r.journey_day_id}`} row={r}/>) }{active.length<=1&&<p className="text-sm text-slate-500">No additional active pieces.</p>}</div></div><div><p className="lfp-eyebrow">Completed</p><h2 className="mt-1 text-2xl font-black">Your completed pieces</h2><div className="mt-4 space-y-3">{completed.slice().reverse().map((r:any)=><Mini key={`${r.session_id}-${r.journey_day_id}`} row={r} done/>)}{completed.length===0&&<p className="text-sm text-slate-500">Completed pieces will collect here.</p>}</div></div></section>
 </div></main>;
}
function Block({title,children}:{title:string;children:React.ReactNode}){return <section><p className="text-xs font-black uppercase tracking-[.15em] text-blue-700">{title}</p><div className="mt-2 whitespace-pre-line leading-7 text-slate-700">{children}</div></section>}
function Mini({row,done=false}:{row:any;done?:boolean}){return <article className="lfp-card p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.13em] text-slate-500">Day {row.day_number} · {label(row.kind)}</p><h3 className="mt-1 font-black text-slate-950">{row.title}</h3></div>{done&&<span aria-label="Completed" className="text-emerald-700">✓</span>}</div></article>}
function label(kind:string){return ({dig_deeper:"Dig Deeper",live_it:"Live It",scripture_focus:"Scripture Focus",reflect:"Reflect",real_life:"Real Life",prayer:"Prayer",sabbath_reset:"Sabbath / Reset",go_deeper:"Go Deeper",prepare:"Prepare",bridge:"Bridge"} as Record<string,string>)[kind]??kind}
