"use client";

import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import { useRouter } from "next/navigation";

type Tool={type?:string;priority?:string;title?:string;prompt?:string;scripture?:string;choices?:string[];answer?:string;facilitator_note?:string};
type Slide={title?:string;body?:string;scripture?:string;discussion?:string;journal?:string;notes?:string;teaching_points?:string[];context?:string;word_insights?:string;cross_references?:string;theology?:string;transition?:string;prayer_points?:string[]|string;toolbox?:Tool[]};
type JoinData={configured:boolean;sessionId:string;roomUrl?:string;token?:string;title:string;subtitle?:string|null;slides:Slide[];facilitator:boolean;supervisor:boolean;message?:string};
type RoomMode="gather"|"teach"|"discuss";type DailyCall=any;type Panel="notes"|"tools"|"prayer"|null;

export default function LfLiveRoom({sessionId}:{sessionId:string}){
 const router=useRouter();const callRef=useRef<DailyCall>(null);const videoRefs=useRef(new Map<string,HTMLVideoElement>());const audioRefs=useRef(new Map<string,HTMLAudioElement>());
 const[loading,setLoading]=useState(true),[error,setError]=useState(""),[data,setData]=useState<JoinData|null>(null),[participants,setParticipants]=useState<any[]>([]),[mic,setMic]=useState(false),[cam,setCam]=useState(false),[slideIndex,setSlideIndex]=useState(0),[ending,setEnding]=useState(false),[mode,setMode]=useState<RoomMode>("gather"),[startedAt,setStartedAt]=useState(Date.now()),[elapsed,setElapsed]=useState(0),[panel,setPanel]=useState<Panel>("notes");const heartbeat=useRef<ReturnType<typeof setInterval>|null>(null);
 const slide=data?.slides?.[slideIndex]||{title:"Welcome to L&F Live",body:"The study will begin shortly."};
 const prayerPoints=useMemo(()=>Array.isArray(slide.prayer_points)?slide.prayer_points:(typeof slide.prayer_points==="string"?slide.prayer_points.split("\n").map(x=>x.trim()).filter(Boolean):[]),[slide.prayer_points]);
 const tools=Array.isArray(slide.toolbox)?slide.toolbox:[];
 const sendPresence=useCallback(async(event:string)=>{try{await fetch(`/api/live/session/${sessionId}/presence`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event}),keepalive:event==="left"})}catch{}},[sessionId]);
 const syncParticipants=useCallback(()=>{const call=callRef.current;if(!call)return;const rows=Object.values(call.participants?.()||{}) as any[];setParticipants(rows);const local=rows.find(p=>p.local);if(local){setMic(local.tracks?.audio?.state==="playable");setCam(local.tracks?.video?.state==="playable")}queueMicrotask(()=>{for(const p of rows){const vt=p.tracks?.video?.persistentTrack||p.videoTrack;const video=videoRefs.current.get(p.session_id);if(video&&vt){const current=(video.srcObject as MediaStream|null)?.getVideoTracks?.()[0];if(current?.id!==vt.id)video.srcObject=new MediaStream([vt]);video.muted=true;video.play().catch(()=>{});}const at=p.tracks?.audio?.persistentTrack||p.audioTrack;const audio=audioRefs.current.get(p.session_id);if(audio&&at&&!p.local){const current=(audio.srcObject as MediaStream|null)?.getAudioTracks?.()[0];if(current?.id!==at.id)audio.srcObject=new MediaStream([at]);audio.play().catch(()=>{});}}});},[]);
 useEffect(()=>{const id=setInterval(()=>setElapsed(Date.now()-startedAt),1000);return()=>clearInterval(id)},[startedAt]);
 useEffect(()=>{let alive=true;async function start(){try{const response=await fetch(`/api/live/session/${sessionId}`,{method:"POST"});const body=await response.json();if(!response.ok)throw new Error(body.error||"Unable to join L&F Live.");if(!alive)return;setData(body);if(!body.configured){setLoading(false);return;}const Daily=(await import("@daily-co/daily-js")).default;const call=Daily.createCallObject({subscribeToTracksAutomatically:true});callRef.current=call;call.on("participant-joined",syncParticipants).on("participant-updated",syncParticipants).on("participant-left",syncParticipants).on("joined-meeting",syncParticipants).on("app-message",(event:any)=>{const msg=event?.data;if(!msg||msg.type!=="lfp-live-state")return;if(Number.isInteger(msg.slideIndex))setSlideIndex(msg.slideIndex);if(["gather","teach","discuss"].includes(msg.mode))setMode(msg.mode);});await call.join({url:body.roomUrl,token:body.token,startAudioOff:true,startVideoOff:true});setMic(false);setCam(false);syncParticipants();await sendPresence("joined");setStartedAt(Date.now());try{const state=await fetch(`/api/live/session/${sessionId}/state`,{cache:"no-store"}).then(r=>r.ok?r.json():null);if(state){if(Number.isInteger(state.slideIndex))setSlideIndex(state.slideIndex);if(["gather","teach","discuss"].includes(state.mode))setMode(state.mode)}}catch{}heartbeat.current=setInterval(()=>sendPresence("heartbeat"),30000);setLoading(false);}catch(e){if(alive){setError(e instanceof Error?e.message:"Unable to join L&F Live. Check camera and microphone permissions, then try again.");setLoading(false);}}}start();return()=>{alive=false;if(heartbeat.current)clearInterval(heartbeat.current);sendPresence("left");const call=callRef.current;if(call){call.leave().catch(()=>{}).finally(()=>call.destroy())}callRef.current=null}},[sessionId,sendPresence,syncParticipants]);
 useEffect(()=>{if(!data?.configured||data.facilitator)return;let active=true;async function poll(){try{const r=await fetch(`/api/live/session/${sessionId}/state`,{cache:"no-store"});if(r.ok){const x=await r.json();if(active&&Number.isInteger(x.slideIndex))setSlideIndex(x.slideIndex);if(active&&["gather","teach","discuss"].includes(x.mode))setMode(x.mode)}}catch{}}const id=setInterval(poll,5000);return()=>{active=false;clearInterval(id)}},[data,sessionId]);
 useEffect(()=>{if(mode==="gather")setPanel(null);else if(mode==="teach")setPanel("notes");else setPanel(null)},[mode]);
 const time=useMemo(()=>{const s=Math.floor(elapsed/1000);return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`},[elapsed]);
 function broadcastState(nextSlide=slideIndex,nextMode=mode){try{callRef.current?.sendAppMessage?.({type:"lfp-live-state",slideIndex:nextSlide,mode:nextMode},"*")}catch{}void fetch(`/api/live/session/${sessionId}/state`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({slideIndex:nextSlide,mode:nextMode})}).catch(()=>{})}
 function setSlide(next:number){const max=Math.max(0,(data?.slides?.length||1)-1),value=Math.max(0,Math.min(max,next));setSlideIndex(value);if(data?.facilitator)broadcastState(value,mode)}
 function changeMode(next:RoomMode){setMode(next);if(data?.facilitator)broadcastState(slideIndex,next)}
 function toggleMic(){const next=!mic;setMic(next);void Promise.resolve(callRef.current?.setLocalAudio(next)).catch(()=>setMic(!next))}function toggleCam(){const next=!cam;setCam(next);void Promise.resolve(callRef.current?.setLocalVideo(next)).catch(()=>setCam(!next))}
 async function leave(){await sendPresence("left");await callRef.current?.leave();router.push("/dashboard")}async function end(){if(!confirm("End L&F Live for this session?"))return;setEnding(true);try{await fetch(`/api/live/session/${sessionId}/end`,{method:"POST"});await callRef.current?.leave();router.push("/dashboard")}finally{setEnding(false)}}
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-[#07111f] text-white"><p className="font-black">Opening L&F Live...</p></div>;if(error)return <div className="flex min-h-screen items-center justify-center bg-[#07111f] p-6 text-white"><div className="max-w-lg rounded-3xl border border-rose-400/30 bg-white/10 p-7"><h1 className="text-2xl font-black">L&F Live could not open</h1><p className="mt-3 text-slate-300">{error}</p></div></div>;if(data&&!data.configured)return <div className="flex min-h-screen items-center justify-center bg-[#07111f] p-6 text-white"><div className="max-w-2xl rounded-[2rem] border border-amber-300/30 bg-white/10 p-8"><p className="text-xs font-black uppercase tracking-[.2em] text-amber-300">L&F Live</p><h1 className="mt-3 text-3xl font-black">Video transport is not configured.</h1><p className="mt-4 text-slate-300">{data.message}</p></div></div>;
 return <div className="min-h-screen bg-[#07111f] text-white"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-[#c8a96b]/25 bg-[#091625] px-4 py-3"><div><p className="text-[10px] font-black uppercase tracking-[.24em] text-[#d9bd7d]">The Lost & Found Project · L&F Live</p><h1 className="mt-1 font-serif text-lg font-bold">{data?.title}</h1></div><div className="flex items-center gap-2"><span className="rounded-full border border-rose-400/25 bg-rose-500/10 px-3 py-1 text-xs font-black text-rose-300">● LIVE</span><span className="font-mono text-sm text-slate-300">{time}</span><button onClick={leave} className="rounded-xl border border-white/15 px-3 py-2 text-sm font-black">Leave</button>{data?.facilitator&&<button disabled={ending} onClick={end} className="rounded-xl bg-rose-700 px-3 py-2 text-sm font-black">{ending?"Ending...":"End Study"}</button>}</div></header>
 <main className="p-3">{mode==="gather"&&<GatherLayout participants={participants} videoRefs={videoRefs} audioRefs={audioRefs}/>} {mode==="teach"&&<TeachLayout data={data} slide={slide} participants={participants} videoRefs={videoRefs} audioRefs={audioRefs} facilitator={Boolean(data?.facilitator)} panel={panel} setPanel={setPanel} tools={tools} prayerPoints={prayerPoints}/>} {mode==="discuss"&&<DiscussLayout data={data} slide={slide} participants={participants} videoRefs={videoRefs} audioRefs={audioRefs} facilitator={Boolean(data?.facilitator)} panel={panel} setPanel={setPanel} tools={tools} prayerPoints={prayerPoints}/>}</main>
 <footer className="sticky bottom-0 z-20 border-t border-[#c8a96b]/20 bg-[#07111f]/95 p-3 backdrop-blur"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-2"><button onClick={toggleMic} className={`rounded-full px-4 py-3 text-sm font-black ${mic?"bg-white/10":"bg-rose-700"}`}>{mic?"Mic on":"Mic off"}</button><button onClick={toggleCam} className={`rounded-full px-4 py-3 text-sm font-black ${cam?"bg-white/10":"bg-rose-700"}`}>{cam?"Camera on":"Camera off"}</button><span className="rounded-full bg-white/5 px-4 py-3 text-sm font-black">{participants.length} in room</span>{data?.facilitator&&<><div className="mx-1 hidden h-7 w-px bg-white/10 sm:block"/><ModeButton active={mode==="gather"} onClick={()=>changeMode("gather")}>Gather</ModeButton><ModeButton active={mode==="teach"} onClick={()=>changeMode("teach")}>Teach</ModeButton><ModeButton active={mode==="discuss"} onClick={()=>changeMode("discuss")}>Discuss</ModeButton>{mode!=="gather"&&<><PanelButton active={panel==="notes"} onClick={()=>setPanel(panel==="notes"?null:"notes")}>Notes</PanelButton><PanelButton active={panel==="tools"} onClick={()=>setPanel(panel==="tools"?null:"tools")}>Tools{tools.length?` · ${tools.length}`:""}</PanelButton><PanelButton active={panel==="prayer"} onClick={()=>setPanel(panel==="prayer"?null:"prayer")}>Prayer{prayerPoints.length?` · ${prayerPoints.length}`:""}</PanelButton></>}</>}</div>{data?.facilitator&&mode!=="gather"&&<div className="mx-auto mt-2 flex max-w-xl items-center justify-between gap-3 rounded-full bg-white/5 px-3 py-1"><button disabled={slideIndex===0} onClick={()=>setSlide(slideIndex-1)} className="px-3 py-2 font-black disabled:opacity-30">← Previous</button><span className="text-xs font-black text-slate-300">{slideIndex+1} / {data.slides.length||1}</span><button disabled={slideIndex>=data.slides.length-1} onClick={()=>setSlide(slideIndex+1)} className="px-3 py-2 font-black disabled:opacity-30">Next →</button></div>}</footer></div>;
}

function GatherLayout({participants,videoRefs,audioRefs}:{participants:any[];videoRefs:any;audioRefs:any}){return <section className="mx-auto grid max-w-7xl gap-3 sm:grid-cols-2 lg:grid-cols-3">{participants.map((p:any)=><VideoTile key={p.session_id} p={p} videoRefs={videoRefs} audioRefs={audioRefs}/>)}</section>}
function TeachLayout({data,slide,participants,videoRefs,audioRefs,facilitator,panel,setPanel,tools,prayerPoints}:{data:JoinData|null;slide:Slide;participants:any[];videoRefs:any;audioRefs:any;facilitator:boolean;panel:Panel;setPanel:(p:Panel)=>void;tools:Tool[];prayerPoints:string[]}){return <div className={`mx-auto grid max-w-7xl gap-3 ${facilitator&&panel?"xl:grid-cols-[minmax(0,1fr)_23rem]":""}`}><div className="min-w-0"><section className="mb-3 grid grid-cols-3 gap-2 md:grid-cols-5 lg:grid-cols-7">{participants.map((p:any)=><VideoTile compact key={p.session_id} p={p} videoRefs={videoRefs} audioRefs={audioRefs}/>)}</section><StudyCard data={data} slide={slide}/></div>{facilitator&&panel&&<FacilitatorPanel panel={panel} slide={slide} tools={tools} prayerPoints={prayerPoints} onClose={()=>setPanel(null)}/>}</div>}
function DiscussLayout({data,slide,participants,videoRefs,audioRefs,facilitator,panel,setPanel,tools,prayerPoints}:{data:JoinData|null;slide:Slide;participants:any[];videoRefs:any;audioRefs:any;facilitator:boolean;panel:Panel;setPanel:(p:Panel)=>void;tools:Tool[];prayerPoints:string[]}){return <div className={`mx-auto grid max-w-7xl gap-3 ${facilitator&&panel?"xl:grid-cols-[minmax(0,1fr)_23rem]":""}`}><div className="min-w-0"><section className="mb-3 rounded-2xl border border-[#c8a96b]/25 bg-[#f7f2e8] p-4 text-[#142033]"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#9b742e]">Discuss Together</p><p className="mt-2 font-serif text-xl font-bold sm:text-2xl">{slide.discussion||slide.title||"Talk through what stood out and why it matters."}</p>{slide.scripture&&<p className="mt-2 text-sm font-bold text-[#76551e]">{slide.scripture}</p>}</section><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{participants.map((p:any)=><VideoTile key={p.session_id} p={p} videoRefs={videoRefs} audioRefs={audioRefs}/>)}</section></div>{facilitator&&panel&&<FacilitatorPanel panel={panel} slide={slide} tools={tools} prayerPoints={prayerPoints} onClose={()=>setPanel(null)}/>}</div>}
function StudyCard({data,slide}:{data:JoinData|null;slide:Slide}){return <section className="flex min-h-[50vh] items-center justify-center rounded-[1.75rem] border border-[#c8a96b]/25 bg-[#f7f2e8] p-5 text-[#142033] shadow-2xl sm:p-8"><article className="w-full max-w-5xl"><p className="text-xs font-black uppercase tracking-[.2em] text-[#9b742e]">{data?.subtitle||"Bible Study"}</p><h2 className="mt-4 font-serif text-3xl font-bold sm:text-5xl">{slide.title}</h2>{slide.scripture&&<p className="mt-5 border-l-2 border-[#c8a96b] pl-4 font-serif text-lg font-bold text-[#76551e] sm:text-xl">{slide.scripture}</p>}{slide.body&&<p className="mt-5 whitespace-pre-line text-lg leading-8 text-slate-700 sm:text-xl">{slide.body}</p>}{slide.discussion&&<div className="mt-6 rounded-2xl border border-[#c8a96b]/35 bg-white/70 p-5"><p className="text-xs font-black uppercase tracking-widest text-[#9b742e]">Discussion ahead</p><p className="mt-2 font-serif text-xl font-bold">{slide.discussion}</p></div>}{slide.journal&&<div className="mt-3 rounded-2xl bg-[#efe3c7] p-4"><p className="text-xs font-black uppercase tracking-widest text-[#76551e]">Journal</p><p className="mt-2 font-bold">{slide.journal}</p></div>}</article></section>}
function FacilitatorPanel({panel,slide,tools,prayerPoints,onClose}:{panel:Exclude<Panel,null>;slide:Slide;tools:Tool[];prayerPoints:string[];onClose:()=>void}){return <aside className="rounded-2xl border border-[#c8a96b]/25 bg-[#0c1b2c] p-5 xl:sticky xl:top-3 xl:max-h-[calc(100vh-8rem)] xl:overflow-y-auto"><div className="flex items-center justify-between"><p className="text-xs font-black uppercase tracking-widest text-[#d9bd7d]">Private Facilitator</p><button onClick={onClose} className="text-xs text-slate-400">Hide</button></div>{panel==="notes"&&<NotesPanel slide={slide}/>} {panel==="tools"&&<ToolsPanel tools={tools}/>} {panel==="prayer"&&<PrayerPanel points={prayerPoints}/>}</aside>}
function NotesPanel({slide}:{slide:Slide}){return <div><h3 className="mt-5 font-serif text-xl font-bold">Teaching Notes</h3>{slide.notes?<p className="mt-3 whitespace-pre-line text-sm leading-6 text-slate-200">{slide.notes}</p>:<p className="mt-3 rounded-xl bg-white/5 p-3 text-sm text-slate-400">No notes authored for this section.</p>}{slide.context&&<NoteBlock title="Context" text={slide.context}/>} {slide.word_insights&&<NoteBlock title="Word Insight" text={slide.word_insights}/>} {slide.cross_references&&<NoteBlock title="Cross-References" text={slide.cross_references}/>} {slide.theology&&<NoteBlock title="Biblical / Theological Background" text={slide.theology}/>} {slide.transition&&<NoteBlock title="Transition" text={slide.transition}/>}</div>}
function ToolsPanel({tools}:{tools:Tool[]}){return <div><h3 className="mt-5 font-serif text-xl font-bold">Session Toolbox</h3><p className="mt-2 text-xs leading-5 text-slate-400">Optional by design. Use only what helps the room.</p><div className="mt-4 space-y-3">{tools.length?tools.map((t,i)=><div key={i} className="rounded-xl border border-white/10 bg-white/5 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm">{t.title||`Tool ${i+1}`}</strong><span className="rounded-full bg-white/10 px-2 py-1 text-[10px] font-black uppercase">{String(t.priority||"helpful").replaceAll("_"," ")}</span></div>{t.prompt&&<p className="mt-2 text-sm leading-6 text-slate-200">{t.prompt}</p>}{t.scripture&&<p className="mt-2 text-xs font-bold text-[#d9bd7d]">{t.scripture}</p>}{Array.isArray(t.choices)&&t.choices.length>0&&<ul className="mt-2 space-y-1 text-xs text-slate-300">{t.choices.map((c,j)=><li key={j}>• {c}</li>)}</ul>}{t.answer&&<details className="mt-3 text-xs"><summary className="cursor-pointer font-black text-slate-300">Teaching key</summary><p className="mt-2 leading-5 text-slate-300">{t.answer}</p></details>}{t.facilitator_note&&<p className="mt-2 text-xs italic text-slate-400">{t.facilitator_note}</p>}</div>):<p className="rounded-xl bg-white/5 p-3 text-sm text-slate-400">No optional tools for this section.</p>}</div></div>}
function PrayerPanel({points}:{points:string[]}){return <div><h3 className="mt-5 font-serif text-xl font-bold">Prayer Points</h3><p className="mt-2 text-xs leading-5 text-slate-400">Invite members to pray first. Use these only as helpful prompts if needed.</p>{points.length?<ul className="mt-4 space-y-3">{points.map((p,i)=><li key={i} className="rounded-xl bg-white/5 p-3 text-sm leading-6 text-slate-200">• {p}</li>)}</ul>:<p className="mt-4 rounded-xl bg-white/5 p-3 text-sm text-slate-400">No prayer points authored for this section.</p>}</div>}
function VideoTile({p,compact=false,videoRefs,audioRefs}:{p:any;compact?:boolean;videoRefs:any;audioRefs:any}){const name=p.user_name||p.user_id||"L&F member";const videoOn=p.tracks?.video?.state==="playable";const audioOn=p.tracks?.audio?.state==="playable";return <article className={`relative overflow-hidden border border-white/10 bg-[#0c1b2c] ${compact?"aspect-video rounded-xl":"aspect-video rounded-2xl"}`}><video ref={el=>{if(el)videoRefs.current.set(p.session_id,el);else videoRefs.current.delete(p.session_id)}} autoPlay playsInline muted className="h-full w-full object-cover"/><audio ref={el=>{if(el)audioRefs.current.set(p.session_id,el);else audioRefs.current.delete(p.session_id)}} autoPlay/>{!videoOn&&<div className="absolute inset-0 flex items-center justify-center font-serif text-3xl font-bold text-[#d9bd7d]">{String(name).charAt(0).toUpperCase()}</div>}<div className={`absolute inset-x-0 bottom-0 flex items-center justify-between bg-gradient-to-t from-black/90 to-transparent ${compact?"p-2 text-[10px]":"p-3 text-sm"}`}><span className="truncate font-black">{name}{p.local?" · You":""}</span><span className={audioOn?"text-emerald-300":"text-rose-300"}>{audioOn?"●":"×"}</span></div></article>}
function ModeButton({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} className={`rounded-full px-4 py-3 text-sm font-black ${active?"bg-[#d9bd7d] text-[#07111f]":"bg-white/10"}`}>{children}</button>}
function PanelButton({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} className={`rounded-full border px-4 py-3 text-sm font-black ${active?"border-[#d9bd7d] bg-[#d9bd7d]/10 text-[#f0d79e]":"border-white/10 bg-white/5 text-slate-200"}`}>{children}</button>}
function NoteBlock({title,text}:{title:string;text:string}){return <div className="mt-5 rounded-xl bg-white/5 p-3"><p className="text-xs font-black uppercase tracking-widest text-[#d9bd7d]">{title}</p><p className="mt-2 whitespace-pre-line text-sm leading-6 text-slate-200">{text}</p></div>}
