"use client";

import { useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Verse={id:string;reference:string;verse_text:string;translation:string;topic:string|null;difficulty:string;mastery?:number};
export default function MemoryVerseClient({userId,verses}:{userId:string;verses:Verse[]}){
 const [index,setIndex]=useState(0); const [stage,setStage]=useState<"read"|"fill"|"recall">("read"); const [answer,setAnswer]=useState(""); const [feedback,setFeedback]=useState(""); const verse=verses[index];
 const words=useMemo(()=>verse?verse.verse_text.split(/\s+/):[],[verse]); const hiddenIndexes=useMemo(()=>new Set(words.map((_,i)=>i).filter((_,i)=>i%4===2)),[words]);
 if(!verse)return <div className="lfp-card p-6"><p className="text-slate-600">No memory verses are active yet.</p></div>;
 async function record(success:boolean){
  const supabase=createClient(); const current=verse.mastery??0; const mastery=Math.max(0,Math.min(5,current+(success?1:-1))); const nextDays=[0,1,2,4,7,14][mastery]??14; const next=new Date(Date.now()+nextDays*86400000).toISOString();
  await supabase.from("memory_verse_progress").upsert({user_id:userId,verse_id:verse.id,mastery,next_review_at:next,last_reviewed_at:new Date().toISOString(),correct_streak:success?1:0});
 }
 async function checkRecall(){const norm=(s:string)=>s.toLowerCase().replace(/[^a-z0-9 ]/g,"").replace(/\s+/g," ").trim(); const target=norm(verse.verse_text); const typed=norm(answer); const success=typed.length>0&&(typed===target||target.includes(typed)&&typed.length>target.length*.8); setFeedback(success?"Strong recall — keep building it.":"Review it once more, then try again."); await record(success)}
 function next(){setIndex((index+1)%verses.length);setStage("read");setAnswer("");setFeedback("")}
 return <div className="grid gap-5 lg:grid-cols-[1fr_.32fr]"><section className="lfp-card p-6 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="lfp-eyebrow">{verse.topic||"Memory Verse"}</p><h2 className="mt-2 text-3xl font-black text-slate-950">{verse.reference}</h2></div><span className="rounded-full bg-blue-50 px-3 py-2 text-xs font-black capitalize text-blue-700">{verse.difficulty}</span></div>{stage==="read"&&<><p className="mt-7 text-2xl font-bold leading-10 text-slate-800">“{verse.verse_text}”</p><p className="mt-3 text-sm font-bold text-slate-400">{verse.translation}</p><button onClick={()=>setStage("fill")} className="lfp-button lfp-button-primary mt-7">Hide some words →</button></>}{stage==="fill"&&<><p className="mt-7 text-2xl font-bold leading-10 text-slate-800">{words.map((w,i)=><span key={i}>{hiddenIndexes.has(i)?<span className="mx-1 inline-block min-w-16 border-b-2 border-blue-300 text-transparent">{w}</span>:w}{" "}</span>)}</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={()=>setStage("recall")} className="lfp-button lfp-button-primary">Try from memory →</button><button onClick={()=>setStage("read")} className="lfp-button lfp-button-secondary">Show verse</button></div></>}{stage==="recall"&&<><label className="mt-7 block"><span className="text-sm font-black text-slate-700">Type as much of the verse as you can remember</span><textarea value={answer} onChange={e=>setAnswer(e.target.value)} rows={6} className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 outline-none focus:border-blue-400"/></label><div className="mt-4 flex flex-wrap gap-3"><button onClick={checkRecall} className="lfp-button lfp-button-primary">Check recall</button><button onClick={()=>setStage("read")} className="lfp-button lfp-button-secondary">Review verse</button></div>{feedback&&<p className="mt-4 rounded-2xl bg-blue-50 p-4 font-bold text-blue-800">{feedback}</p>}</>}</section><aside className="space-y-4"><div className="lfp-card p-5"><p className="lfp-eyebrow">Learning pattern</p><ol className="mt-4 space-y-3 text-sm font-bold text-slate-700"><li>1. Read it in context.</li><li>2. Fill missing words.</li><li>3. Recall it unaided.</li><li>4. Return later for spaced review.</li></ol></div><button onClick={next} className="lfp-button lfp-button-secondary w-full">Next verse →</button></aside></div>
}
