"use client";

import { useEffect, useState } from "react";

function urlBase64ToUint8Array(base64String: string) {const padding="=".repeat((4-(base64String.length%4))%4);const base64=(base64String+padding).replace(/-/g,"+").replace(/_/g,"/");const rawData=window.atob(base64);const outputArray=new Uint8Array(rawData.length);for(let i=0;i<rawData.length;i++)outputArray[i]=rawData.charCodeAt(i);return outputArray;}
type SupportState="checking"|"unsupported"|"supported";
export default function PushNotificationToggle(){const[support,setSupport]=useState<SupportState>("checking"),[enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[testing,setTesting]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
useEffect(()=>{let active=true;async function checkStatus(){const isSupported=typeof window!=="undefined"&&"serviceWorker" in navigator&&"PushManager" in window&&"Notification" in window;if(!isSupported){if(active)setSupport("unsupported");return}try{const registration=await navigator.serviceWorker.getRegistration(),existing=await registration?.pushManager.getSubscription();if(active){setSupport("supported");setEnabled(Boolean(existing)&&Notification.permission==="granted")}}catch{if(active)setSupport("supported")}}checkStatus();return()=>{active=false}},[]);
async function handleEnable(){setError("");setMessage("");setBusy(true);try{const publicKey=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;if(!publicKey)throw new Error("Push notifications aren't configured yet.");const permission=await Notification.requestPermission();if(permission!=="granted")throw new Error("Notification permission was not granted.");const registration=await navigator.serviceWorker.register("/sw.js");await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription();if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(publicKey)});const json=subscription.toJSON();const res=await fetch("/api/push/subscribe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({endpoint:json.endpoint,keys:json.keys})});if(!res.ok)throw new Error("Failed to save subscription");setEnabled(true);setMessage("Push notifications are enabled on this device.")}catch(err){setError(err instanceof Error?err.message:"Something went wrong turning on push notifications.")}finally{setBusy(false)}}
async function handleTest(){setError("");setMessage("");setTesting(true);try{const res=await fetch("/api/push/test",{method:"POST",credentials:"same-origin"});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||"Failed to send test notification");setMessage("Test notification sent.")}catch(err){setError(err instanceof Error?err.message:"Failed to send test notification")}finally{setTesting(false)}}
async function handleDisable(){setError("");setMessage("");setBusy(true);try{const registration=await navigator.serviceWorker.getRegistration(),subscription=await registration?.pushManager.getSubscription();if(subscription){await fetch("/api/push/unsubscribe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({endpoint:subscription.endpoint})});await subscription.unsubscribe()}setEnabled(false);setMessage("Push notifications are off on this device.")}catch{setError("Something went wrong turning off push notifications.")}finally{setBusy(false)}}
if(support==="unsupported")return null;return <div className="px-6 py-5"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-medium text-gray-900">Push notifications</p><p className="mt-1 text-sm text-gray-500">Get a notification on this device even when the app isn&apos;t open. On iPhone, add the app to your Home Screen first for this to work.</p></div><button type="button" role="switch" aria-label="Push notifications" aria-checked={enabled} disabled={busy||testing||support==="checking"} onClick={()=>enabled?handleDisable():handleEnable()} className="relative -my-2 h-11 w-11 shrink-0 disabled:opacity-60"><span className={`absolute inset-x-0 top-2.5 h-6 rounded-full transition ${enabled?"bg-gradient-to-r from-indigo-600 to-violet-600":"bg-gray-200"}`}><span className={`absolute top-0.5 h-5 w-5 rounded-full bg-white shadow transition ${enabled?"left-5":"left-0.5"}`}/></span></button></div>{enabled&&<button type="button" onClick={handleTest} disabled={busy||testing} className="mt-4 min-h-11 rounded-xl border border-indigo-200 bg-indigo-50 px-4 py-2.5 text-sm font-semibold text-indigo-700 disabled:opacity-60">{testing?"Sending…":"Send Test Notification"}</button>}{error&&<p role="alert" aria-live="polite" className="mt-2 text-sm text-red-600">{error}</p>}{message&&<p role="status" aria-live="polite" className="mt-2 text-sm text-gray-600">{message}</p>}</div>}
