"use client";
import {useState} from "react";

type Slide={title?:string;body?:string;scripture?:string;discussion?:string;journal?:string;notes?:string};
export default function StudyViewer({slides,meetingUrl,downloadUrl}:{slides:Slide[];meetingUrl?:string|null;downloadUrl?:string|null}){const [index,setIndex]=useState(0);const [zoom,setZoom]=useState(100);const [presenter,setPresenter]=useState(false);const slide=slides[index]||{title:"Study materials are being prepared.",body:"Check back soon."};return <div className="grid gap-5 lg:grid-cols-[1fr_18rem]">
 <section className="overflow-hidden rounded-3xl bg-slate-950 text-white shadow-xl"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-white/10 px-4 py-3"><div className="flex gap-2"><button onClick={()=>setZoom(Math.max(75,zoom-10))} className="rounded-lg bg-white/10 px-3 py-2 font-bold">−</button><span className="px-2 py-2 text-sm font-bold">{zoom}%</span><button onClick={()=>setZoom(Math.min(150,zoom+10))} className="rounded-lg bg-white/10 px-3 py-2 font-bold">+</button></div><button onClick={()=>setPresenter(!presenter)} className="rounded-lg bg-white/10 px-3 py-2 text-sm font-bold">{presenter?"Participant mode":"Presenter mode"}</button></div>
 <div className="flex min-h-[28rem] items-center justify-center overflow-auto p-6 sm:p-10"><article style={{fontSize:`${zoom}%`}} className="w-full max-w-4xl rounded-2xl bg-white p-7 text-slate-950 sm:p-12"><p className="text-xs font-black uppercase tracking-[.18em] text-indigo-700">The Lost and Found Project · Bible Study</p><h2 className="mt-4 text-3xl font-black sm:text-5xl">{slide.title}</h2>{slide.scripture&&<p className="mt-5 font-black text-indigo-700">{slide.scripture}</p>}{slide.body&&<p className="mt-5 whitespace-pre-line text-lg leading-8 text-slate-700">{slide.body}</p>}{slide.discussion&&<div className="mt-7 rounded-2xl bg-indigo-50 p-5"><p className="text-xs font-black uppercase tracking-widest text-indigo-700">Discuss</p><p className="mt-2 font-bold">{slide.discussion}</p></div>}{slide.journal&&<div className="mt-4 rounded-2xl bg-amber-50 p-5"><p className="text-xs font-black uppercase tracking-widest text-amber-800">Journal</p><p className="mt-2 font-bold">{slide.journal}</p></div>}{presenter&&slide.notes&&<div className="mt-4 border-t pt-4 text-sm text-slate-500"><strong>Presenter note:</strong> {slide.notes}</div>}</article></div>
 <div className="flex items-center justify-between border-t border-white/10 p-4"><button disabled={index===0} onClick={()=>setIndex(index-1)} className="rounded-xl bg-white/10 px-4 py-2 font-bold disabled:opacity-30">← Previous</button><span className="text-sm font-bold">{Math.min(index+1,slides.length||1)} / {slides.length||1}</span><button disabled={index>=slides.length-1} onClick={()=>setIndex(index+1)} className="rounded-xl bg-amber-300 px-4 py-2 font-black text-slate-950 disabled:opacity-30">Next →</button></div></section>
 <aside className="space-y-4"><div className="lfp-card p-5"><h3 className="font-black">Study tools</h3><div className="mt-4 grid gap-2">{meetingUrl&&<a href={meetingUrl} target="_blank" rel="noreferrer" className="lfp-button bg-indigo-700 text-center text-white">Join Live Study</a>}<a href="https://emmaus.lostandfoundproject.org" target="_blank" rel="noreferrer" className="rounded-xl border p-3 text-center font-black">Open Scripture in Emmaus</a>{downloadUrl&&<a href={downloadUrl} target="_blank" rel="noreferrer" className="rounded-xl border p-3 text-center font-black">Download Resources</a>}</div></div><div className="lfp-card p-5"><h3 className="font-black">Navigate</h3><div className="mt-3 grid max-h-80 gap-2 overflow-auto">{slides.map((s,i)=><button key={i} onClick={()=>setIndex(i)} className={`rounded-xl p-3 text-left text-sm font-bold ${i===index?"bg-indigo-700 text-white":"bg-slate-50"}`}>{i+1}. {s.title||"Study point"}</button>)}</div></div></aside>
 </div>}
