"use client";

import { FormEvent, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { createStudy } from "@/app/admin/studies/actions";

type Ministry={slug:string;title:string};
type Slide={title:string;scripture:string;body:string;discussion:string;journal:string;notes:string};
type Day={title:string;scripture:string;teaching:string;story:string;prompt:string};
const blankSlide=():Slide=>({title:"",scripture:"",body:"",discussion:"",journal:"",notes:""});
const blankDay=():Day=>({title:"",scripture:"",teaching:"",story:"",prompt:""});

export default function StudyBuilderForm({ministries}:{ministries:Ministry[]}){
 const router=useRouter();const formRef=useRef<HTMLFormElement>(null);const[slides,setSlides]=useState<Slide[]>([blankSlide()]);const[days,setDays]=useState<Day[]>([blankDay()]);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");const[error,setError]=useState("");
 const updateSlide=(i:number,k:keyof Slide,v:string)=>setSlides(a=>a.map((x,n)=>n===i?{...x,[k]:v}:x));
 const updateDay=(i:number,k:keyof Day,v:string)=>setDays(a=>a.map((x,n)=>n===i?{...x,[k]:v}:x));
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();e.stopPropagation();if(busy)return;setMsg("");setError("");const form=e.currentTarget;const fd=new FormData(form);const title=String(fd.get("title")||"").trim();if(!title){setError("Add a study title before saving.");form.querySelector<HTMLInputElement>('[name="title"]')?.focus();return;}setBusy(true);try{fd.set("slides",JSON.stringify(slides.filter(s=>s.title||s.scripture||s.body||s.discussion||s.journal||s.notes)));fd.set("devotional_cards",JSON.stringify(days.filter(d=>d.title||d.scripture||d.teaching||d.story||d.prompt)));const result=await createStudy(fd);if(!result?.ok)throw new Error(result?.message||"Unable to save this study.");setMsg(`Saved: ${result.title}`);formRef.current?.reset();setSlides([blankSlide()]);setDays([blankDay()]);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Unable to save this study.");}finally{setBusy(false)}}
 return <form ref={formRef} noValidate onSubmit={submit} className="lfp-card mt-6 grid gap-5 p-6 sm:grid-cols-2">
  <label className="text-sm font-bold">Title <span className="text-rose-700">Required</span><input name="title" required className="mt-1 w-full rounded-xl border p-3"/></label>
  <label className="text-sm font-bold">Subtitle<input name="subtitle" className="mt-1 w-full rounded-xl border p-3"/></label>
  <label className="text-sm font-bold">Ministry<select name="ministry_slug" className="mt-1 w-full rounded-xl border p-3"><option value="">L&F General</option>{ministries.map(m=><option key={m.slug} value={m.slug}>{m.title}</option>)}</select></label>
  <label className="text-sm font-bold">Scripture references, one per line<textarea name="scripture_refs" rows={3} className="mt-1 w-full rounded-xl border p-3"/></label>
  <label className="text-sm font-bold sm:col-span-2">Description<textarea name="description" rows={3} className="mt-1 w-full rounded-xl border p-3"/></label>
  <section className="sm:col-span-2"><div className="flex items-center justify-between"><h3 className="text-xl font-black">Teaching sections</h3><button type="button" onClick={()=>setSlides(s=>[...s,blankSlide()])} className="rounded-xl border px-3 py-2 text-sm font-black">+ Add section</button></div><div className="mt-4 grid gap-4">{slides.map((s,i)=><article key={i} className="rounded-2xl border bg-slate-50 p-4"><div className="flex justify-between"><strong>Section {i+1}</strong>{slides.length>1&&<button type="button" onClick={()=>setSlides(x=>x.filter((_,n)=>n!==i))} className="text-xs font-black text-rose-700">Remove</button>}</div><div className="mt-3 grid gap-3 sm:grid-cols-2"><input placeholder="Section title" value={s.title} onChange={e=>updateSlide(i,"title",e.target.value)} className="rounded-xl border p-3"/><input placeholder="Scripture" value={s.scripture} onChange={e=>updateSlide(i,"scripture",e.target.value)} className="rounded-xl border p-3"/><textarea placeholder="Teaching point / explanation" value={s.body} onChange={e=>updateSlide(i,"body",e.target.value)} rows={3} className="rounded-xl border p-3 sm:col-span-2"/><textarea placeholder="Discussion question" value={s.discussion} onChange={e=>updateSlide(i,"discussion",e.target.value)} rows={2} className="rounded-xl border p-3"/><textarea placeholder="Journaling prompt" value={s.journal} onChange={e=>updateSlide(i,"journal",e.target.value)} rows={2} className="rounded-xl border p-3"/><textarea placeholder="Facilitator notes / talking points" value={s.notes} onChange={e=>updateSlide(i,"notes",e.target.value)} rows={3} className="rounded-xl border p-3 sm:col-span-2"/></div></article>)}</div></section>
  <section className="sm:col-span-2"><div className="flex items-center justify-between"><h3 className="text-xl font-black">Daily Path</h3><button type="button" onClick={()=>setDays(d=>[...d,blankDay()])} className="rounded-xl border px-3 py-2 text-sm font-black">+ Add day</button></div><div className="mt-4 grid gap-4">{days.map((d,i)=><article key={i} className="rounded-2xl border bg-violet-50/40 p-4"><div className="flex justify-between"><strong>Day {i+1}</strong>{days.length>1&&<button type="button" onClick={()=>setDays(x=>x.filter((_,n)=>n!==i))} className="text-xs font-black text-rose-700">Remove</button>}</div><div className="mt-3 grid gap-3 sm:grid-cols-2"><input placeholder="Day title" value={d.title} onChange={e=>updateDay(i,"title",e.target.value)} className="rounded-xl border p-3"/><input placeholder="Scripture" value={d.scripture} onChange={e=>updateDay(i,"scripture",e.target.value)} className="rounded-xl border p-3"/><textarea placeholder="Teaching point" value={d.teaching} onChange={e=>updateDay(i,"teaching",e.target.value)} rows={3} className="rounded-xl border p-3 sm:col-span-2"/><textarea placeholder="Relatable story / scenario" value={d.story} onChange={e=>updateDay(i,"story",e.target.value)} rows={3} className="rounded-xl border p-3"/><textarea placeholder="Reflection or journaling prompt" value={d.prompt} onChange={e=>updateDay(i,"prompt",e.target.value)} rows={3} className="rounded-xl border p-3"/></div></article>)}</div></section>
  <label className="flex items-center gap-2 font-bold"><input type="checkbox" name="is_published"/> Publish now</label><div aria-live="polite">{error&&<p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-bold text-rose-800">! {error}</p>}{msg&&<p role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">✓ {msg}</p>}</div>
  <button type="submit" disabled={busy} className="lfp-button bg-slate-950 text-white sm:col-span-2 disabled:cursor-wait disabled:opacity-60">{busy?"Saving Bible Study…":"Save Bible Study"}</button>
 </form>;
}
