"use client";

import { useEffect, useRef, useState } from "react";

type Slide={title?:string;body?:string;scripture?:string;discussion?:string;journal?:string;notes?:string};

export default function StudyPresentation({title,subtitle,slides}:{title:string;subtitle?:string|null;slides:Slide[]}){
 const [index,setIndex]=useState(0);const [showNotes,setShowNotes]=useState(true);const root=useRef<HTMLDivElement>(null);const slide=slides[index]||{title:"Study materials are being prepared.",body:"Check back soon."};
 function previous(){setIndex(i=>Math.max(0,i-1))}function next(){setIndex(i=>Math.min(Math.max(slides.length-1,0),i+1))}
 useEffect(()=>{function key(e:KeyboardEvent){if(["ArrowRight","PageDown"," "].includes(e.key)){e.preventDefault();next()}if(["ArrowLeft","PageUp"].includes(e.key)){e.preventDefault();previous()}if(e.key.toLowerCase()==="n")setShowNotes(v=>!v);if(e.key.toLowerCase()==="f")root.current?.requestFullscreen?.()}window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[slides.length]);
 return <div ref={root} className="min-h-screen bg-slate-950 text-white"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 px-4 py-3"><div><p className="text-xs font-black uppercase tracking-[.18em] text-amber-300">The Lost & Found Project · Facilitator Presentation</p><p className="mt-1 font-black">{title}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setShowNotes(v=>!v)} className="rounded-xl bg-white/10 px-3 py-2 text-sm font-black">{showNotes?"Hide notes":"Show notes"}</button><button onClick={()=>root.current?.requestFullscreen?.()} className="rounded-xl bg-white/10 px-3 py-2 text-sm font-black">Full screen</button></div></header><main className={`grid min-h-[calc(100vh-8rem)] ${showNotes?"lg:grid-cols-[minmax(0,1fr)_22rem]":""}`}><section className="flex items-center justify-center p-4 sm:p-8"><article className="aspect-video w-full max-w-6xl overflow-auto rounded-2xl bg-white p-8 text-slate-950 shadow-2xl sm:p-14"><p className="text-xs font-black uppercase tracking-[.2em] text-indigo-700">{subtitle||"Bible Study"}</p><h1 className="mt-5 text-4xl font-black leading-tight sm:text-6xl">{slide.title}</h1>{slide.scripture&&<p className="mt-6 text-xl font-black text-indigo-700 sm:text-2xl">{slide.scripture}</p>}{slide.body&&<p className="mt-6 whitespace-pre-line text-xl leading-9 text-slate-700 sm:text-2xl">{slide.body}</p>}{slide.discussion&&<div className="mt-7 rounded-2xl bg-indigo-50 p-5"><p className="text-xs font-black uppercase tracking-widest text-indigo-700">Discuss</p><p className="mt-2 text-lg font-bold">{slide.discussion}</p></div>}{slide.journal&&<div className="mt-4 rounded-2xl bg-amber-50 p-5"><p className="text-xs font-black uppercase tracking-widest text-amber-800">Journal</p><p className="mt-2 text-lg font-bold">{slide.journal}</p></div>}</article></section>{showNotes&&<aside className="border-l border-white/10 bg-slate-900 p-5"><p className="text-xs font-black uppercase tracking-widest text-amber-300">Facilitator notes</p><div className="mt-4 whitespace-pre-line text-sm leading-6 text-slate-200">{slide.notes||"No presenter notes for this slide."}</div><p className="mt-8 text-xs leading-5 text-slate-400">Share only the slide tab/window in Google Meet if you want these notes to remain private. Keyboard: ←/→ slides · N notes · F full screen.</p></aside>}</main><footer className="sticky bottom-0 flex items-center justify-between border-t border-white/10 bg-slate-950/95 px-4 py-3 backdrop-blur"><button disabled={index===0} onClick={previous} className="rounded-xl bg-white/10 px-4 py-2 font-black disabled:opacity-30">← Previous</button><span className="text-sm font-black">{Math.min(index+1,slides.length||1)} / {slides.length||1}</span><button disabled={index>=slides.length-1} onClick={next} className="rounded-xl bg-amber-300 px-5 py-2 font-black text-slate-950 disabled:opacity-30">Next →</button></footer></div>
}
