export type LearningCollection={slug:string;title:string;description:string;target:number;level:"Beginner"|"Intermediate"|"All levels";lessons:{title:string;href:string;minutes:number;level:"Beginner"|"Intermediate";status:"available"|"planned"}[]};
export const learningCollections:LearningCollection[]=[
{slug:"jesus",title:"Life and Teachings of Jesus",description:"Follow the Gospels and practice reading Jesus' teaching in context.",target:12,level:"All levels",lessons:[{title:"Jesus: Gospel Foundations (Six Lessons)",href:"/learn/jesus",minutes:90,level:"Beginner",status:"available"}]},
{slug:"old-testament",title:"Understanding the Old Testament",description:"Learn the story, genres, covenant themes, and historical settings.",target:12,level:"All levels",lessons:[]},
{slug:"new-testament",title:"Understanding the New Testament",description:"Understand the Gospels, Acts, letters, and Revelation in their contexts.",target:12,level:"All levels",lessons:[{title:"New Testament Foundations (Ten Lessons)",href:"/learn/new-testament",minutes:150,level:"Beginner",status:"available"}]},
{slug:"language",title:"Hebrew and Greek in Context",description:"Learn meaningful biblical words without turning them into secret codes.",target:10,level:"Intermediate",lessons:[{title:"From Death to Life · Ephesians 2",href:"/learn/language/ephesians-2-1-10",minutes:15,level:"Intermediate",status:"available"},{title:"The Lord Is My Shepherd · Psalm 23",href:"/learn/language/psalm-23",minutes:15,level:"Intermediate",status:"available"}]},
{slug:"study-skills",title:"How to Study Scripture",description:"Practice genre, observation, context, interpretation, and application.",target:10,level:"Beginner",lessons:[{title:"Context Foundations",href:"/learn/context",minutes:12,level:"Beginner",status:"available"},{title:"Observation Foundations",href:"/learn/observation",minutes:15,level:"Beginner",status:"available"},{title:"Study Skills Foundations",href:"/learn/study-skills",minutes:20,level:"Beginner",status:"available"}]},
{slug:"people-places",title:"People, Places, and Timelines",description:"Learn who, where, and when—and why those details matter.",target:10,level:"Beginner",lessons:[{title:"Geography Foundations",href:"/learn/geography",minutes:12,level:"Beginner",status:"available"}]},
{slug:"connections",title:"Biblical Themes and Connections",description:"Trace explicit quotations, developed arguments, and careful patterns.",target:10,level:"Intermediate",lessons:[{title:"Connections Foundations",href:"/learn/connections",minutes:12,level:"Intermediate",status:"available"}]},
{slug:"everyday-life",title:"Faith in Everyday Life",description:"Read passages about relationships, choices, and discipleship in context.",target:10,level:"All levels",lessons:[]}
];
export const plannedLessonCount=learningCollections.reduce((n,c)=>n+c.target,0);
