import Link from "next/link";
import {createClient} from "@/lib/supabase/server";
import {MinistryImpactInvitation} from "@/components/MinistryImpactInvitation";

export default async function GivePage(){
 const supabase=await createClient();const{data}=await supabase.rpc("get_active_ministry_impact_areas",{p_ministry_slug:null});
 const hasImpact=(data??[]).some((i:any)=>i.show_on_giving);
 return <main className="lfp-page pb-24"><section className="relative overflow-hidden bg-[rgb(var(--lfp-ink))] text-white"><div className="lfp-shell py-12 sm:py-16"><p className="text-xs font-black uppercase tracking-[.2em] text-sky-300">Support The Lost &amp; Found Project</p><h1 className="mt-4 max-w-4xl text-4xl font-black tracking-[-.045em] sm:text-6xl">Help make room for more ministry.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">Giving is one way to participate in what God is doing through L&amp;F. We want the invitation to be clear and easy without placing money ahead of Scripture, salvation, prayer, or serving people.</p><p className="mt-5 max-w-3xl text-sm leading-7 text-slate-400">“Let each man give according as he has determined in his heart, not grudgingly or under compulsion, for God loves a cheerful giver.” — 2 Corinthians 9:7, WEB</p></div></section><div className="lfp-shell py-10"><section className="grid gap-4 md:grid-cols-4"><Way title="Pray">Pray for the people, ministries, leaders, and opportunities God places before L&amp;F.</Way><Way title="Serve">Give your time and abilities where the ministry has a place for you to help.</Way><Way title="Share">Help someone discover a study, ministry, prayer community, or resource that may serve them.</Way><Way title="Give">Financial support helps L&amp;F continue and expand the practical work behind the ministry.</Way></section>{hasImpact&&<MinistryImpactInvitation surface="giving" limit={4}/>}<section className="mt-12 rounded-[2rem] border border-slate-200 bg-white p-7 sm:p-9"><p className="lfp-eyebrow">Giving</p><h2 className="mt-2 text-3xl font-black">Give freely. No pressure. No minimum.</h2><p className="mt-3 max-w-3xl leading-7 text-slate-600">We are preparing the secure giving connection now. When it is connected, one-time and recurring support will be equally easy to choose, and L&amp;F will not store your card information.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/ministries" className="lfp-button lfp-button-secondary">Explore Ministries</Link><Link href="/prayer" className="lfp-button lfp-button-secondary">Pray With Us</Link></div></section></div></main>
}
function Way({title,children}:{title:string;children:React.ReactNode}){return <article className="lfp-card p-5"><h2 className="text-xl font-black">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{children}</p></article>}
