export type TriviaQuestion = {
  question: string;
  choices: string[];
  correct: string;
  ref: string;
  note: string;
};

export type TriviaCategory = {
  id: string;
  name: string;
  description: string;
  questions: TriviaQuestion[];
};

// The Lost and Found Project's "Bible Trivia Challenge" — originally a custom
// embed on the Hostinger marketing site. Moved in-app so it lives behind
// sign-in alongside the rest of the community content, matching the app's
// design system instead of the marketing site's separate widget styling.
// Each category has 10 fixed questions. Scores are saved per member in the
// quiz_attempts table so members can track their best score per category.
export const triviaCategories: TriviaCategory[] = [
  {
    id: "bible-basics",
    name: "Bible Basics",
    description: "Foundational people, places, and stories from Scripture.",
    questions: [
      {
        question: "What did God give Moses on Mount Sinai?",
        choices: ["The Ten Commandments", "A crown", "A sword", "A temple plan"],
        correct: "The Ten Commandments",
        ref: "Exodus 20:1-17",
        note: "The Ten Commandments reveal God's holy standard and teach His people how to live in covenant relationship with Him.",
      },
      {
        question: "Who was swallowed by a great fish?",
        choices: ["Elijah", "Jonah", "Paul", "Peter"],
        correct: "Jonah",
        ref: "Jonah 1:17",
        note: "Jonah ran from God's assignment, but God pursued him. His story shows both God's mercy toward sinners and His patience with reluctant servants.",
      },
      {
        question: "Who was Abraham's wife?",
        choices: ["Rebekah", "Rachel", "Sarah", "Leah"],
        correct: "Sarah",
        ref: "Genesis 17:15-16",
        note: "Sarah's story reminds us that God keeps His promises even when the timeline feels impossible from a human perspective.",
      },
      {
        question: "What is the first book of the Bible?",
        choices: ["Exodus", "Genesis", "Psalms", "Matthew"],
        correct: "Genesis",
        ref: "Genesis 1:1",
        note: "Genesis means beginnings. It introduces creation, humanity, sin, promise, and God's plan of redemption. The Bible begins with God, not with man.",
      },
      {
        question: "How many days did God take to create the heavens and the earth?",
        choices: ["5", "6", "7", "10"],
        correct: "6",
        ref: "Genesis 1:31; Genesis 2:2",
        note: "God created in six days and rested on the seventh. Creation shows His power, order, goodness, and authority over all things.",
      },
      {
        question: "Who built the ark?",
        choices: ["Moses", "Abraham", "Noah", "David"],
        correct: "Noah",
        ref: "Genesis 6:14",
        note: "God told Noah to build an ark because judgment was coming, but He also provided a way of rescue. Noah's obedience reminds us that faith is not just believing God exists; it is trusting Him enough to act.",
      },
      {
        question: "Who led the Israelites out of Egypt?",
        choices: ["Joshua", "Moses", "Aaron", "Caleb"],
        correct: "Moses",
        ref: "Exodus 3:10",
        note: "God used Moses to deliver Israel from slavery. This points to God's heart as Redeemer and foreshadows the greater deliverance found in Christ.",
      },
      {
        question: "Who was the first king of Israel?",
        choices: ["David", "Solomon", "Saul", "Samuel"],
        correct: "Saul",
        ref: "1 Samuel 10:1",
        note: "Saul was chosen as Israel's first king, but his story warns us that outward appearance cannot replace inward obedience.",
      },
      {
        question: "Who interpreted dreams in Egypt and later helped save many lives?",
        choices: ["Daniel", "Joseph", "Moses", "Aaron"],
        correct: "Joseph",
        ref: "Genesis 41:15-16",
        note: "Joseph gave glory to God for interpreting dreams. His life shows how God can use hardship, betrayal, and delay for a greater purpose.",
      },
      {
        question: "Who defeated Goliath?",
        choices: ["Saul", "David", "Jonathan", "Samson"],
        correct: "David",
        ref: "1 Samuel 17:45-47",
        note: "David faced Goliath with confidence in the Lord. Faith does not ignore the size of the battle; it focuses on the greatness of God.",
      },
    ],
  },
  {
    id: "jesus-and-the-gospels",
    name: "Jesus & the Gospels",
    description: "The life, ministry, and disciples of Jesus Christ.",
    questions: [
      {
        question: "Where did Jesus pray before His arrest?",
        choices: ["Eden", "Gethsemane", "Carmel", "Sinai"],
        correct: "Gethsemane",
        ref: "Matthew 26:36",
        note: "In Gethsemane, Jesus surrendered to the Father's will. His prayer teaches us to bring anguish honestly to God while choosing obedience.",
      },
      {
        question: "What did the angel say after Jesus rose from the dead?",
        choices: ["He is not here; He is risen", "Wait for Moses", "Go back to Egypt", "Build an altar"],
        correct: "He is not here; He is risen",
        ref: "Matthew 28:5-6",
        note: "The resurrection is the center of Christian hope. Jesus conquered sin and death, proving that His promises are true.",
      },
      {
        question: "Who baptized Jesus?",
        choices: ["Peter", "John the Baptist", "James", "Nicodemus"],
        correct: "John the Baptist",
        ref: "Matthew 3:13-17",
        note: "Jesus' baptism publicly revealed His obedience, the Father's pleasure, and the presence of the Holy Spirit.",
      },
      {
        question: "What did Jesus feed to the 5,000?",
        choices: ["Manna and quail", "Bread and fish", "Grapes and figs", "Lentils and bread"],
        correct: "Bread and fish",
        ref: "Matthew 14:17-21",
        note: "Jesus multiplied what seemed insufficient. When surrendered to Him, small things can become more than enough.",
      },
      {
        question: "How many apostles did Jesus choose?",
        choices: ["10", "11", "12", "13"],
        correct: "12",
        ref: "Luke 6:13",
        note: "Jesus chose twelve apostles to walk with Him, learn from Him, and later carry the gospel forward. Discipleship is learned through relationship and obedience.",
      },
      {
        question: "Who climbed a tree to see Jesus?",
        choices: ["Bartimaeus", "Zacchaeus", "Nicodemus", "Lazarus"],
        correct: "Zacchaeus",
        ref: "Luke 19:1-10",
        note: "Zacchaeus was changed by encountering Jesus. Salvation did not merely give him information; it transformed his priorities and actions.",
      },
      {
        question: "What miracle did Jesus perform at a wedding in Cana?",
        choices: ["He healed a blind man", "He walked on water", "He turned water into wine", "He raised Lazarus"],
        correct: "He turned water into wine",
        ref: "John 2:1-11",
        note: "This first sign revealed Jesus' glory. It also shows that Jesus cares about real-life moments, family events, and human need.",
      },
      {
        question: "Who betrayed Jesus?",
        choices: ["Peter", "John", "Judas Iscariot", "Thomas"],
        correct: "Judas Iscariot",
        ref: "Matthew 26:14-16",
        note: "Judas' betrayal is sobering because proximity to Jesus is not the same as surrender to Jesus. The heart must belong to Him.",
      },
      {
        question: "Which disciple is often called doubting Thomas?",
        choices: ["Andrew", "Thomas", "Philip", "Matthew"],
        correct: "Thomas",
        ref: "John 20:24-29",
        note: "Thomas struggled to believe, but Jesus met him with grace and truth. Honest doubt should lead us toward Christ, not away from Him.",
      },
      {
        question: "Who denied Jesus three times?",
        choices: ["James", "John", "Peter", "Andrew"],
        correct: "Peter",
        ref: "Luke 22:61-62",
        note: "Peter's failure was painful, but it was not final. Jesus later restored him, showing that repentance can lead to renewed purpose.",
      },
    ],
  },
  {
    id: "faith-in-real-life",
    name: "Faith in Real Life",
    description: "What Scripture teaches about trusting God in everyday life.",
    questions: [
      {
        question: "What does Hebrews 11:1 say faith is?",
        choices: ["A feeling only", "Confidence in what we hope for", "Pretending life is easy", "Never asking questions"],
        correct: "Confidence in what we hope for",
        ref: "Hebrews 11:1",
        note: "Faith is not wishful thinking. Biblical faith rests on the character, promises, and faithfulness of God.",
      },
      {
        question: "What fruit of the Spirit is listed first in Galatians 5?",
        choices: ["Patience", "Peace", "Love", "Self-control"],
        correct: "Love",
        ref: "Galatians 5:22-23",
        note: "The fruit of the Spirit begins with love because Spirit-filled living reflects the heart and character of Christ.",
      },
      {
        question: "According to Philippians 4:6-7, what should believers do instead of being anxious?",
        choices: ["Ignore their problems", "Pray about everything", "Complain more", "Control everyone"],
        correct: "Pray about everything",
        ref: "Philippians 4:6-7",
        note: "Prayer moves anxiety from our hands into God's hands. His peace guards the heart and mind even before every circumstance changes.",
      },
      {
        question: "What does Romans 8:28 teach believers?",
        choices: ["Life is random", "God works all things together for good", "Pain has no purpose", "Only strong people overcome"],
        correct: "God works all things together for good",
        ref: "Romans 8:28",
        note: "God does not waste suffering. For those who love Him, He is able to weave even painful circumstances into His redemptive purpose.",
      },
      {
        question: "According to Proverbs 3:5, what should we not lean on?",
        choices: ["God's Word", "Our own understanding", "Prayer", "Wisdom"],
        correct: "Our own understanding",
        ref: "Proverbs 3:5-6",
        note: "Trusting God means surrendering the demand to understand everything before obeying. God's direction is better than our limited perspective.",
      },
      {
        question: "According to Ephesians 6, what is the sword of the Spirit?",
        choices: ["Prayer", "Faith", "The Word of God", "The church"],
        correct: "The Word of God",
        ref: "Ephesians 6:17",
        note: "God's Word is the believer's offensive weapon against lies, temptation, discouragement, and spiritual attack.",
      },
      {
        question: "What does Psalm 119:105 compare God's Word to?",
        choices: ["A lamp and a light", "A sword and shield", "Bread and water", "A mountain"],
        correct: "A lamp and a light",
        ref: "Psalm 119:105",
        note: "God's Word gives guidance one step at a time. It may not reveal the whole road, but it gives enough light for faithful obedience.",
      },
      {
        question: "What does Jesus say is the greatest commandment?",
        choices: ["Love your neighbor only", "Love the Lord your God", "Keep traditions", "Avoid all sinners"],
        correct: "Love the Lord your God",
        ref: "Matthew 22:37-38",
        note: "Love for God is the foundation of obedience. Christianity is not merely behavior modification; it is a surrendered heart loving God fully.",
      },
      {
        question: "What happens when someone is in Christ according to 2 Corinthians 5:17?",
        choices: ["They stay the same", "They become a new creation", "They never struggle again", "They become religious only"],
        correct: "They become a new creation",
        ref: "2 Corinthians 5:17",
        note: "Christian identity is not built on the old life. In Christ, a person receives a new identity, new direction, and new hope.",
      },
      {
        question: "What does James say faith without works is?",
        choices: ["Hidden", "Dead", "Optional", "Perfect"],
        correct: "Dead",
        ref: "James 2:17",
        note: "Works do not save us, but genuine faith produces visible obedience. Living faith shows up in real choices.",
      },
    ],
  },
  {
    id: "marriage-and-family",
    name: "Marriage & Family",
    description: "Biblical wisdom for marriage, parenting, and home life.",
    questions: [
      {
        question: "According to Joshua 24:15, whom did Joshua say his household would serve?",
        choices: ["Pharaoh", "The Lord", "Baal", "Rome"],
        correct: "The Lord",
        ref: "Joshua 24:15",
        note: "Joshua made a clear household commitment. Families are strengthened when spiritual direction is intentional, not accidental.",
      },
      {
        question: "What does 1 Corinthians 13 say love is?",
        choices: ["Impatient and proud", "Patient and kind", "Always suspicious", "Only emotional"],
        correct: "Patient and kind",
        ref: "1 Corinthians 13:4",
        note: "Love is not only a feeling; it is a Spirit-shaped way of treating people with patience, kindness, humility, and endurance.",
      },
      {
        question: "What does Colossians 3:13 call believers to do?",
        choices: ["Keep score", "Forgive as the Lord forgave", "Win every argument", "Avoid all hard talks"],
        correct: "Forgive as the Lord forgave",
        ref: "Colossians 3:13",
        note: "Forgiveness does not mean pretending hurt did not happen. It means releasing vengeance to God and choosing grace because Christ has shown grace to us.",
      },
      {
        question: "What does Genesis 2:24 say a husband and wife become?",
        choices: ["Two teams", "One flesh", "Friendly neighbors", "Separate households"],
        correct: "One flesh",
        ref: "Genesis 2:24",
        note: "Marriage is designed for covenant unity. God's vision is deeper than coexisting; it is shared life, loyalty, and oneness.",
      },
      {
        question: "What does Proverbs 15:1 say a gentle answer does?",
        choices: ["Stirs up anger", "Turns away wrath", "Ends every relationship", "Proves weakness"],
        correct: "Turns away wrath",
        ref: "Proverbs 15:1",
        note: "Gentleness is not weakness. A soft answer can de-escalate tension and make room for wisdom.",
      },
      {
        question: "According to James 1:19, what should we be quick to do?",
        choices: ["Speak", "Become angry", "Listen", "Judge"],
        correct: "Listen",
        ref: "James 1:19",
        note: "Healthy communication begins with listening. Many conflicts grow because people respond before they understand.",
      },
      {
        question: "What does Ecclesiastes 4:12 say about a cord of three strands?",
        choices: ["It is quickly broken", "It is not quickly broken", "It is useless", "It must be hidden"],
        correct: "It is not quickly broken",
        ref: "Ecclesiastes 4:12",
        note: "When God is at the center, relationships have greater strength, endurance, and resilience.",
      },
      {
        question: "What does Ephesians 4:32 tell believers to be toward one another?",
        choices: ["Bitter and cold", "Kind and compassionate", "Proud and distant", "Silent and resentful"],
        correct: "Kind and compassionate",
        ref: "Ephesians 4:32",
        note: "Kindness and compassion are not optional extras; they are evidence of a heart shaped by the forgiveness of Christ.",
      },
      {
        question: "According to Ephesians 5:25, how should husbands love their wives?",
        choices: ["Only when it is easy", "As Christ loved the church", "By controlling everything", "By avoiding conflict"],
        correct: "As Christ loved the church",
        ref: "Ephesians 5:25",
        note: "Biblical love is sacrificial, protective, and Christlike. A husband's love should point his wife toward the heart of Jesus.",
      },
      {
        question: "What should parents do according to Proverbs 22:6?",
        choices: ["Ignore instruction", "Train up a child", "Let children lead everything", "Avoid discipline"],
        correct: "Train up a child",
        ref: "Proverbs 22:6",
        note: "Godly parenting involves intentional direction, patient instruction, and consistent example. Children need formation, not just correction.",
      },
    ],
  },
  {
    id: "recovery-and-restoration",
    name: "Recovery & Restoration",
    description: "God's heart for healing, forgiveness, and new beginnings.",
    questions: [
      {
        question: "What does Galatians 6:1 say spiritual people should do for someone caught in sin?",
        choices: ["Expose them harshly", "Restore them gently", "Avoid them forever", "Celebrate their failure"],
        correct: "Restore them gently",
        ref: "Galatians 6:1",
        note: "Restoration must be done with gentleness and humility. The goal is not humiliation; the goal is healing and return.",
      },
      {
        question: "What does Matthew 11:28 invite the weary to do?",
        choices: ["Work harder alone", "Come to Jesus for rest", "Hide their pain", "Pretend they are fine"],
        correct: "Come to Jesus for rest",
        ref: "Matthew 11:28",
        note: "Jesus invites the weary, not just the impressive. His rest reaches people carrying burdens too heavy to bear alone.",
      },
      {
        question: "In Luke 15, what did the father do when the prodigal son returned?",
        choices: ["Rejected him", "Ran to him and welcomed him", "Ignored him", "Made him leave again"],
        correct: "Ran to him and welcomed him",
        ref: "Luke 15:20-24",
        note: "The father's welcome reveals God's heart toward repentant sinners. Return is met with compassion, not coldness.",
      },
      {
        question: "What does Romans 12:2 say believers should be transformed by?",
        choices: ["Popularity", "The renewing of the mind", "Fear", "Pressure"],
        correct: "The renewing of the mind",
        ref: "Romans 12:2",
        note: "Transformation begins as God renews the mind. New patterns of thought lead to new patterns of life.",
      },
      {
        question: "According to 1 John 1:9, what happens when we confess our sins?",
        choices: ["God rejects us", "God forgives and cleanses us", "Nothing happens", "We must hide better"],
        correct: "God forgives and cleanses us",
        ref: "1 John 1:9",
        note: "Confession brings sin into the light where grace can deal with it. God is faithful and just to forgive because of Christ.",
      },
      {
        question: "What does Isaiah 61:3 say God gives instead of ashes?",
        choices: ["More shame", "A crown of beauty", "Confusion", "Punishment only"],
        correct: "A crown of beauty",
        ref: "Isaiah 61:3",
        note: "God specializes in restoration. He can bring beauty, joy, and praise from places marked by grief and loss.",
      },
      {
        question: "What does John 8:36 say about the Son?",
        choices: ["He partly helps", "He sets people free indeed", "He brings confusion", "He only teaches rules"],
        correct: "He sets people free indeed",
        ref: "John 8:36",
        note: "True freedom is found in Christ. He does not merely manage bondage; He breaks the power of sin and shame.",
      },
      {
        question: "According to Lamentations 3:22-23, what is new every morning?",
        choices: ["God's mercies", "Our excuses", "Our fear", "The law"],
        correct: "God's mercies",
        ref: "Lamentations 3:22-23",
        note: "God's mercy is not stale or exhausted. Every morning is another testimony to His faithfulness.",
      },
      {
        question: "What does Joel 2:25 say God can restore?",
        choices: ["Years the locusts have eaten", "Only money", "Only reputation", "Nothing from the past"],
        correct: "Years the locusts have eaten",
        ref: "Joel 2:25",
        note: "God can restore what sin, loss, delay, and hardship have damaged. Restoration belongs to His redemptive nature.",
      },
      {
        question: "What does Psalm 34:18 say about the Lord?",
        choices: ["He avoids the brokenhearted", "He is close to the brokenhearted", "He only helps the strong", "He forgets the hurting"],
        correct: "He is close to the brokenhearted",
        ref: "Psalm 34:18",
        note: "God does not despise brokenness. He draws near to those who are crushed and offers presence, comfort, and rescue.",
      },
    ],
  },
  {
    id: "mixed-challenge",
    name: "Mixed Challenge",
    description: "A mix of questions pulled from every category above.",
    questions: [
      {
        question: "According to 1 John 1:9, what happens when we confess our sins?",
        choices: ["God rejects us", "God forgives and cleanses us", "Nothing happens", "We must hide better"],
        correct: "God forgives and cleanses us",
        ref: "1 John 1:9",
        note: "Confession brings sin into the light where grace can deal with it. God is faithful and just to forgive because of Christ.",
      },
      {
        question: "What did the angel say after Jesus rose from the dead?",
        choices: ["He is not here; He is risen", "Wait for Moses", "Go back to Egypt", "Build an altar"],
        correct: "He is not here; He is risen",
        ref: "Matthew 28:5-6",
        note: "The resurrection is the center of Christian hope. Jesus conquered sin and death, proving that His promises are true.",
      },
      {
        question: "What does Hebrews 11:1 say faith is?",
        choices: ["A feeling only", "Confidence in what we hope for", "Pretending life is easy", "Never asking questions"],
        correct: "Confidence in what we hope for",
        ref: "Hebrews 11:1",
        note: "Faith is not wishful thinking. Biblical faith rests on the character, promises, and faithfulness of God.",
      },
      {
        question: "What does Colossians 3:13 call believers to do?",
        choices: ["Keep score", "Forgive as the Lord forgave", "Win every argument", "Avoid all hard talks"],
        correct: "Forgive as the Lord forgave",
        ref: "Colossians 3:13",
        note: "Forgiveness does not mean pretending hurt did not happen. It means releasing vengeance to God and choosing grace because Christ has shown grace to us.",
      },
      {
        question: "Who was swallowed by a great fish?",
        choices: ["Elijah", "Jonah", "Paul", "Peter"],
        correct: "Jonah",
        ref: "Jonah 1:17",
        note: "Jonah ran from God's assignment, but God pursued him. His story shows both God's mercy toward sinners and His patience with reluctant servants.",
      },
      {
        question: "Which disciple is often called doubting Thomas?",
        choices: ["Andrew", "Thomas", "Philip", "Matthew"],
        correct: "Thomas",
        ref: "John 20:24-29",
        note: "Thomas struggled to believe, but Jesus met him with grace and truth. Honest doubt should lead us toward Christ, not away from Him.",
      },
      {
        question: "What does Galatians 6:1 say spiritual people should do for someone caught in sin?",
        choices: ["Expose them harshly", "Restore them gently", "Avoid them forever", "Celebrate their failure"],
        correct: "Restore them gently",
        ref: "Galatians 6:1",
        note: "Restoration must be done with gentleness and humility. The goal is not humiliation; the goal is healing and return.",
      },
      {
        question: "According to Ephesians 6, what is the sword of the Spirit?",
        choices: ["Prayer", "Faith", "The Word of God", "The church"],
        correct: "The Word of God",
        ref: "Ephesians 6:17",
        note: "God's Word is the believer's offensive weapon against lies, temptation, discouragement, and spiritual attack.",
      },
      {
        question: "According to Philippians 4:6-7, what should believers do instead of being anxious?",
        choices: ["Ignore their problems", "Pray about everything", "Complain more", "Control everyone"],
        correct: "Pray about everything",
        ref: "Philippians 4:6-7",
        note: "Prayer moves anxiety from our hands into God's hands. His peace guards the heart and mind even before every circumstance changes.",
      },
      {
        question: "What does Genesis 2:24 say a husband and wife become?",
        choices: ["Two teams", "One flesh", "Friendly neighbors", "Separate households"],
        correct: "One flesh",
        ref: "Genesis 2:24",
        note: "Marriage is designed for covenant unity. God's vision is deeper than coexisting; it is shared life, loyalty, and oneness.",
      },
    ],
  },
];
