import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { ministryPortals } from "@/lib/ministry-hub";

export default async function EventsPage(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/login");
 const {data:gatherings}=await supabase.from("ministry_content").select("id,ministry_slug,title,summary,link_url,starts_at,ends_at,location").eq("content_type","gathering").eq("is_published",true).gte("starts_at",new Date().toISOString()).order("starts_at",{ascending:true}).limit(30);
 const next=gatherings?.[0]; const rest=(gatherings??[]).slice(1);
 return <main className="lfp-page pb-24">
  <section className="relative overflow-hidden"><div aria-hidden className="lfp-grid absolute inset-0"/><div aria-hidden className="lfp-orb -right-24 top-4 h-72 w-72 bg-sky-200/45"/><div className="lfp-shell relative py-12 sm:py-16"><p className="lfp-eyebrow">Gather</p><h1 className="mt-3 text-4xl font-black tracking-[-.045em] text-slate-950 sm:text-6xl">Faith grows differently when you <span className="lfp-gradient-text">show up together.</span></h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">One simple place for gatherings across the entire Lost & Found ministry family.</p></div></section>
  <div className="lfp-shell py-8 sm:py-12">
   {next?<section className="rounded-[2rem] bg-[rgb(var(--lfp-ink))] p-7 text-white shadow-2xl sm:p-9"><div className="grid gap-7 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-[11px] font-black uppercase tracking-[.17em] text-sky-300">Up next</p><p className="mt-3 text-sm font-bold text-slate-400">{ministryPortals.find(m=>m.slug===next.ministry_slug)?.title||"L&F"} · {new Date(next.starts_at).toLocaleString()}</p><h2 className="mt-2 text-3xl font-black sm:text-4xl">{next.title}</h2>{next.summary&&<p className="mt-3 max-w-3xl leading-7 text-slate-300">{next.summary}</p>}{next.location&&<p className="mt-4 font-bold text-slate-200">⌖ {next.location}</p>}</div>{next.link_url&&<a href={next.link_url} className="lfp-button bg-white text-slate-950">Event details →</a>}</div></section>:<section className="lfp-card p-7 sm:p-9"><p className="lfp-eyebrow">Up next</p><h2 className="mt-2 text-3xl font-black text-slate-950">Nothing is published yet.</h2><p className="mt-3 max-w-2xl leading-7 text-slate-600">When a ministry publishes a gathering, the next one will become the focal point here automatically.</p></section>}
   {rest.length>0&&<section className="mt-12"><p className="lfp-eyebrow">Coming up</p><h2 className="mt-2 text-3xl font-black text-slate-950">More ways to gather</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{rest.map((event:any)=>{const ministry=ministryPortals.find(m=>m.slug===event.ministry_slug);return <article key={event.id} className="lfp-card p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-black uppercase tracking-[.15em] text-blue-700">{ministry?.title||"L&F"}</p><h3 className="mt-2 text-xl font-black text-slate-950">{event.title}</h3></div><span className="rounded-2xl bg-blue-50 px-3 py-2 text-right text-xs font-black text-blue-700">{new Date(event.starts_at).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</span></div>{event.summary&&<p className="mt-3 leading-7 text-slate-600">{event.summary}</p>}{event.location&&<p className="mt-3 text-sm font-bold text-slate-700">⌖ {event.location}</p>}{event.link_url&&<a href={event.link_url} className="mt-4 inline-flex font-black text-blue-700">Details →</a>}</article>})}</div></section>}
   <section className="mt-12"><p className="lfp-eyebrow">Browse by ministry</p><h2 className="mt-2 text-3xl font-black text-slate-950">Find your space.</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{ministryPortals.map(m=><Link key={m.slug} href={`/ministries/${m.slug}`} className="lfp-card p-6"><span className="text-2xl">{m.icon}</span><p className="mt-4 text-[11px] font-black uppercase tracking-[.16em] text-blue-700">{m.eyebrow}</p><h3 className="mt-1 text-xl font-black text-slate-950">{m.title}</h3><p className="mt-2 leading-7 text-slate-600">{m.description}</p></Link>)}</div></section>
  </div>
 </main>;
}
