import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { ministryPortals } from "@/lib/ministry-hub";
import { respondToInvitation } from "./actions";

function ministryTitle(slug:string|null|undefined){return ministryPortals.find(m=>m.slug===slug)?.title||"L&F";}
function formatTime(value:string){return new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:"America/New_York"}).format(new Date(value));}

export default async function EventsPage(){
 const supabase=await createClient();
 const{data:{user}}=await supabase.auth.getUser();
 if(!user)redirect("/login?next=%2Fevents");
 const now=new Date();const floor=new Date(now.getTime()-4*60*60*1000).toISOString();
 const[{data:gatherings},{data:assignments}]=await Promise.all([
  supabase.from("ministry_content").select("id,ministry_slug,title,summary,link_url,starts_at,ends_at,location").eq("content_type","gathering").eq("is_published",true).gte("starts_at",now.toISOString()).order("starts_at",{ascending:true}).limit(30),
  supabase.from("study_session_participants").select("study_session_id,rsvp_status,responded_at,study_sessions(id,scheduled_start,scheduled_end,status,ministry_slug,daily_path_released_at,google_meeting_uri,bible_studies(id,title))").eq("user_id",user.id)
 ]);
 const sessions=(assignments??[]).map((row:any)=>{const session=Array.isArray(row.study_sessions)?row.study_sessions[0]:row.study_sessions;return session?{...session,rsvp_status:row.rsvp_status||"invited"}:null}).filter((x:any)=>x&&["scheduled","live"].includes(x.status)&&x.scheduled_start>=floor).sort((a:any,b:any)=>+new Date(a.scheduled_start)-+new Date(b.scheduled_start));
 const next=gatherings?.[0];const rest=(gatherings??[]).slice(1);
 return <main className="lfp-page pb-24">
  <section className="relative overflow-hidden"><div aria-hidden className="lfp-grid absolute inset-0"/><div aria-hidden className="lfp-orb -right-24 top-4 h-72 w-72 bg-sky-200/45"/><div className="lfp-shell relative py-12 sm:py-16"><p className="lfp-eyebrow">Gatherings</p><h1 className="mt-3 text-4xl font-black tracking-[-.045em] text-slate-950 sm:text-6xl">Know where to show up, <span className="lfp-gradient-text">then keep walking together.</span></h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">Your assigned studies and the wider L&amp;F gathering calendar live together here. Respond to invitations, join L&amp;F Live, and return to the ministry space that is hosting you.</p></div></section>
  <div className="lfp-shell py-8 sm:py-12">
   <section><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="lfp-eyebrow">For you</p><h2 className="mt-2 text-3xl font-black text-slate-950">Your invitations</h2><p className="mt-2 max-w-2xl leading-7 text-slate-600">These sessions are assigned directly to you or your study group.</p></div></div>
    {sessions.length?<div className="mt-6 grid gap-4">{sessions.map((session:any)=>{const study=Array.isArray(session.bible_studies)?session.bible_studies[0]:session.bible_studies;return <article key={session.id} className="rounded-[1.8rem] border border-indigo-100 bg-indigo-50/60 p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[11px] font-black uppercase tracking-[.16em] text-indigo-700">{ministryTitle(session.ministry_slug)} · {session.status==="live"?"Live now":"Assigned gathering"}</p><h3 className="mt-2 text-2xl font-black text-slate-950">{study?.title||"Bible Study"}</h3><p className="mt-2 font-bold text-slate-600">{formatTime(session.scheduled_start)} ET</p></div><span className="rounded-full bg-white px-3 py-1 text-xs font-black uppercase text-indigo-700 ring-1 ring-indigo-100">{session.rsvp_status==="invited"?"Response needed":session.rsvp_status}</span></div>
     <div className="mt-5 flex flex-wrap gap-2"><form action={respondToInvitation}><input type="hidden" name="session_id" value={session.id}/><input type="hidden" name="status" value="going"/><button className={"rounded-xl px-3 py-2 text-sm font-black "+(session.rsvp_status==="going"?"bg-emerald-700 text-white":"border border-emerald-200 bg-white text-emerald-800")}>Going</button></form><form action={respondToInvitation}><input type="hidden" name="session_id" value={session.id}/><input type="hidden" name="status" value="maybe"/><button className={"rounded-xl px-3 py-2 text-sm font-black "+(session.rsvp_status==="maybe"?"bg-amber-500 text-slate-950":"border border-amber-200 bg-white text-amber-800")}>Maybe</button></form><form action={respondToInvitation}><input type="hidden" name="session_id" value={session.id}/><input type="hidden" name="status" value="declined"/><button className={"rounded-xl px-3 py-2 text-sm font-black "+(session.rsvp_status==="declined"?"bg-slate-700 text-white":"border bg-white text-slate-700")}>Can&apos;t make it</button></form></div>
     <div className="mt-5 flex flex-wrap gap-3 border-t border-indigo-100 pt-5"><Link href={`/live/${session.id}`} className="lfp-button bg-gradient-to-r from-indigo-700 to-violet-700 text-white">{session.status==="live"?"Join L&F Live now":"Open gathering"}</Link>{study?.id&&<Link href={`/studies/${study.id}`} className="lfp-button border bg-white text-slate-950">Open Study</Link>}<Link href={`/ministries/${session.ministry_slug}`} className="lfp-button border bg-white text-slate-950">Ministry Space</Link></div>
    </article>})}</div>:<div className="lfp-card mt-6 p-7"><h3 className="text-xl font-black text-slate-950">No assigned gatherings are waiting.</h3><p className="mt-2 leading-7 text-slate-600">When a facilitator schedules you for a study, it will appear here and on Home.</p></div>}
   </section>
   <section className="mt-14"><p className="lfp-eyebrow">Across L&amp;F</p><h2 className="mt-2 text-3xl font-black text-slate-950">Public gatherings</h2>
   {next?<div className="mt-6 rounded-[2rem] bg-[rgb(var(--lfp-ink))] p-7 text-white shadow-2xl sm:p-9"><div className="grid gap-7 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-[11px] font-black uppercase tracking-[.17em] text-sky-300">Up next</p><p className="mt-3 text-sm font-bold text-slate-400">{ministryTitle(next.ministry_slug)} · {formatTime(next.starts_at)} ET</p><h3 className="mt-2 text-3xl font-black sm:text-4xl">{next.title}</h3>{next.summary&&<p className="mt-3 max-w-3xl leading-7 text-slate-300">{next.summary}</p>}{next.location&&<p className="mt-4 font-bold text-slate-200">⌖ {next.location}</p>}</div><div className="flex flex-wrap gap-2">{next.link_url&&<a href={next.link_url} className="lfp-button bg-white text-slate-950">Event details →</a>}<Link href={`/ministries/${next.ministry_slug}`} className="lfp-button border border-white/20 bg-white/10 text-white">Ministry Space</Link></div></div></div>:<div className="lfp-card mt-6 p-7"><h3 className="text-xl font-black text-slate-950">Nothing public is scheduled yet.</h3><p className="mt-2 leading-7 text-slate-600">Assigned study sessions can still appear above even when the public calendar is quiet.</p></div>}
   {rest.length>0&&<div className="mt-6 grid gap-4 md:grid-cols-2">{rest.map((event:any)=><article key={event.id} className="lfp-card p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-black uppercase tracking-[.15em] text-blue-700">{ministryTitle(event.ministry_slug)}</p><h3 className="mt-2 text-xl font-black text-slate-950">{event.title}</h3></div><span className="rounded-2xl bg-blue-50 px-3 py-2 text-right text-xs font-black text-blue-700">{new Date(event.starts_at).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</span></div>{event.summary&&<p className="mt-3 leading-7 text-slate-600">{event.summary}</p>}{event.location&&<p className="mt-3 text-sm font-bold text-slate-700">⌖ {event.location}</p>}<div className="mt-4 flex flex-wrap gap-3">{event.link_url&&<a href={event.link_url} className="font-black text-blue-700">Details →</a>}<Link href={`/ministries/${event.ministry_slug}`} className="font-black text-slate-600">Ministry Space →</Link></div></article>)}</div>}
   </section>
   <section className="mt-14"><p className="lfp-eyebrow">Browse by ministry</p><h2 className="mt-2 text-3xl font-black text-slate-950">Find your space.</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{ministryPortals.map(m=><Link key={m.slug} href={`/ministries/${m.slug}`} className="lfp-card p-6"><span className="text-2xl">{m.icon}</span><p className="mt-4 text-[11px] font-black uppercase tracking-[.16em] text-blue-700">{m.eyebrow}</p><h3 className="mt-1 text-xl font-black text-slate-950">{m.title}</h3><p className="mt-2 leading-7 text-slate-600">{m.description}</p></Link>)}</div></section>
  </div>
 </main>;
}
