import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getMinistryPortal, ministryPortals } from "@/lib/ministry-hub";
import { joinMinistry, leaveMinistry } from "../actions";

export function generateStaticParams(){return ministryPortals.map(({slug})=>({slug}));}

const themes={
 warm:{orb:"bg-amber-200/45",chip:"bg-amber-50 text-amber-800",soft:"border-amber-200 bg-amber-50/70"},
 steel:{orb:"bg-slate-300/45",chip:"bg-slate-100 text-slate-800",soft:"border-slate-200 bg-slate-100/80"},
 ink:{orb:"bg-violet-200/45",chip:"bg-violet-50 text-violet-800",soft:"border-violet-200 bg-violet-50/70"},
};

export default async function MinistryPortalPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params; const ministry=getMinistryPortal(slug); if(!ministry)notFound(); const theme=themes[ministry.accent]; const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/login");
 const [{data:content},{data:membership}]=await Promise.all([
  supabase.from("ministry_content").select("id,content_type,title,summary,body,link_url,starts_at,location,action_label,is_featured").eq("ministry_slug",slug).eq("is_published",true).order("sort_order").order("created_at",{ascending:false}),
  supabase.from("ministry_memberships").select("id,membership_role").eq("ministry_slug",slug).eq("user_id",user.id).maybeSingle()
 ]);
 const featured=(content??[]).filter((x:any)=>x.is_featured); const regular=(content??[]).filter((x:any)=>!x.is_featured); const gatherings=(content??[]).filter((x:any)=>x.content_type==="gathering"); const studies=(content??[]).filter((x:any)=>x.content_type==="study"); const serve=(content??[]).filter((x:any)=>x.content_type==="serve");
 return <main className="lfp-page pb-24">
  <section className="relative overflow-hidden"><div aria-hidden className="lfp-grid absolute inset-0"/><div aria-hidden className={`lfp-orb -right-20 top-0 h-72 w-72 ${theme.orb}`}/><div className="lfp-shell relative py-10 sm:py-14"><Link href="/ministries" className="text-sm font-black text-slate-500">← Ministry spaces</Link><div className="mt-7 grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div className="max-w-4xl"><span className={`inline-flex rounded-full px-3 py-1.5 text-[11px] font-black uppercase tracking-[.16em] ${theme.chip}`}>{ministry.eyebrow}</span><div className="mt-4 flex items-center gap-4"><span className="text-4xl">{ministry.icon}</span><h1 className="text-4xl font-black tracking-[-.045em] text-slate-950 sm:text-6xl">{ministry.title}</h1></div><h2 className="mt-5 max-w-3xl text-2xl font-black text-slate-950 sm:text-3xl">{ministry.experienceTitle}</h2><p className="mt-3 max-w-3xl text-lg leading-8 text-slate-600">{ministry.experienceDescription}</p></div><div className="flex flex-wrap gap-3 lg:justify-end"><form action={membership?leaveMinistry:joinMinistry}><input type="hidden" name="ministry_slug" value={slug}/><button className="lfp-button lfp-button-secondary">{membership?"Following ✓":"Follow"}</button></form>{ministry.actions[0].external?<a href={ministry.actions[0].href} target="_blank" rel="noreferrer" className="lfp-button lfp-button-primary">{ministry.primaryLabel} ↗</a>:<Link href={ministry.actions[0].href} className="lfp-button lfp-button-primary">{ministry.primaryLabel} →</Link>}</div></div></div></section>
  <div className="lfp-shell py-8 sm:py-12"><section className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><article className="lfp-card p-6 sm:p-8"><p className="lfp-eyebrow">Welcome</p><p className="mt-4 text-lg leading-8 text-slate-600">{ministry.welcome}</p></article><aside className={`rounded-[2rem] border p-6 sm:p-8 ${theme.soft}`}><p className="text-[11px] font-black uppercase tracking-[.16em] text-slate-700">Scripture anchor</p><p className="mt-3 text-3xl font-black text-slate-950">{ministry.scripture}</p><p className="mt-3 leading-7 text-slate-600">{ministry.purpose}</p></aside></section>
   <Focus slug={slug} gatherings={gatherings.length} studies={studies.length} serve={serve.length}/>
   <section className="mt-12"><p className="lfp-eyebrow">Next steps</p><h2 className="mt-2 text-3xl font-black text-slate-950">Choose a meaningful action.</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{ministry.actions.map(a=>{const body=<><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-blue-50 text-xl text-blue-700">{a.icon}</span><span><span className="text-lg font-black text-slate-950">{a.label}</span><span className="mt-1 block leading-6 text-slate-600">{a.description}</span></span></>;return a.external?<a key={a.label} href={a.href} target="_blank" rel="noreferrer" className="lfp-card flex gap-4 p-5">{body}</a>:<Link key={a.label} href={a.href} className="lfp-card flex gap-4 p-5">{body}</Link>})}</div></section>
   {featured.length>0&&<section className="mt-12"><p className="lfp-eyebrow">Featured</p><div className="mt-5 grid gap-4 md:grid-cols-2">{featured.map((item:any)=><ContentCard key={item.id} item={item}/>)}</div></section>}
   {regular.length>0&&<section className="mt-12"><p className="lfp-eyebrow">From {ministry.title}</p><h2 className="mt-2 text-3xl font-black text-slate-950">Latest in this space</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{regular.map((item:any)=><ContentCard key={item.id} item={item}/>)}</div></section>}
   <section className="mt-12 grid gap-5 lg:grid-cols-2"><article className="lfp-card p-6"><p className="lfp-eyebrow">Ministry rhythm</p><ol className="mt-5 space-y-3">{ministry.rhythms.map((r,i)=><li key={r} className="flex gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-blue-50 text-xs font-black text-blue-700">{i+1}</span><span className="pt-1 font-bold text-slate-700">{r}</span></li>)}</ol></article><article className={`rounded-[2rem] border p-6 ${theme.soft}`}><p className="lfp-eyebrow">Explore this space</p><div className="mt-5 flex flex-wrap gap-2">{ministry.resourceTopics.map(t=><span key={t} className="rounded-full bg-white px-4 py-2 text-sm font-bold text-slate-700 shadow-sm">{t}</span>)}</div></article></section>
   <section className="mt-12 rounded-[2rem] bg-[rgb(var(--lfp-ink))] p-7 text-white"><p className="text-[11px] font-black uppercase tracking-[.17em] text-sky-300">One L&F family</p><h2 className="mt-2 text-2xl font-black">Distinct space. Shared community.</h2><p className="mt-3 max-w-3xl leading-7 text-slate-300">Prayer, praise, testimony, gatherings, and discovery connect every ministry space without flattening what makes each one unique.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/community" className="lfp-button bg-white text-slate-950">Community</Link><Link href="/discover" className="lfp-button border border-white/15 bg-white/10 text-white">Discover</Link></div></section>
  </div>
 </main>;
}

function Focus({slug,gatherings,studies,serve}:{slug:string;gatherings:number;studies:number;serve:number}){
 const config=slug==="hearth"
  ?{eyebrow:"Around the Hearth",title:"Belonging is practiced.",copy:"Prioritize people and presence. Show up, notice who needs encouragement, celebrate what God is doing, and carry needs together.",stats:[`${gatherings} gatherings`,"Hospitality","Encouragement","Prayer"]}
  :slug==="foundry"
   ?{eyebrow:"Formation in motion",title:"Growth should become faithful action.",copy:"Move through a simple rhythm of truth, practice, service, and reflection rather than collecting information without application.",stats:[`${serve} service opportunities`,"Learn","Practice","Serve"]}
   :{eyebrow:"The study table",title:"Read carefully. Speak honestly. Walk it out.",copy:"Use Emmaus for deep Scripture work, then bring your observations into honest conversation, prayer, accountability, and application.",stats:[`${studies} study items`,"Observe","Discuss","Apply"]};
 return <section className="mt-12 rounded-[2rem] bg-[rgb(var(--lfp-ink))] p-7 text-white sm:p-9"><p className="text-[11px] font-black uppercase tracking-[.17em] text-sky-300">{config.eyebrow}</p><h2 className="mt-2 text-3xl font-black">{config.title}</h2><p className="mt-3 max-w-3xl leading-7 text-slate-300">{config.copy}</p><div className="mt-6 flex flex-wrap gap-2">{config.stats.map(s=><span key={s} className="rounded-full bg-white/10 px-4 py-2 text-sm font-bold">{s}</span>)}</div></section>
}

function ContentCard({item}:{item:any}){return <article className="lfp-card p-5"><div className="text-[11px] font-black uppercase tracking-[.15em] text-blue-700">{item.content_type}</div><h3 className="mt-2 text-xl font-black text-slate-950">{item.title}</h3>{item.starts_at&&<p className="mt-2 text-sm font-bold text-slate-500">{new Date(item.starts_at).toLocaleString()}</p>}{item.location&&<p className="mt-2 text-sm font-bold text-slate-700">⌖ {item.location}</p>}{item.summary&&<p className="mt-3 leading-7 text-slate-600">{item.summary}</p>}{item.body&&<p className="mt-3 whitespace-pre-line leading-7 text-slate-600">{item.body}</p>}{item.link_url&&<a href={item.link_url} className="mt-4 inline-flex font-black text-blue-700">{item.action_label||"Learn more"} →</a>}</article>}
