import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getMinistryPortal, ministryPortals } from "@/lib/ministry-hub";
import { joinMinistry, leaveMinistry } from "../actions";
export function generateStaticParams(){return ministryPortals.map(({slug})=>({slug}));}
export default async function MinistryPortalPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params; const ministry=getMinistryPortal(slug); if(!ministry)notFound(); const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/login");
 const [{data:content},{data:membership}]=await Promise.all([supabase.from("ministry_content").select("id,content_type,title,summary,body,link_url,starts_at,location,action_label,is_featured").eq("ministry_slug",slug).eq("is_published",true).order("sort_order").order("created_at",{ascending:false}),supabase.from("ministry_memberships").select("id,membership_role").eq("ministry_slug",slug).eq("user_id",user.id).maybeSingle()]);
 const featured=(content??[]).filter((x:any)=>x.is_featured); const regular=(content??[]).filter((x:any)=>!x.is_featured);
 return <main className="lfp-page pb-24"><section className="relative overflow-hidden bg-slate-950 text-white"><div className="lfp-shell relative py-12 sm:py-16"><Link href="/ministries" className="text-sm font-bold text-indigo-200">← Ministry Hub</Link><div className="mt-6 flex items-center gap-4"><span className="text-3xl">{ministry.icon}</span><div><p className="text-xs font-black uppercase tracking-[.2em] text-amber-300">{ministry.eyebrow}</p><h1 className="mt-1 text-4xl font-black sm:text-6xl">{ministry.title}</h1></div></div><p className="mt-6 max-w-3xl text-lg leading-8 text-indigo-100/75">{ministry.description}</p><form action={membership?leaveMinistry:joinMinistry} className="mt-7"><input type="hidden" name="ministry_slug" value={slug}/><button className="lfp-button bg-amber-300 text-slate-950">{membership?"Following ministry ✓":"Follow this ministry"}</button></form></div></section>
 <div className="lfp-shell py-10 sm:py-14"><section className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><article className="lfp-card p-6 sm:p-8"><p className="lfp-eyebrow">Welcome</p><h2 className="mt-2 text-3xl font-black">This is a place to participate.</h2><p className="mt-4 text-lg leading-8 text-slate-600">{ministry.welcome}</p></article><aside className="rounded-[2rem] border border-amber-200 bg-amber-50 p-6 sm:p-8"><p className="text-xs font-black uppercase text-amber-800">Scripture anchor</p><p className="mt-3 text-3xl font-black">{ministry.scripture}</p><p className="mt-3 text-slate-600">{ministry.purpose}</p></aside></section>
 {featured.length>0&&<section className="mt-12"><p className="lfp-eyebrow">Featured</p><div className="mt-4 grid gap-4 md:grid-cols-2">{featured.map((item:any)=><ContentCard key={item.id} item={item}/>)}</div></section>}
 <section className="mt-12"><p className="lfp-eyebrow">Start Here</p><h2 className="mt-2 text-3xl font-black">Take a real next step.</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{ministry.actions.map(a=><Link key={a.label} href={a.href} className="lfp-card flex gap-4 p-5"><span className="text-xl">{a.icon}</span><span><span className="text-lg font-black">{a.label} →</span><span className="mt-1 block text-slate-600">{a.description}</span></span></Link>)}</div></section>
 {regular.length>0&&<section className="mt-12"><p className="lfp-eyebrow">Latest</p><h2 className="mt-2 text-3xl font-black">From {ministry.title}</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{regular.map((item:any)=><ContentCard key={item.id} item={item}/>)}</div></section>}
 <section className="mt-12 grid gap-6 lg:grid-cols-2"><article className="lfp-card p-6"><p className="lfp-eyebrow">Ministry Rhythm</p><ol className="mt-5 space-y-3">{ministry.rhythms.map((r,i)=><li key={r} className="flex gap-3"><span className="font-black">{i+1}.</span><span className="font-bold">{r}</span></li>)}</ol></article><article className="rounded-[2rem] bg-indigo-50 p-6"><p className="lfp-eyebrow">Resource Shelf</p><div className="mt-5 flex flex-wrap gap-2">{ministry.resourceTopics.map(t=><span key={t} className="rounded-full bg-white px-4 py-2 text-sm font-bold">{t}</span>)}</div></article></section>
 <section className="mt-12 rounded-[2rem] bg-slate-950 p-6 text-white"><p className="text-xs font-black uppercase text-amber-300">One L&F Family</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/prayer" className="lfp-button bg-amber-300 text-slate-950">Prayer</Link><Link href="/praise" className="lfp-button bg-white/10 text-white">Praise</Link><Link href="/testimonies" className="lfp-button bg-white/10 text-white">Testimonies</Link><Link href="/events" className="lfp-button bg-white/10 text-white">Events</Link></div></section></div></main>;
}
function ContentCard({item}:{item:any}){return <article className="lfp-card p-5"><div className="text-xs font-black uppercase tracking-wide text-indigo-700">{item.content_type}</div><h3 className="mt-2 text-xl font-black">{item.title}</h3>{item.starts_at&&<p className="mt-2 text-sm font-bold text-slate-500">{new Date(item.starts_at).toLocaleString()}</p>}{item.location&&<p className="mt-2 text-sm font-bold">📍 {item.location}</p>}{item.summary&&<p className="mt-3 leading-7 text-slate-600">{item.summary}</p>}{item.body&&<p className="mt-3 whitespace-pre-line leading-7 text-slate-600">{item.body}</p>}{item.link_url&&<a href={item.link_url} className="mt-4 inline-flex font-black text-indigo-700">{item.action_label||"Learn more"} →</a>}</article>}
