"use server";
import{revalidatePath}from"next/cache";import{redirect}from"next/navigation";import{createClient}from"@/lib/supabase/server";
async function admin(){const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)redirect("/login");const{data:p}=await s.from("profiles").select("role").eq("id",user.id).maybeSingle();if(p?.role!=="admin")redirect("/dashboard");return{s,user}}
const v=(f:FormData,k:string)=>String(f.get(k)||"").trim()||null;
export async function createDirectoryEntry(f:FormData){const{s,user}=await admin();const name=v(f,"name"),slug=v(f,"slug"),short_description=v(f,"short_description");if(!name||!slug||!short_description)return;const{error}=await s.from("directory_entries").insert({name,slug,short_description,entry_type:v(f,"entry_type")||"directory_listing",location_type:v(f,"location_type")||"local",city:v(f,"city"),state:v(f,"state"),website_url:v(f,"website_url"),services:v(f,"services"),who_served:v(f,"who_served"),created_by:user.id});if(error)throw new Error(error.message);revalidatePath("/studio/directory");}
export async function approveDirectoryEntry(f:FormData){const{s,user}=await admin();const id=v(f,"id");if(!id)return;const now=new Date(),due=new Date();due.setFullYear(due.getFullYear()+1);const{error}=await s.from("directory_entries").update({status:"approved",verification_status:"verified",last_verified_at:now.toISOString(),review_due_at:due.toISOString(),reviewed_by:user.id}).eq("id",id);if(error)throw new Error(error.message);revalidatePath("/studio/directory");revalidatePath("/directory");}

export async function setDirectoryCategories(f:FormData){const{s}=await admin();const id=v(f,"id");if(!id)return;const slugs=f.getAll("categories").map(x=>String(x));const{data:cats}=await s.from("directory_categories").select("id,slug").in("slug",slugs);await s.from("directory_entry_categories").delete().eq("entry_id",id);if(cats?.length){const{error}=await s.from("directory_entry_categories").insert(cats.map(c=>({entry_id:id,category_id:c.id})));if(error)throw new Error(error.message)}revalidatePath("/studio/directory");revalidatePath("/directory");}
export async function verifyDirectoryEntry(f:FormData){const{s,user}=await admin();const id=v(f,"id");if(!id)return;const now=new Date(),due=new Date();due.setFullYear(due.getFullYear()+1);const{error}=await s.from("directory_entries").update({verification_status:"verified",last_verified_at:now.toISOString(),review_due_at:due.toISOString(),reviewed_by:user.id}).eq("id",id);if(error)throw new Error(error.message);revalidatePath("/studio/directory");revalidatePath("/directory");}

export async function reviewDirectorySubmission(f:FormData){const{s,user}=await admin();const id=v(f,"id"),decision=v(f,"decision");if(!id||!decision)return;const status=decision==="accept"?"accepted":decision==="reject"?"rejected":"under_review";const{error}=await s.from("directory_submissions").update({status,reviewed_by:user.id,reviewed_at:new Date().toISOString()}).eq("id",id);if(error)throw new Error(error.message);revalidatePath("/studio/directory/review");}
export async function updateDirectoryPartnership(f:FormData){const{s,user}=await admin();const entry_id=v(f,"entry_id");if(!entry_id)return;const stage=v(f,"stage")||"interested";const row={entry_id,stage,primary_contact_name:v(f,"primary_contact_name"),primary_contact_email:v(f,"primary_contact_email"),internal_notes:v(f,"internal_notes"),website_assistance_status:v(f,"website_assistance_status")||"not_needed",website_project_url:v(f,"website_project_url"),updated_by:user.id,created_by:user.id};const{error}=await s.from("directory_partnerships").upsert(row,{onConflict:"entry_id"});if(error)throw new Error(error.message);if(stage==="active"){await s.from("directory_entries").update({entry_type:"official_partner",relationship_label:"Official L&F Partner"}).eq("id",entry_id)}revalidatePath("/studio/directory/partnerships");revalidatePath("/directory");}
