import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export default async function StudioGivingPage(){
 const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login?next=/studio/giving");
 const{data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();if(profile?.role!=="admin")redirect("/dashboard");
 return <main className="lfp-page pb-24"><div className="lfp-shell py-10 sm:py-14"><Link href="/studio" className="text-sm font-black text-blue-700">← Studio</Link><p className="lfp-eyebrow mt-8">Stewardship</p><h1 className="mt-3 text-4xl font-black tracking-[-.045em] sm:text-6xl">Giving should support the mission, never become the mission.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">L&F needs financial support to serve well. We can make giving easy to find and explain why it matters without interrupting Scripture, prayer, salvation, or ministry participation.</p><section className="mt-8 grid gap-4 lg:grid-cols-3"><Principle title="Visible, not dominant">Give belongs in navigation, the website journey, and appropriate ministry moments—but never above Scripture or the invitation to follow Jesus.</Principle><Principle title="Invitational, not coercive">No guilt, artificial urgency, preselected recurring gifts, or spiritual pressure. “Not reluctantly or under compulsion.” — 2 Corinthians 9:7.</Principle><Principle title="Transparent">Explain real ministry needs and actual stewardship. Never invent impact claims or imply a gift purchases a spiritual outcome.</Principle></section><section className="mt-8 rounded-[2rem] bg-[rgb(var(--lfp-ink))] p-7 text-white sm:p-9"><p className="text-xs font-black uppercase tracking-[.18em] text-sky-300">Recommended integration</p><h2 className="mt-3 text-3xl font-black">One Giving Center, surfaced gently across L&F.</h2><p className="mt-4 max-w-3xl leading-7 text-slate-300">Use a dedicated giving provider for payment processing and keep card data out of L&F. Studio should manage presentation, campaigns or designated funds only when real, receipts/provider links, and aggregate reporting. Public and app surfaces should point to the same Giving Center.</p><div className="mt-6 grid gap-3 md:grid-cols-2"><div className="rounded-2xl bg-white/10 p-5"><strong>Public website</strong><p className="mt-2 text-sm text-slate-300">Persistent Give navigation plus a calm stewardship section after the ministry story—not before it.</p></div><div className="rounded-2xl bg-white/10 p-5"><strong>L&F App</strong><p className="mt-2 text-sm text-slate-300">Support in navigation/account and occasional contextual ministry updates. No donation nags during Bible study, prayer, or salvation pathways.</p></div></div></section><section className="mt-8 lfp-card p-7"><p className="text-xs font-black uppercase tracking-widest text-blue-700">Provider decision</p><h2 className="mt-2 text-2xl font-black">Payment provider intentionally not hard-coded yet.</h2><p className="mt-3 leading-7 text-slate-600">We should compare nonprofit pricing, recurring giving, donor experience, receipts, exports/accounting, APIs/webhooks, designated funds, and payout controls before connecting money movement. Studio is now structured so the provider can be plugged in without redesigning the ministry experience.</p></section></div></main>
}
function Principle({title,children}:{title:string;children:React.ReactNode}){return <article className="lfp-card p-6"><h2 className="text-xl font-black">{title}</h2><p className="mt-3 leading-7 text-slate-600">{children}</p></article>}
