import type { EmmausContentPack } from "@/lib/emmaus/content-packs/john-1";

export const genesisOneOneToFiveContentPack: EmmausContentPack = {
  id: "genesis-1-1-5-content-pack-v1",
  title: "Genesis 1:1–5 — When God Speaks Into the Dark",
  book: "Genesis",
  chapter: 1,
  status: "reviewed",
  description: "A verse-level Emmaus discovery pack exploring creation, divine speech, the Spirit's presence, light, order, goodness, and the first day.",
  discoveries: [
    {
      id: "genesis-1-1-in-the-beginning",
      title: "Before Everything, God",
      passage: "Genesis 1:1",
      sourceNodeId: "verse-genesis-1-1",
      subtitle: "Begin where Scripture begins: not with an argument for God, but with God acting.",
      estimatedMinutes: 45,
      defaultDepth: "deep",
      skillFocus: ["observe", "context", "connect", "theology", "reflect"],
      objectives: [
        "Identify the subject, action, and scope of the opening sentence.",
        "Recognize that the verse distinguishes the Creator from creation.",
        "Explore the Hebrew terms bereshit, bara, elohim, shamayim, and erets without overstating them.",
        "Connect Genesis 1:1 with John 1:1–3, Psalm 33:6, Colossians 1:16–17, and Hebrews 11:3.",
      ],
      dialogueMoves: ["observe", "clarify", "connect", "probe", "test", "reflect", "apply", "summarize"],
      openingQuestion: "What does Genesis 1:1 place before everything else, and what does it say God did?",
      probingQuestions: [
        "What changes when you notice that God is already present before the heavens and the earth exist?",
        "What does the verb bara contribute, and what should we avoid claiming from the word alone?",
        "How does the phrase ‘the heavens and the earth’ function as a way of describing the whole created order?",
        "How do John 1:1–3 and Colossians 1:16–17 deepen—not replace—your reading of this verse?",
      ],
      clues: [
        "Separate what the verse explicitly states from later theological synthesis.",
        "Notice that creation is not divine; it is something God makes.",
        "The plural form elohim takes a singular verb here. Observe the grammar without turning it into a complete doctrine of the Trinity by itself.",
      ],
      graphConnectionIds: ["creation-god-as-creator", "creation-john-1", "creation-colossians-1", "creation-hebrews-11", "theme-beginning"],
      applicationPrompt: "Where have you allowed a created thing—success, fear, approval, money, comfort, or control—to occupy the place that belongs to the Creator?",
      journalPrompt: "Write three sentences beginning with ‘Because God is Creator…’ Support each sentence with something actually present in Genesis 1:1.",
      openingPrayer: "Creator God, quiet my assumptions and teach me to begin where Your Word begins—with You. Give me humility, attention, and wonder. Amen.",
      closingPrayer: "God of the beginning, reorder my life around the truth that all things come from You and belong to You. Amen.",
    },
    {
      id: "genesis-1-2-formless-deep-spirit",
      title: "The Spirit Over the Deep",
      passage: "Genesis 1:2",
      sourceNodeId: "verse-genesis-1-2",
      subtitle: "Explore the unformed world, the darkness, the waters, and the active presence of God's Spirit.",
      estimatedMinutes: 50,
      defaultDepth: "deep",
      skillFocus: ["observe", "context", "probe", "theology", "reflect"],
      objectives: [
        "Observe the four conditions named before God speaks light.",
        "Study tohu wabohu, tehom, and ruach elohim in context.",
        "Distinguish unformed creation from moral evil.",
        "Recognize God's presence before visible order appears.",
      ],
      dialogueMoves: ["observe", "clarify", "connect", "probe", "test", "reflect", "apply", "summarize"],
      openingQuestion: "What conditions describe the earth in verse 2, and where is God in relation to them?",
      probingQuestions: [
        "Does ‘formless and empty’ mean evil, abandoned, or unfinished? Which conclusion best fits the chapter?",
        "Why is it significant that the Spirit is present before the environment looks ordered or fruitful?",
        "What picture does the verb translated ‘hovering’ suggest when compared with Deuteronomy 32:11?",
        "How might an ancient audience hear the deep waters differently from modern readers?",
      ],
      clues: [
        "Do not automatically equate darkness in verse 2 with sin; verse 5 shows God naming the darkness Night.",
        "Ruach can mean spirit, wind, or breath. Let the phrase and wider canon guide the interpretation.",
        "The scene is unproductive and uninhabitable, but not outside God's presence or authority.",
      ],
      graphConnectionIds: ["spirit-hovering", "theme-chaos-to-order", "deuteronomy-eagle-hovering", "waters-creation", "god-present-in-darkness"],
      applicationPrompt: "What unfinished or disordered area of your life have you mistaken for evidence that God is absent?",
      journalPrompt: "Describe one place that feels ‘formless and empty.’ Then list what verse 2 allows you to affirm about God's presence before the situation changes.",
      openingPrayer: "Spirit of God, meet me in places that feel unfinished. Help me see Your presence before I see visible progress. Amen.",
      closingPrayer: "Holy Spirit, hover over what is disordered in me and prepare me to receive the Word of God with trust. Amen.",
    },
    {
      id: "genesis-1-3-let-there-be-light",
      title: "God Speaks Light",
      passage: "Genesis 1:3",
      sourceNodeId: "verse-genesis-1-3",
      subtitle: "Watch the first recorded divine command move immediately from speech to reality.",
      estimatedMinutes: 45,
      defaultDepth: "growing",
      skillFocus: ["observe", "connect", "theology", "apply"],
      objectives: [
        "Observe the command-and-fulfillment pattern.",
        "Connect divine speech with Psalm 33:6–9 and Hebrews 11:3.",
        "Distinguish created light from the later creation of the luminaries in Genesis 1:14–18.",
        "Reflect on the authority and effectiveness of God's Word.",
      ],
      dialogueMoves: ["observe", "connect", "probe", "test", "reflect", "apply", "summarize"],
      openingQuestion: "What happens between God's command and the appearance of light?",
      probingQuestions: [
        "What does the brevity of ‘and there was light’ communicate about God's authority?",
        "Why might the text introduce light before the sun, moon, and stars?",
        "How do Psalm 33:9 and 2 Corinthians 4:6 use the pattern of God speaking light?",
        "What is the difference between treating God's Word as information and receiving it as authoritative speech?",
      ],
      clues: [
        "Follow the grammar: God said → light came to be.",
        "Do not force the light to be merely symbolic; begin with its role in the created order, then trace later biblical uses.",
      ],
      graphConnectionIds: ["divine-speech-creates", "psalm-33-creation", "hebrews-11-creation", "second-corinthians-4-light", "theme-light"],
      applicationPrompt: "What clear word from God are you discussing, delaying, or negotiating instead of obeying?",
      journalPrompt: "Write one command, promise, or truth from Scripture that needs to move from information into obedient response today.",
      openingPrayer: "God who speaks, give me ears to hear and a heart ready to respond. Let Your Word bring light into my confusion. Amen.",
      closingPrayer: "Lord, where You have spoken clearly, give me courage to obey without delay. Amen.",
    },
    {
      id: "genesis-1-4-good-and-separated",
      title: "God Sees, Names, and Separates",
      passage: "Genesis 1:4",
      sourceNodeId: "verse-genesis-1-4",
      subtitle: "Discover how God's evaluation and separation begin forming an ordered world.",
      estimatedMinutes: 40,
      defaultDepth: "growing",
      skillFocus: ["observe", "context", "theology", "reflect", "apply"],
      objectives: [
        "Identify God's evaluation of the light.",
        "Understand separation as an act of ordering rather than rejection.",
        "Trace the repeated pattern of evaluation throughout Genesis 1.",
        "Reflect on the difference between God's declaration of good and personal preference.",
      ],
      dialogueMoves: ["observe", "clarify", "connect", "probe", "reflect", "apply", "summarize"],
      openingQuestion: "What two actions does God take toward the light in verse 4?",
      probingQuestions: [
        "What gives God the authority to call the light good?",
        "Why is separation necessary for order, rhythm, and life?",
        "Where else in Genesis 1 does God separate, gather, or assign boundaries?",
        "How is biblical discernment different from labeling whatever feels pleasant as good?",
      ],
      clues: [
        "Good describes fitness within God's purpose, not merely visual beauty or personal comfort.",
        "Separation creates distinction without implying that darkness is an independent rival to God.",
      ],
      graphConnectionIds: ["creation-goodness", "creation-separation", "theme-order", "discernment-good", "boundaries-life"],
      applicationPrompt: "What boundary, distinction, or separation might be necessary for greater order and faithfulness in your life?",
      journalPrompt: "Name one area where you need God's definition of good to correct your own preference or impulse.",
      openingPrayer: "Wise God, teach me to see goodness through Your purposes rather than my preferences. Amen.",
      closingPrayer: "God of order, give me wisdom to establish boundaries that protect what You call good. Amen.",
    },
    {
      id: "genesis-1-5-evening-morning-first-day",
      title: "The First Rhythm",
      passage: "Genesis 1:5",
      sourceNodeId: "verse-genesis-1-5",
      subtitle: "See God name time, establish rhythm, and complete the first day.",
      estimatedMinutes: 45,
      defaultDepth: "deep",
      skillFocus: ["observe", "context", "connect", "probe", "reflect"],
      objectives: [
        "Observe God's naming of Day and Night.",
        "Recognize naming as an expression of authority and ordered function.",
        "Examine the evening-and-morning refrain without making the age of the earth the only question in the text.",
        "Connect created rhythm with later biblical patterns of work, rest, worship, and dependence.",
      ],
      dialogueMoves: ["observe", "clarify", "connect", "probe", "test", "reflect", "apply", "summarize"],
      openingQuestion: "What does God name, and what repeated pattern closes the first day?",
      probingQuestions: [
        "What does God's naming communicate about His authority over both light and darkness?",
        "Why might the day be narrated from evening to morning?",
        "Which questions does verse 5 answer clearly, and which modern questions does it not answer by itself?",
        "How does the creation rhythm prepare for the Sabbath pattern in Genesis 2:1–3 and Exodus 20:8–11?",
      ],
      clues: [
        "Keep the literary refrain in view: evening, morning, numbered day.",
        "Acknowledge major interpretive views about the creation days without allowing the debate to eclipse the passage's central claims about God.",
      ],
      graphConnectionIds: ["creation-day-one", "theme-sacred-rhythm", "sabbath-genesis-2", "sabbath-exodus-20", "god-names"],
      applicationPrompt: "Where has your life lost a God-honoring rhythm of work, rest, worship, and dependence?",
      journalPrompt: "Design one small evening-to-morning rhythm that helps you end and begin the day under God's authority.",
      openingPrayer: "Lord of time, slow me down and teach me to receive the rhythms You establish as gifts. Amen.",
      closingPrayer: "God of every evening and morning, order my days around Your presence, purpose, and peace. Amen.",
    },
  ],
  rabbitTrails: [
    {
      id: "creation-word-spirit-light",
      title: "Word, Spirit, and Light",
      startingPassage: "Genesis 1:1–5",
      theme: "God creates and reveals",
      stops: [
        { passage: "Psalm 33:6–9", question: "How are God's Word and breath connected to creation?", purpose: "Divine speech and Spirit" },
        { passage: "John 1:1–5", question: "How does John identify the Word and connect creation, life, and light?", purpose: "Christ and creation" },
        { passage: "Colossians 1:15–17", question: "What do ‘through Him’ and ‘for Him’ add to the creation story?", purpose: "Christ-centered purpose" },
        { passage: "2 Corinthians 4:6", question: "How does Paul apply creation light to spiritual illumination?", purpose: "New creation" },
        { passage: "Revelation 21:22–25", question: "How does the Bible's final vision complete the theme of divine light?", purpose: "Creation to new creation" },
      ],
    },
    {
      id: "chaos-to-ordered-life",
      title: "From Unformed to Fruitful",
      startingPassage: "Genesis 1:2",
      theme: "God brings order and fullness",
      stops: [
        { passage: "Genesis 1:2", question: "What is unformed, empty, dark, and covered?", purpose: "Starting condition" },
        { passage: "Genesis 1:3–25", question: "How do the forming and filling movements answer verse 2?", purpose: "Literary structure" },
        { passage: "Jeremiah 4:23–26", question: "Why does Jeremiah reuse creation language to describe judgment?", purpose: "De-creation imagery" },
        { passage: "Isaiah 45:18", question: "What purpose does Isaiah give for the earth?", purpose: "Created to be inhabited" },
        { passage: "1 Corinthians 14:33,40", question: "How does God's character inform order in gathered worship?", purpose: "Responsible application" },
      ],
    },
  ],
  mentorGuide: {
    watchFor: [
      "Learner turns the passage immediately into a science debate and stops observing the text.",
      "Learner treats darkness in verse 2 as moral evil without textual support.",
      "Learner claims the plural elohim proves the Trinity by itself.",
      "Learner collects Hebrew words as trivia rather than using them to clarify the passage.",
      "Learner applies the passage vaguely without identifying a concrete response.",
    ],
    conversationPrompts: [
      "Which conclusion is explicit in the verse, and which conclusion comes from the wider canon?",
      "What did the passage say before you asked your modern question of it?",
      "Which word or repeated pattern most changed your understanding?",
      "Where do you see God present before visible change occurs?",
      "What specific act of trust, obedience, boundary, or rhythm follows from this study?",
    ],
    prayerPrompts: [
      "Pray for wonder before the Creator rather than mastery over the text.",
      "Pray for trust in God's presence within unfinished places.",
      "Pray for responsive obedience to God's Word.",
      "Pray for ordered rhythms that reflect God's wisdom.",
    ],
  },
  groupGuide: {
    sessionMinutes: 90,
    flow: [
      { segment: "Opening prayer and repeated reading", minutes: 10, instructions: "Read Genesis 1:1–5 aloud twice. On the second reading, members listen for actions attributed to God." },
      { segment: "Silent observation", minutes: 12, instructions: "Mark subjects, verbs, repeated ideas, contrasts, sequence, and questions. Do not consult notes yet." },
      { segment: "Verse-level discovery", minutes: 25, instructions: "Work through one observation question from each verse. Require answers to point to exact words in the passage." },
      { segment: "Context and Hebrew insights", minutes: 12, instructions: "Introduce only the terms that clarify the text: bereshit, bara, tohu wabohu, ruach, and the command-fulfillment pattern." },
      { segment: "Rabbit Trail", minutes: 12, instructions: "Compare Psalm 33:6–9, John 1:1–5, and 2 Corinthians 4:6. Ask what each passage contributes." },
      { segment: "Relatable scenario discussion", minutes: 8, instructions: "Discuss a season that felt dark or unfinished. Separate honest emotion from the assumption that God was absent." },
      { segment: "Personal application and journaling", minutes: 7, instructions: "Choose one response: reorder an allegiance, obey a clear word, establish a boundary, or restore a daily rhythm." },
      { segment: "Closing prayer", minutes: 4, instructions: "Pray directly from the discoveries: Creator, present Spirit, speaking God, giver of light, and Lord of time." },
    ],
    discussionQuestions: [
      "What does the passage reveal about God before it reveals anything about humanity?",
      "Which detail in verse 2 brings the most hope to an unfinished situation?",
      "What does the immediate arrival of light teach about God's Word?",
      "How can separation and boundaries serve life rather than merely restrict it?",
      "Which modern question tends to dominate discussions of Genesis 1, and what central truth can that question cause us to miss?",
      "What is one concrete response you will make this week?",
    ],
    leaderGuardrails: [
      "Keep the biblical text primary; historical, linguistic, and scientific discussions must serve observation rather than replace it.",
      "Present major creation-day interpretations fairly when raised, but do not force agreement where faithful Christians differ.",
      "Do not use Hebrew vocabulary to create certainty beyond what grammar and context support.",
      "Invite personal application without implying that every difficult circumstance will change immediately.",
      "Let participants reach conclusions through guided questions before offering summaries.",
    ],
  },
};

export function getGenesisOneOneToFiveDiscovery(id: string) {
  return genesisOneOneToFiveContentPack.discoveries.find((discovery) => discovery.id === id) ?? null;
}
