import Link from "next/link";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";

export default async function ImpactStudio(){
 const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login?next=/studio/impact");
 const{data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();if(profile?.role!=="admin")redirect("/dashboard");
 const{data:items}=await supabase.from("ministry_impact_areas").select("id,ministry_slug,title,public_message,internal_need,status,show_on_ministry,show_on_giving,show_in_app").order("sort_order").order("created_at",{ascending:false});
 return <main className="lfp-page pb-24"><div className="lfp-shell py-10 sm:py-14"><Link href="/studio" className="text-sm font-black text-blue-700">← Studio</Link><p className="lfp-eyebrow mt-8">Impact & Support</p><h1 className="mt-3 text-4xl font-black tracking-[-.045em] sm:text-6xl">Show what support makes possible.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">Studio can track operational needs privately while public messages focus on ministry: serving people, providing resources, expanding outreach, and sharing Christ. Costs stay internal unless L&amp;F intentionally publishes formal financial transparency.</p><div className="mt-7 rounded-[1.6rem] border border-amber-100 bg-amber-50/70 p-5"><p className="text-xs font-black uppercase tracking-widest text-amber-800">Public-copy guardrail</p><p className="mt-2 font-black">Describe what a gift helps L&amp;F do. Do not turn dollar amounts into spiritual outcomes or publish internal costs as appeals.</p></div><section className="mt-8 grid gap-4">{items?.length?items.map(i=><article key={i.id} className="lfp-card p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-widest text-blue-700">{i.ministry_slug.replaceAll("-"," ")} · {i.status}</p><h2 className="mt-2 text-2xl font-black">{i.title}</h2></div><div className="flex flex-wrap gap-2 text-xs font-bold text-slate-500">{i.show_on_ministry&&<span>Ministry</span>}{i.show_on_giving&&<span>Giving Center</span>}{i.show_in_app&&<span>App</span>}</div></div><p className="mt-4 leading-7 text-slate-700">{i.public_message}</p>{i.internal_need&&<div className="mt-5 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4"><p className="text-[10px] font-black uppercase tracking-widest text-slate-500">Internal only</p><p className="mt-1 text-sm text-slate-600">{i.internal_need}</p></div>}</article>):<div className="lfp-card p-7"><h2 className="text-2xl font-black">No impact messages yet.</h2><p className="mt-3 text-slate-600">The structure is ready. We can add each ministry’s approved support language as the ministries are built out.</p></div>}</section></div></main>
}