export type ContextExercise={id:string;title:string;passage:string;skill:string;question:string;choices:string[];correct:string;teaching:string;practice:string};
export const contextFoundations={
 title:"Context Foundations",
 description:"Five foundational exercises that train you to ask what kind of text you are reading, how its argument works, and what its first hearers would have understood.",
 exercises:[
 {id:"proverbs",title:"Read Wisdom as Wisdom",passage:"Proverbs 1:1–7",skill:"Genre",question:"What kind of literature is much of Proverbs?",choices:["Wisdom literature","Apocalyptic prophecy","Legal code","Narrative history"],correct:"Wisdom literature",teaching:"Proverbs trains readers in wisdom—skill for faithful living in God's world. Individual proverbs normally describe wise patterns and consequences rather than functioning as unconditional guarantees.",practice:"When a proverb sounds like a promise, ask whether the book is describing a wise pattern before treating it as a guaranteed outcome."},
 {id:"genealogy",title:"Genealogies Make Claims",passage:"Matthew 1:1–17",skill:"Identity & covenant",question:"Why were genealogies important in the biblical world?",choices:["They established identity and covenant lineage","They were only decorative","They replaced every legal record","They were secret priestly codes"],correct:"They established identity and covenant lineage",teaching:"Biblical genealogies can establish ancestry, inheritance, continuity, and covenant identity. Matthew's opening genealogy also makes a theological claim: Jesus belongs within Israel's story as son of David and son of Abraham.",practice:"Do not automatically skip a genealogy. Ask why this author placed these names here and what identity or continuity the list establishes."},
 {id:"honor-shame",title:"See the Social World",passage:"Luke 15:11–32",skill:"Culture",question:"Why can first-century honor and shame dynamics help readers understand this parable?",choices:["They clarify the social force of family actions and public responses","They change the words Jesus spoke","They make the story a strict allegory","They remove the need to read the passage"],correct:"They clarify the social force of family actions and public responses",teaching:"Family status, inheritance, public reputation, hospitality, and shame sharpen several actions in the story. Cultural context illuminates the text; it does not replace the text or authorize details the passage never states.",practice:"Use historical context to explain something actually present in the passage—not to decorate the passage with interesting facts."},
 {id:"letters",title:"Follow the Argument",passage:"Romans 1:16–17",skill:"Literary flow",question:"Why should a New Testament letter such as Romans be read as a developing argument?",choices:["Individual verses participate in a larger flow of thought","Chapter numbers were part of Paul's original manuscript","Every paragraph is independent","Paul expected readers to ignore transitions"],correct:"Individual verses participate in a larger flow of thought",teaching:"Letters develop ideas across sentences, paragraphs, and sections. Modern chapter and verse numbers are useful navigation tools, but they were added later and can tempt readers to isolate a sentence from the author's argument.",practice:"Before building a conclusion on one verse, read the paragraph before it and after it and identify connecting words such as therefore, for, but, and so."},
 {id:"apocalyptic",title:"Read Symbols in Their World",passage:"Revelation 1:1",skill:"Genre & allusion",question:"How should apocalyptic symbols normally be investigated?",choices:["Within their literary context and the Bible's earlier imagery","As modern newspaper codes by default","By assigning every detail a numerical value","As meaningless decoration"],correct:"Within their literary context and the Bible's earlier imagery",teaching:"Revelation communicates through visions, symbols, and extensive echoes of earlier Scripture. Responsible interpretation begins with the book's own literary setting and biblical allusions before jumping to modern events.",practice:"When you meet a strange image, first ask where Scripture has used similar imagery before asking what current event it might resemble."}
 ] as ContextExercise[]
};