export type IdentityOfJesusPassage = {
  id: string;
  reference: string;
  title: string;
  testament: "Old" | "New";
  role: string;
  centralClaim: string;
  observations: string[];
  connections: string[];
  questions: string[];
  misconceptions: string[];
  formation: string[];
  reviewStatus: "draft" | "reviewed" | "approved";
};

export const identityOfJesusPassages: IdentityOfJesusPassage[] = [
  {
    id: "genesis-3-15",
    reference: "Genesis 3:15",
    title: "The Promised Offspring",
    testament: "Old",
    role: "Promise",
    centralClaim: "God announces conflict between the serpent and the woman's offspring, ending with the serpent's defeat through costly victory.",
    observations: ["God speaks directly to the serpent.", "Two lines of offspring are placed in conflict.", "The serpent's head is struck while the offspring's heel is struck."],
    connections: ["Romans 16:20", "Galatians 4:4", "Hebrews 2:14", "Revelation 12"],
    questions: ["What victory and suffering are both present in the verse?", "How does later Scripture develop the identity of the promised offspring?"],
    misconceptions: ["The verse provides every detail of the gospel by itself.", "The woman's offspring experiences no suffering."],
    formation: ["Hope in God's promise", "Patience with progressive revelation"],
    reviewStatus: "reviewed",
  },
  {
    id: "exodus-3-14-15",
    reference: "Exodus 3:14–15",
    title: "I AM",
    testament: "Old",
    role: "Divine Name",
    centralClaim: "God reveals His covenant name and self-existence as He commissions Moses to deliver Israel.",
    observations: ["God identifies Himself before assigning Moses' mission.", "The divine name is tied to God's enduring memorial among His people.", "God's presence grounds Moses' obedience."],
    connections: ["John 8:58", "John 18:4–6", "Revelation 1:8"],
    questions: ["Why does God's identity matter before Moses' assignment?", "How should Jesus' use of 'I am' language be tested against this passage?"],
    misconceptions: ["Every use of 'I am' in ordinary speech is a claim to deity."],
    formation: ["Trust God's presence", "Obey from revelation rather than self-confidence"],
    reviewStatus: "reviewed",
  },
  {
    id: "psalm-2",
    reference: "Psalm 2",
    title: "The Lord's Anointed King",
    testament: "Old",
    role: "Royal Messiah",
    centralClaim: "God installs His anointed Son as King over the nations and calls rulers to submit to Him.",
    observations: ["The nations rebel against the Lord and His Anointed.", "God installs His King on Zion.", "The Son receives the nations as inheritance.", "Blessing belongs to those who take refuge in Him."],
    connections: ["Matthew 3:17", "Acts 4:25–28", "Acts 13:33", "Hebrews 1:5", "Revelation 19:15"],
    questions: ["What authority does the Son receive?", "How does refuge in the Son function within the psalm?"],
    misconceptions: ["The psalm is only about an ancient Israelite king and has no messianic development."],
    formation: ["Submit to Christ's kingship", "Take refuge in Him"],
    reviewStatus: "reviewed",
  },
  {
    id: "psalm-110",
    reference: "Psalm 110",
    title: "Priest and King",
    testament: "Old",
    role: "Priest-King",
    centralClaim: "David's Lord is enthroned by God and appointed a permanent priest after the order of Melchizedek.",
    observations: ["David calls the enthroned figure 'my Lord.'", "The figure rules amid enemies.", "Kingship and priesthood are united."],
    connections: ["Matthew 22:41–46", "Acts 2:34–36", "Hebrews 5–7", "Hebrews 10:12–13"],
    questions: ["Why does Jesus ask who David's son really is?", "What changes when priesthood and kingship meet in one person?"],
    misconceptions: ["Jesus is merely one more priest in the Levitical line."],
    formation: ["Approach Christ as both ruler and mediator"],
    reviewStatus: "reviewed",
  },
  {
    id: "isaiah-9-1-7",
    reference: "Isaiah 9:1–7",
    title: "A Child Is Born",
    testament: "Old",
    role: "Promised King",
    centralClaim: "A promised child brings light, ends oppression, bears extraordinary titles, and reigns forever on David's throne.",
    observations: ["Light enters a region of darkness.", "The child's rule brings justice and peace.", "His throne is Davidic and everlasting.", "The Lord's zeal guarantees the promise."],
    connections: ["Matthew 4:12–16", "Luke 1:32–33", "John 8:12"],
    questions: ["Which descriptions exceed what an ordinary king could sustain?", "How does Matthew use this passage?"],
    misconceptions: ["The titles can be interpreted without considering the whole passage's royal and divine language."],
    formation: ["Hope in Christ's just reign", "Walk in His light"],
    reviewStatus: "reviewed",
  },
  {
    id: "isaiah-53",
    reference: "Isaiah 52:13–53:12",
    title: "The Suffering Servant",
    testament: "Old",
    role: "Servant and Sacrifice",
    centralClaim: "The Servant suffers innocently for others, bears their guilt, is vindicated by God, and brings many into righteousness.",
    observations: ["The Servant is rejected and afflicted.", "His suffering is repeatedly described as substitutionary.", "He is silent before oppression.", "Death is followed by vindication and reward."],
    connections: ["Mark 10:45", "Luke 22:37", "Acts 8:26–35", "1 Peter 2:21–25"],
    questions: ["Which phrases show that the Servant suffers for others?", "How does the passage hold humiliation and exaltation together?"],
    misconceptions: ["The Servant's suffering is merely an example and not redemptive."],
    formation: ["Gratitude for Christ's sacrifice", "Humility under suffering"],
    reviewStatus: "reviewed",
  },
  {
    id: "daniel-7-13-14",
    reference: "Daniel 7:13–14",
    title: "The Son of Man",
    testament: "Old",
    role: "Universal Ruler",
    centralClaim: "One like a son of man comes with the clouds, approaches the Ancient of Days, and receives everlasting dominion over every people and nation.",
    observations: ["The figure is human-like yet comes with the clouds.", "He receives worshipful service from all peoples.", "His kingdom cannot be destroyed."],
    connections: ["Mark 14:61–64", "Matthew 24:30", "Revelation 1:7", "Revelation 14:14"],
    questions: ["Why is cloud-coming significant?", "What authority does Jesus claim when He applies this passage to Himself?"],
    misconceptions: ["Son of Man means only that Jesus is human and nothing more."],
    formation: ["Allegiance to Christ's universal kingdom"],
    reviewStatus: "reviewed",
  },
  {
    id: "john-1-1-18",
    reference: "John 1:1–18",
    title: "The Word Became Flesh",
    testament: "New",
    role: "Eternal Word",
    centralClaim: "The eternal divine Word creates, reveals, gives life, and becomes flesh to make God known.",
    observations: ["The Word already exists in the beginning.", "The Word is with God and is God.", "All things are made through Him.", "The Word becomes flesh and dwells among us.", "The Son makes the Father known."],
    connections: ["Genesis 1:1–3", "Colossians 1:15–17", "Hebrews 1:1–3", "Revelation 19:13"],
    questions: ["What three claims does John make in verse 1?", "How does verse 14 identify the Word?", "What does Jesus reveal about God?"],
    misconceptions: ["The Word is created.", "Jesus only became divine later.", "Original-language background can override John's own explanation."],
    formation: ["Worship Jesus", "Trust His authority", "Receive grace and truth"],
    reviewStatus: "reviewed",
  },
  {
    id: "john-8-58",
    reference: "John 8:48–59",
    title: "Before Abraham Was, I Am",
    testament: "New",
    role: "Preexistent Lord",
    centralClaim: "Jesus claims existence before Abraham and uses language that provokes an immediate charge of blasphemy.",
    observations: ["Jesus contrasts Abraham's coming into existence with His own 'I am.'", "The crowd responds by attempting to stone Him.", "The claim occurs within a dispute about Jesus' identity and the Father."],
    connections: ["Exodus 3:14", "John 1:1", "John 17:5"],
    questions: ["Why does Jesus not say 'I was'?", "How does the crowd's reaction help interpret the claim?"],
    misconceptions: ["The statement only means Jesus existed in God's plan."],
    formation: ["Receive Jesus' self-revelation rather than remaking Him"],
    reviewStatus: "reviewed",
  },
  {
    id: "john-10-22-39",
    reference: "John 10:22–39",
    title: "I and the Father Are One",
    testament: "New",
    role: "Divine Son and Shepherd",
    centralClaim: "Jesus gives eternal life, preserves His sheep with the Father, and claims unity that His opponents understand as making Himself God.",
    observations: ["Jesus gives eternal life.", "No one can seize His sheep from His or the Father's hand.", "Jesus states that He and the Father are one.", "His works are offered as evidence."],
    connections: ["Deuteronomy 32:39", "John 5:17–23", "John 14:9–11"],
    questions: ["What kind of unity is demanded by the context?", "Why does Jesus appeal to His works?"],
    misconceptions: ["The statement means only shared purpose and nothing about identity or authority."],
    formation: ["Rest in Christ's preserving power", "Evaluate claims by works and words together"],
    reviewStatus: "reviewed",
  },
  {
    id: "colossians-1-15-23",
    reference: "Colossians 1:15–23",
    title: "Christ Supreme",
    testament: "New",
    role: "Creator and Reconciler",
    centralClaim: "Christ reveals the invisible God, creates and sustains all things, leads the Church, and reconciles through His death.",
    observations: ["All things are created through and for Christ.", "He is before all things.", "All things hold together in Him.", "Creation and reconciliation meet in the same person."],
    connections: ["Genesis 1", "John 1:1–3", "Hebrews 1:1–3", "Ephesians 1:20–23"],
    questions: ["How does the passage define 'firstborn'?", "What does 'for Him' add to 'through Him'?"],
    misconceptions: ["Firstborn means Christ is the first created being."],
    formation: ["Center all of life on Christ's supremacy", "Persevere in faith"],
    reviewStatus: "reviewed",
  },
  {
    id: "hebrews-1-1-4",
    reference: "Hebrews 1:1–4",
    title: "God Has Spoken by His Son",
    testament: "New",
    role: "Final Revelation",
    centralClaim: "The Son is God's climactic revelation, creator, sustainer, exact representation, purifier, and enthroned heir.",
    observations: ["The Son stands in continuity with and superiority to prior revelation.", "He creates and sustains all things.", "He exactly represents God's being.", "He makes purification and sits at God's right hand."],
    connections: ["Psalm 110:1", "John 1:1–18", "Colossians 1:15–17"],
    questions: ["Which actions in the passage belong uniquely to God?", "How does revelation lead to atonement and enthronement?"],
    misconceptions: ["Jesus is merely God's greatest messenger."],
    formation: ["Listen to the Son", "Anchor confidence in His finished work"],
    reviewStatus: "reviewed",
  },
  {
    id: "revelation-5",
    reference: "Revelation 5",
    title: "The Lamb Is Worthy",
    testament: "New",
    role: "Slain and Victorious Lamb",
    centralClaim: "The slain Lamb alone is worthy to open God's scroll because He redeemed a kingdom of priests from every people and receives worship with God.",
    observations: ["The Lion appears as a slain Lamb.", "The Lamb's death achieves redemption.", "He receives universal worship.", "The redeemed become a kingdom and priests."],
    connections: ["Genesis 49:9–10", "Exodus 12", "Isaiah 53", "Daniel 7:13–14"],
    questions: ["Why does victory appear in the form of a slain Lamb?", "What does the worship of the Lamb reveal about His identity?"],
    misconceptions: ["Power and sacrifice are opposites in Christ."],
    formation: ["Worship the Lamb", "Embrace sacrificial faithfulness"],
    reviewStatus: "reviewed",
  },
  {
    id: "revelation-19-11-16",
    reference: "Revelation 19:11–16",
    title: "King of Kings",
    testament: "New",
    role: "Returning King",
    centralClaim: "Jesus returns as faithful judge, the Word of God, ruler of nations, and King of kings.",
    observations: ["He is called Faithful and True.", "His name includes the Word of God.", "He judges and wages war in righteousness.", "His kingship is supreme."],
    connections: ["Psalm 2", "Isaiah 11:1–5", "John 1:1", "Revelation 5"],
    questions: ["How does the Word title connect the Gospel of John and Revelation?", "How are justice and faithfulness joined in His return?"],
    misconceptions: ["The returning Christ is disconnected from the crucified Lamb."],
    formation: ["Live under Christ's present authority", "Hope in His righteous return"],
    reviewStatus: "reviewed",
  },
];

export const identityOfJesusPathway = {
  id: "identity-of-jesus",
  title: "Identity of Jesus",
  drivingQuestion: "Who is Jesus?",
  purpose: "Trace how Scripture progressively reveals Jesus as promised offspring, divine Lord, Messiah, Servant, Son of Man, eternal Word, Creator, Priest, Lamb, and returning King.",
  passages: identityOfJesusPassages,
  openingPrayer: "Father, open our eyes to see Jesus faithfully across Your Word. Guard us from reducing Him to our assumptions. Teach us to observe carefully, connect responsibly, worship humbly, and obey fully. Amen.",
  closingPrayer: "Lord Jesus, You are the promised One, eternal Word, suffering Servant, risen Lord, worthy Lamb, and reigning King. Deepen our trust, worship, and allegiance as we continue to know You through Scripture. Amen.",
};
