"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type PathRow={id:string;path_key:string;title:string;subtitle:string|null;description:string;learning_objective:string;mode:string;difficulty:string;completion_xp:number;estimated_minutes:number};
type StepRow={id:string;step_key:string;graph_node_id:string;position:number;step_type:string;observation_prompt:string|null;connection_prompt:string|null;reflection_prompt:string|null;journaling_prompt:string|null;xp_reward:number;is_completion_required:boolean};
type NodeRow={id:string;title:string;node_type:string;scripture_reference:string|null;summary:string|null};
type SessionRow={id:string;current_step_key:string|null;earned_xp:number;status:"active"|"completed"|"abandoned"};
type ProgressRow={step_id:string;observation_response:string|null;connection_response:string|null;reflection_response:string|null;journal_entry:string|null;prayer_response:string|null;completed:boolean;xp_awarded:number};

export default function EmmausWalkExperience({path,steps,nodes,userId}:{path:PathRow;steps:StepRow[];nodes:NodeRow[];userId:string}){
 const supabase=useMemo(()=>createClient(),[]),router=useRouter();
 const[session,setSession]=useState<SessionRow|null>(null),[progress,setProgress]=useState<Record<string,ProgressRow>>({}),[currentIndex,setCurrentIndex]=useState(0),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const[answers,setAnswers]=useState({observation:"",connection:"",reflection:"",journal:"",prayer:""});
 const currentStep=steps[currentIndex],currentNode=nodes.find(n=>n.id===currentStep?.graph_node_id),completedCount=Object.values(progress).filter(p=>p.completed).length,percent=steps.length?Math.round((completedCount/steps.length)*100):0;

 useEffect(()=>{void initialize()},[]);
 useEffect(()=>{if(!currentStep)return;const saved=progress[currentStep.id];setAnswers({observation:saved?.observation_response??"",connection:saved?.connection_response??"",reflection:saved?.reflection_response??"",journal:saved?.journal_entry??"",prayer:saved?.prayer_response??""})},[currentStep?.id,progress]);

 async function initialize(){setLoading(true);const{data:existing}=await supabase.from("emmaus_walk_sessions").select("id,current_step_key,earned_xp,status").eq("user_id",userId).eq("path_id",path.id).maybeSingle();let active=existing as SessionRow|null;if(!active){const{data,error}=await supabase.from("emmaus_walk_sessions").insert({user_id:userId,path_id:path.id,current_step_key:steps[0]?.step_key??null,status:"active"}).select("id,current_step_key,earned_xp,status").single();if(error){setMessage(error.message);setLoading(false);return}active=data as SessionRow}setSession(active);const{data:rows}=await supabase.from("emmaus_walk_step_progress").select("step_id,observation_response,connection_response,reflection_response,journal_entry,prayer_response,completed,xp_awarded").eq("session_id",active.id);const map=Object.fromEntries(((rows??[]) as ProgressRow[]).map(r=>[r.step_id,r]));setProgress(map);const index=Math.max(0,steps.findIndex(s=>s.step_key===active?.current_step_key));setCurrentIndex(index);setLoading(false)}

 async function saveCurrent(complete=false){if(!session||!currentStep)return;setSaving(true);const existing=progress[currentStep.id];const xp=complete&&!existing?.completed?currentStep.xp_reward:(existing?.xp_awarded??0);const payload={session_id:session.id,step_id:currentStep.id,observation_response:answers.observation||null,connection_response:answers.connection||null,reflection_response:answers.reflection||null,journal_entry:answers.journal||null,prayer_response:answers.prayer||null,completed:complete||existing?.completed||false,xp_awarded:xp,completed_at:complete?new Date().toISOString():null,updated_at:new Date().toISOString()};const{error}=await supabase.from("emmaus_walk_step_progress").upsert(payload,{onConflict:"session_id,step_id"});if(error){setMessage(error.message);setSaving(false);return}const nextProgress={...progress,[currentStep.id]:{step_id:currentStep.id,observation_response:payload.observation_response,connection_response:payload.connection_response,reflection_response:payload.reflection_response,journal_entry:payload.journal_entry,prayer_response:payload.prayer_response,completed:payload.completed,xp_awarded:xp}};setProgress(nextProgress);let earned=Object.values(nextProgress).reduce((sum,p)=>sum+p.xp_awarded,0);let nextIndex=currentIndex;if(complete){nextIndex=Math.min(currentIndex+1,steps.length-1)}const finished=complete&&currentIndex===steps.length-1;const{error:sessionError}=await supabase.from("emmaus_walk_sessions").update({current_step_key:finished?currentStep.step_key:steps[nextIndex]?.step_key??currentStep.step_key,earned_xp:earned,status:finished?"completed":"active",last_activity_at:new Date().toISOString(),completed_at:finished?new Date().toISOString():null}).eq("id",session.id);if(sessionError){setMessage(sessionError.message);setSaving(false);return}setSession({...session,earned_xp:earned,status:finished?"completed":"active",current_step_key:finished?currentStep.step_key:steps[nextIndex]?.step_key??currentStep.step_key});setSaving(false);if(finished){setMessage(`Path complete! You earned ${earned+path.completion_xp} XP.`)}else if(complete){setCurrentIndex(nextIndex);setMessage(`Step complete. +${currentStep.xp_reward} XP`)}else setMessage("Progress saved.")}

 if(loading)return <div className="rounded-[2rem] border border-slate-200 bg-white p-8 text-center font-black text-slate-500 shadow-xl">Preparing your walk...</div>;
 if(!currentStep||!currentNode)return <div className="rounded-[2rem] border border-rose-200 bg-rose-50 p-8 text-center font-black text-rose-700">This path has no playable steps yet.</div>;

 return <div className="mx-auto max-w-5xl space-y-6">
  <section className="overflow-hidden rounded-[2rem] bg-slate-950 p-6 text-white shadow-2xl sm:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.18em] text-amber-300">Emmaus Walk</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">{path.title}</h1><p className="mt-3 text-indigo-100/70">{path.learning_objective}</p></div><div className="rounded-2xl border border-white/10 bg-white/10 px-5 py-4 text-center"><p className="text-3xl font-black">{session?.earned_xp??0}</p><p className="text-[10px] font-black uppercase tracking-widest text-indigo-200">XP earned</p></div></div><div className="mt-7"><div className="flex justify-between text-xs font-black uppercase tracking-wide text-indigo-200"><span>Step {currentIndex+1} of {steps.length}</span><span>{percent}% complete</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-amber-300 transition-all" style={{width:`${percent}%`}}/></div></div></section>

  <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-xl sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-indigo-700">{currentStep.step_type} discovery</p><h2 className="mt-2 text-3xl font-black text-slate-950">{currentNode.title}</h2><p className="mt-2 text-lg font-black text-indigo-700">{currentNode.scripture_reference??currentNode.node_type.replaceAll("_"," ")}</p></div><span className="rounded-full bg-indigo-50 px-4 py-2 text-sm font-black text-indigo-700">+{currentStep.xp_reward} XP</span></div>{currentNode.summary&&<div className="mt-6 rounded-3xl border border-indigo-100 bg-indigo-50 p-5"><p className="text-xs font-black uppercase tracking-wide text-indigo-700">Context</p><p className="mt-2 leading-7 text-slate-700">{currentNode.summary}</p></div>}
  <div className="mt-7 space-y-5"><Prompt label="Observe" prompt={currentStep.observation_prompt} value={answers.observation} onChange={v=>setAnswers({...answers,observation:v})}/><Prompt label="Connect" prompt={currentStep.connection_prompt} value={answers.connection} onChange={v=>setAnswers({...answers,connection:v})}/><Prompt label="Reflect" prompt={currentStep.reflection_prompt} value={answers.reflection} onChange={v=>setAnswers({...answers,reflection:v})}/><Prompt label="Journal" prompt={currentStep.journaling_prompt} value={answers.journal} onChange={v=>setAnswers({...answers,journal:v})}/><Prompt label="Prayer" prompt="Turn what you discovered into a personal prayer." value={answers.prayer} onChange={v=>setAnswers({...answers,prayer:v})}/></div>
  <div className="mt-8 flex flex-wrap items-center justify-between gap-3"><button type="button" disabled={currentIndex===0||saving} onClick={()=>setCurrentIndex(i=>Math.max(0,i-1))} className="rounded-full border border-slate-300 px-5 py-3 font-black text-slate-700 disabled:opacity-40">← Previous</button><div className="flex gap-3"><button type="button" disabled={saving} onClick={()=>void saveCurrent(false)} className="rounded-full border border-indigo-300 bg-indigo-50 px-5 py-3 font-black text-indigo-700">Save</button><button type="button" disabled={saving||!answers.observation.trim()} onClick={()=>void saveCurrent(true)} className="rounded-full bg-indigo-600 px-6 py-3 font-black text-white disabled:opacity-50">{currentIndex===steps.length-1?"Complete Path":"Complete Step →"}</button></div></div><p className="mt-5 min-h-6 text-sm font-bold text-slate-500" aria-live="polite">{message}</p></section>
  {session?.status==="completed"&&<section className="rounded-[2rem] border border-emerald-200 bg-emerald-50 p-8 text-center shadow-xl"><p className="text-sm font-black uppercase tracking-widest text-emerald-700">Journey Complete</p><h2 className="mt-3 text-4xl font-black text-emerald-950">You finished {path.title}.</h2><p className="mt-3 text-emerald-900/70">Your responses, journal entries, prayer, and XP have been saved.</p><button onClick={()=>router.push("/emmaus/walk")} className="mt-6 rounded-full bg-emerald-700 px-6 py-3 font-black text-white">Choose another path</button></section>}
 </div>;
}
function Prompt({label,prompt,value,onChange}:{label:string;prompt:string|null;value:string;onChange:(value:string)=>void}){if(!prompt)return null;return <label className="block"><span className="text-xs font-black uppercase tracking-[0.14em] text-indigo-700">{label}</span><p className="mt-2 text-lg font-black leading-7 text-slate-950">{prompt}</p><textarea value={value} onChange={e=>onChange(e.target.value)} rows={4} className="mt-3 w-full rounded-2xl border border-slate-300 bg-slate-50 px-4 py-3 text-slate-950 outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100"/></label>}
