"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type TranslationCode="KJV"|"WEB";
type ProgressRow={book_key:string;book_name:string;abbreviation?:string;testament:"old"|"new";canonical_order:number;chapter_count:number;imported_chapters:number;imported_verses:number;enriched_verses:number;graph_edges:number;pending_enrichment:number;chapter_percent:number;enrichment_percent:number};
type ImportBatch={id:string;book_key:string;chapter_start:number;chapter_end:number;translation:string;imported_verse_count:number;status:string;completed_at:string|null;created_at:string};

export default function EmmausCommandCenter(){
 const supabase=useMemo(()=>createClient(),[]);
 const[translation,setTranslation]=useState<TranslationCode>("KJV"),[rows,setRows]=useState<ProgressRow[]>([]),[batches,setBatches]=useState<ImportBatch[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 async function load(){setLoading(true);setMessage("");const[{data:progress,error:progressError},{data:recent,error:recentError}]=await Promise.all([supabase.rpc("get_emmaus_bible_progress",{p_translation:translation}),supabase.from("emmaus_scripture_import_batches").select("id,book_key,chapter_start,chapter_end,translation,imported_verse_count,status,completed_at,created_at").eq("translation",translation).order("created_at",{ascending:false}).limit(8)]);if(progressError){setMessage(progressError.message);setLoading(false);return}if(recentError)setMessage(recentError.message);setRows((progress??[]) as ProgressRow[]);setBatches((recent??[]) as ImportBatch[]);setLoading(false)}
 useEffect(()=>{void load()},[translation]);
 const totals=rows.reduce((acc,row)=>({books:acc.books+(row.imported_chapters>0?1:0),chapters:acc.chapters+row.imported_chapters,chapterTotal:acc.chapterTotal+row.chapter_count,verses:acc.verses+row.imported_verses,enriched:acc.enriched+row.enriched_verses,edges:acc.edges+row.graph_edges,pending:acc.pending+row.pending_enrichment}),{books:0,chapters:0,chapterTotal:0,verses:0,enriched:0,edges:0,pending:0});
 const chapterPercent=totals.chapterTotal?Math.floor(totals.chapters/totals.chapterTotal*100):0;
 const enrichmentPercent=totals.verses?Math.floor(totals.enriched/totals.verses*100):0;
 const priority=[...rows].filter(row=>row.chapter_percent<100||row.pending_enrichment>0).sort((a,b)=>{const aStarted=a.imported_chapters>0?0:1,bStarted=b.imported_chapters>0?0:1;return aStarted-bStarted||b.pending_enrichment-a.pending_enrichment||a.canonical_order-b.canonical_order})[0]??rows[0];
 const nextChapter=priority?Math.min(priority.chapter_count,priority.imported_chapters+1):1;
 const oldRows=rows.filter(row=>row.testament==="old"),newRows=rows.filter(row=>row.testament==="new");
 if(loading)return <div className="rounded-[2rem] border border-slate-200 bg-white p-10 text-center font-black text-slate-500 shadow-xl">Loading Emmaus Command Center...</div>;
 return <div className="space-y-6">
  <header className="overflow-hidden rounded-[2rem] bg-slate-950 p-7 text-white shadow-2xl sm:p-9"><div className="flex flex-wrap items-start justify-between gap-6"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-amber-300">The Lost and Found Project</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">Emmaus Command Center</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-indigo-100/70">Track the biblical corpus, semantic graph, and enrichment workload across the entire canon.</p></div><select value={translation} onChange={e=>setTranslation(e.target.value as TranslationCode)} className="rounded-full border border-white/15 bg-white/10 px-5 py-3 font-black text-white outline-none"><option className="text-slate-950" value="KJV">KJV</option><option className="text-slate-950" value="WEB">WEB</option></select></div></header>
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><Metric value={`${chapterPercent}%`} label="Bible imported"/><Metric value={totals.verses.toLocaleString()} label="Verses"/><Metric value={totals.books} label="Books started"/><Metric value={totals.edges.toLocaleString()} label="Relationships"/><Metric value={`${enrichmentPercent}%`} label="Verses enriched"/><Metric value={totals.pending.toLocaleString()} label="Tasks pending"/></section>
  {priority&&<section className="grid gap-5 rounded-[2rem] border border-amber-200 bg-amber-50 p-6 shadow-xl lg:grid-cols-[1fr_auto]"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-700">Current priority</p><h2 className="mt-2 text-3xl font-black text-amber-950">{priority.book_name} {nextChapter}</h2><p className="mt-3 text-slate-700">{priority.imported_chapters} of {priority.chapter_count} chapters imported · {priority.pending_enrichment} enrichment tasks pending.</p><div className="mt-4 h-3 overflow-hidden rounded-full bg-amber-100"><div className="h-full rounded-full bg-amber-500" style={{width:`${priority.chapter_percent}%`}}/></div></div><div className="flex items-center"><Link href={`/emmaus/admin/import?book=${encodeURIComponent(priority.book_name)}&chapter=${nextChapter}&translation=${translation}`} className="rounded-full bg-slate-950 px-6 py-3 font-black text-white">Continue building →</Link></div></section>}
  <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-indigo-700">Canon heat map</p><h2 className="mt-1 text-3xl font-black text-slate-950">66-book progress</h2></div><Link href="/emmaus/admin/import" className="rounded-full border border-indigo-300 bg-indigo-50 px-5 py-3 font-black text-indigo-700">Open Bible Builder</Link></div><Testament title="Old Testament" rows={oldRows} translation={translation}/><Testament title="New Testament" rows={newRows} translation={translation}/></section>
  <div className="grid gap-6 xl:grid-cols-[1fr_420px]"><section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-xl"><p className="text-xs font-black uppercase tracking-[0.16em] text-indigo-700">Book-by-book production</p><div className="mt-5 space-y-3">{rows.filter(row=>row.imported_chapters>0||row.pending_enrichment>0).map(row=><article key={row.book_key} className="grid gap-4 rounded-2xl border border-slate-200 bg-slate-50 p-4 md:grid-cols-[180px_1fr_150px]"><div><p className="font-black text-slate-950">{row.book_name}</p><p className="mt-1 text-xs font-black uppercase text-slate-400">{row.testament} testament</p></div><div><div className="flex justify-between text-xs font-black text-slate-500"><span>{row.imported_chapters}/{row.chapter_count} chapters</span><span>{row.chapter_percent}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-indigo-600" style={{width:`${row.chapter_percent}%`}}/></div><p className="mt-2 text-xs text-slate-500">{row.imported_verses} verses · {row.enriched_verses} enriched · {row.graph_edges} relationships</p></div><div className="md:text-right"><p className="font-black text-amber-700">{row.pending_enrichment}</p><p className="text-xs font-black uppercase text-slate-400">tasks pending</p></div></article>)}</div></section>
  <aside className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-xl"><p className="text-xs font-black uppercase tracking-[0.16em] text-indigo-700">Recent imports</p><div className="mt-5 space-y-3">{batches.length?batches.map(batch=><article key={batch.id} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between gap-4"><p className="font-black text-slate-950">{titleCase(batch.book_key)} {batch.chapter_start===batch.chapter_end?batch.chapter_start:`${batch.chapter_start}-${batch.chapter_end}`}</p><span className={`rounded-full px-3 py-1 text-xs font-black ${batch.status==="verified"||batch.status==="complete"?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>{batch.status}</span></div><p className="mt-2 text-sm text-slate-600">{batch.imported_verse_count} verses · {batch.translation}</p><p className="mt-2 text-xs text-slate-400">{formatDate(batch.completed_at??batch.created_at)}</p></article>):<p className="text-sm text-slate-500">No import batches yet.</p>}</div></aside></div>
  <p className="min-h-5 text-sm font-bold text-slate-500">{message}</p>
 </div>
}

function Metric({value,label}:{value:string|number;label:string}){return <div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 text-center shadow-lg"><p className="text-3xl font-black text-slate-950">{value}</p><p className="mt-2 text-[10px] font-black uppercase tracking-widest text-slate-500">{label}</p></div>}
function Testament({title,rows,translation}:{title:string;rows:ProgressRow[];translation:string}){return <div className="mt-7"><p className="mb-3 text-sm font-black uppercase tracking-[0.14em] text-slate-500">{title}</p><div className="grid grid-cols-4 gap-2 sm:grid-cols-7 md:grid-cols-10 lg:grid-cols-13">{rows.map(row=><Link key={row.book_key} title={`${row.book_name}: ${row.chapter_percent}% imported, ${row.enrichment_percent}% enriched`} href={`/emmaus/admin/import?book=${encodeURIComponent(row.book_name)}&chapter=${Math.min(row.chapter_count,row.imported_chapters+1)}&translation=${translation}`} className={`flex aspect-square items-center justify-center rounded-xl border text-xs font-black transition hover:-translate-y-0.5 ${heatClass(row.chapter_percent)}`}>{row.abbreviation??shortName(row.book_name)}</Link>)}</div></div>}
function heatClass(percent:number){if(percent===100)return"border-emerald-500 bg-emerald-500 text-white";if(percent>=50)return"border-indigo-400 bg-indigo-400 text-white";if(percent>0)return"border-amber-300 bg-amber-200 text-amber-950";return"border-slate-200 bg-slate-50 text-slate-400"}
function shortName(name:string){return name.replace(/\s+/g,"").slice(0,3)}
function titleCase(value:string){return value.split("-").map(part=>part.charAt(0).toUpperCase()+part.slice(1)).join(" ")}
function formatDate(value:string){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value))}
