"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Message={id:string;role:"companion"|"learner";message_type:"question"|"response"|"nudge"|"cross_reference"|"context"|"insight";content:string;created_at:string};
type NodeContext={id:string;title:string;node_type:string;scripture_reference:string|null;summary:string|null};
type StepContext={id:string;observation_prompt:string|null;connection_prompt:string|null;reflection_prompt:string|null};
type GraphConnection={relationship_key:string;explanation:string|null;related_title:string;related_type:string;related_reference:string|null};

export default function EmmausCompanionPanel({sessionId,step,node}:{sessionId:string;step:StepContext;node:NodeContext}){
 const supabase=useMemo(()=>createClient(),[]);
 const[messages,setMessages]=useState<Message[]>([]),[connections,setConnections]=useState<GraphConnection[]>([]),[draft,setDraft]=useState(""),[open,setOpen]=useState(true),[working,setWorking]=useState(false),[message,setMessage]=useState("");
 async function loadConnections(){const{data:edges}=await supabase.from("emmaus_graph_edges").select("source_node_id,target_node_id,relationship_key,explanation").or(`source_node_id.eq.${node.id},target_node_id.eq.${node.id}`).neq("status","archived").limit(12);if(!edges?.length){setConnections([]);return}const relatedIds=[...new Set(edges.map((e:any)=>e.source_node_id===node.id?e.target_node_id:e.source_node_id))];const{data:related}=await supabase.from("emmaus_graph_nodes").select("id,title,node_type,scripture_reference").in("id",relatedIds);const byId=Object.fromEntries((related??[]).map((n:any)=>[n.id,n]));setConnections(edges.map((e:any)=>{const id=e.source_node_id===node.id?e.target_node_id:e.source_node_id,n=byId[id];return{relationship_key:e.relationship_key,explanation:e.explanation,related_title:n?.title??"Connected node",related_type:n?.node_type??"concept",related_reference:n?.scripture_reference??null}}))}
 async function loadConversation(){const{data,error}=await supabase.from("emmaus_companion_messages").select("id,role,message_type,content,created_at").eq("session_id",sessionId).eq("step_id",step.id).order("created_at");if(error)return setMessage(error.message);const loaded=(data??[]) as Message[];if(loaded.length)return setMessages(loaded);const opening=buildOpeningQuestion(step,node);const{data:created,error:createError}=await supabase.from("emmaus_companion_messages").insert({session_id:sessionId,step_id:step.id,role:"companion",message_type:"question",content:opening,metadata:{generator:"graph-aware-companion-v2"}}).select("id,role,message_type,content,created_at").single();if(createError)return setMessage(createError.message);setMessages([created as Message])}
 useEffect(()=>{void Promise.all([loadConversation(),loadConnections()])},[sessionId,step.id,node.id]);
 async function sendLearnerMessage(){const content=draft.trim();if(!content)return;setWorking(true);setDraft("");const{data:learner,error}=await supabase.from("emmaus_companion_messages").insert({session_id:sessionId,step_id:step.id,role:"learner",message_type:"response",content}).select("id,role,message_type,content,created_at").single();if(error){setMessage(error.message);setWorking(false);return}const next=buildFollowUpQuestion(content,messages.length,step,node,connections);const{data:companion,error:companionError}=await supabase.from("emmaus_companion_messages").insert({session_id:sessionId,step_id:step.id,role:"companion",message_type:"question",content:next,metadata:{generator:"graph-aware-companion-v2",connection_count:connections.length}}).select("id,role,message_type,content,created_at").single();setMessages(c=>companionError?[...c,learner as Message]:[...c,learner as Message,companion as Message]);if(companionError)setMessage(companionError.message);setWorking(false)}
 async function requestHelp(type:"nudge"|"cross_reference"|"context"|"insight"){setWorking(true);const content=buildHelpMessage(type,step,node,messages,connections);const{data,error}=await supabase.from("emmaus_companion_messages").insert({session_id:sessionId,step_id:step.id,role:"companion",message_type:type,content,metadata:{generator:"graph-aware-companion-v2",connection_count:connections.length}}).select("id,role,message_type,content,created_at").single();if(error)setMessage(error.message);else setMessages(c=>[...c,data as Message]);setWorking(false)}
 return <section className="overflow-hidden rounded-[2rem] border border-indigo-200 bg-white shadow-xl"><button type="button" onClick={()=>setOpen(v=>!v)} className="flex w-full items-center justify-between gap-4 bg-gradient-to-r from-indigo-700 to-violet-700 px-6 py-5 text-left text-white"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-300">Study Companion</p><h2 className="mt-1 text-2xl font-black">Discover before you reveal.</h2><p className="mt-1 text-xs text-indigo-100/60">{connections.length} graph connections available for this step</p></div><span className="text-2xl">{open?"−":"+"}</span></button>{open&&<div className="p-5 sm:p-6"><div className="max-h-[420px] space-y-4 overflow-auto rounded-2xl bg-slate-50 p-4">{messages.map(item=><div key={item.id} className={`max-w-[88%] rounded-2xl px-4 py-3 ${item.role==="learner"?"ml-auto bg-indigo-600 text-white":"bg-white text-slate-800 shadow-sm"}`}><p className="text-[10px] font-black uppercase tracking-wide opacity-60">{item.role==="learner"?"You":labelForType(item.message_type)}</p><p className="mt-1 leading-7">{item.content}</p></div>)}</div><div className="mt-4 flex flex-wrap gap-2"><button disabled={working} onClick={()=>void requestHelp("nudge")} className={helpButton}>Give me a nudge</button><button disabled={working} onClick={()=>void requestHelp("cross_reference")} className={helpButton}>Graph connection</button><button disabled={working} onClick={()=>void requestHelp("context")} className={helpButton}>Context</button><button disabled={working||messages.filter(m=>m.role==="learner").length<1} onClick={()=>void requestHelp("insight")} className={helpButton}>Reveal insight</button></div><div className="mt-4 flex gap-3"><textarea value={draft} onChange={e=>setDraft(e.target.value)} rows={3} placeholder="Share what you notice or ask for another question..." className="min-w-0 flex-1 rounded-2xl border border-slate-300 bg-white px-4 py-3 text-slate-950 outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100"/><button disabled={working||!draft.trim()} onClick={()=>void sendLearnerMessage()} className="self-end rounded-2xl bg-indigo-600 px-5 py-3 font-black text-white disabled:opacity-50">Send</button></div><p className="mt-3 min-h-5 text-xs font-bold text-slate-500">{message}</p></div>}</section>;
}
function buildOpeningQuestion(step:StepContext,node:NodeContext){return step.observation_prompt??`Before looking for an explanation, what stands out to you about ${node.title}${node.scripture_reference?` in ${node.scripture_reference}`:""}?`}
function buildFollowUpQuestion(response:string,count:number,step:StepContext,node:NodeContext,connections:GraphConnection[]){const lower=response.toLowerCase();if(count<3)return"What in the text or context led you to that observation?";if(lower.includes("god")||lower.includes("jesus")||lower.includes("lord"))return"What does that observation suggest about God's character or actions?";if(connections.length){const c=connections[count%connections.length];return`Emmaus connects this step to ${c.related_title}${c.related_reference?` (${c.related_reference})`:""} through “${c.relationship_key.replaceAll("_"," ")}.” What connection do you see before reading an explanation?`;}return step.connection_prompt??step.reflection_prompt??`How might ${node.title} connect to another passage, promise, person, or event you already know?`}
function buildHelpMessage(type:"nudge"|"cross_reference"|"context"|"insight",step:StepContext,node:NodeContext,messages:Message[],connections:GraphConnection[]){if(type==="nudge")return`Look again at the key nouns, verbs, repeated ideas, and contrasts connected to ${node.title}. Which one seems most important, and why?`;if(type==="cross_reference"){const c=connections[0];return c?`Follow this graph connection: ${node.title} → ${c.relationship_key.replaceAll("_"," ")} → ${c.related_title}${c.related_reference?` (${c.related_reference})`:""}. Compare the two before deciding what the relationship means.`:`No reviewed graph connection is available yet. Search for another passage that repeats the main wording or theme.`}if(type==="context")return node.summary?`Context clue: ${node.summary} Now identify which detail changes or strengthens your first observation.`:"Identify the speaker, audience, setting, and what happens immediately before and after this passage or concept.";const c=connections.find(x=>x.explanation);const learner=messages.filter(m=>m.role==="learner").slice(-2).map(m=>m.content).join(" | ");return c?`Possible insight: ${c.explanation} Compare that reviewed connection with your observations${learner?`: ${learner}`:""}. What evidence supports or challenges it?`:`Possible insight: understand ${node.title} by combining its wording, immediate context, and place in the larger story of Scripture. What evidence supports or challenges that reading?`}
function labelForType(type:Message["message_type"]){return type==="nudge"?"Nudge":type==="cross_reference"?"Graph connection":type==="context"?"Context":type==="insight"?"Insight":"Emmaus Companion"}
const helpButton="rounded-full border border-indigo-200 bg-indigo-50 px-4 py-2 text-xs font-black text-indigo-700 disabled:opacity-40";
