"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type NodeRow={id:string;node_key:string;node_type:string;title:string;subtitle:string|null;scripture_reference:string|null;summary:string|null;status:"draft"|"reviewed"|"published"|"archived";metadata:Record<string,unknown>|null};
type EdgeRow={id:string;source_node_id:string;target_node_id:string;relationship_key:string;explanation:string|null;confidence_score:number;confidence_class:string;evidence_summary:string|null;interpretive_notes:string|null;status:"draft"|"reviewed"|"published"|"archived"};
type Relationship={key:string;label:string;is_directional?:boolean};
type Position={x:number;y:number};
type PositionSnapshot=Record<string,Position>;
type DragState={anchorId:string;startX:number;startY:number;originals:PositionSnapshot};

const NODE_WIDTH=220,NODE_HEIGHT=116,GRID_SIZE=24;
const nodeTypes=["verse","passage","book","person","place","event","theme","doctrine","attribute","language_term","command","promise","question","discipline","life_topic","discovery","rabbit_trail"];

export default function FounderGraphBuilder(){
 const supabase=useMemo(()=>createClient(),[]),viewportRef=useRef<HTMLDivElement>(null),canvasRef=useRef<HTMLDivElement>(null),dragStartSnapshot=useRef<PositionSnapshot|null>(null);
 const [nodes,setNodes]=useState<NodeRow[]>([]),[edges,setEdges]=useState<EdgeRow[]>([]),[relationships,setRelationships]=useState<Relationship[]>([]),[positions,setPositions]=useState<PositionSnapshot>({}),[undoStack,setUndoStack]=useState<PositionSnapshot[]>([]),[redoStack,setRedoStack]=useState<PositionSnapshot[]>([]);
 const [snapToGrid,setSnapToGrid]=useState(true),[selectedNodeIds,setSelectedNodeIds]=useState<string[]>([]),[selectedEdgeId,setSelectedEdgeId]=useState<string|null>(null),[connectSource,setConnectSource]=useState<string|null>(null),[dragging,setDragging]=useState<DragState|null>(null),[panning,setPanning]=useState<{x:number;y:number;left:number;top:number}|null>(null);
 const [message,setMessage]=useState(""),[saving,setSaving]=useState(false),[search,setSearch]=useState(""),[typeFilter,setTypeFilter]=useState("all"),[statusFilter,setStatusFilter]=useState("active"),[zoom,setZoom]=useState(1);
 const [nodeDraft,setNodeDraft]=useState({node_key:"",node_type:"theme",title:"",subtitle:"",scripture_reference:"",summary:"",status:"draft" as NodeRow["status"]});
 const [edgeDraft,setEdgeDraft]=useState({relationship_key:"develops_theme",explanation:"",confidence_score:70,status:"draft" as EdgeRow["status"]});
 const selectedNodeId=selectedNodeIds.length===1?selectedNodeIds[0]:null;

 useEffect(()=>{void loadGraph()},[]);
 useEffect(()=>{const handleKey=(event:KeyboardEvent)=>{const target=event.target as HTMLElement|null;if(target?.tagName==="INPUT"||target?.tagName==="TEXTAREA"||target?.tagName==="SELECT")return;if(event.key==="Escape"){setConnectSource(null);setSelectedNodeIds([]);setSelectedEdgeId(null)}if((event.key==="Delete"||event.key==="Backspace")&&(selectedNodeIds.length||selectedEdgeId)){event.preventDefault();void deleteSelected()}if((event.metaKey||event.ctrlKey)&&event.key==="0"){event.preventDefault();setZoom(1)}if((event.metaKey||event.ctrlKey)&&event.key==="+"){event.preventDefault();setZoom(v=>Math.min(1.5,Number((v+.1).toFixed(1))))}if((event.metaKey||event.ctrlKey)&&event.key==="-"){event.preventDefault();setZoom(v=>Math.max(.5,Number((v-.1).toFixed(1))))}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="z"){event.preventDefault();if(event.shiftKey)void redoLayout();else void undoLayout()}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="y"){event.preventDefault();void redoLayout()}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="a"){event.preventDefault();setSelectedNodeIds(visibleNodes.map(n=>n.id));setSelectedEdgeId(null)}};window.addEventListener("keydown",handleKey);return()=>window.removeEventListener("keydown",handleKey)},[selectedNodeIds,selectedEdgeId,undoStack,redoStack,positions,nodes,search,typeFilter,statusFilter]);

 async function loadGraph(){const[{data:nodeRows},{data:edgeRows},{data:relationRows}]=await Promise.all([supabase.from("emmaus_graph_nodes").select("id,node_key,node_type,title,subtitle,scripture_reference,summary,status,metadata").order("title"),supabase.from("emmaus_graph_edges").select("id,source_node_id,target_node_id,relationship_key,explanation,confidence_score,confidence_class,evidence_summary,interpretive_notes,status"),supabase.from("emmaus_relationship_types").select("key,label,is_directional").order("sort_order")]);const loaded=(nodeRows??[]) as NodeRow[];setNodes(loaded);setEdges((edgeRows??[]) as EdgeRow[]);setRelationships((relationRows??[]) as Relationship[]);setPositions(Object.fromEntries(loaded.map((node,index)=>{const m=node.metadata??{};return[node.id,{x:typeof m.canvas_x==="number"?m.canvas_x:60+(index%4)*270,y:typeof m.canvas_y==="number"?m.canvas_y:60+Math.floor(index/4)*170}]})));setUndoStack([]);setRedoStack([]);setSelectedNodeIds([]);setSelectedEdgeId(null)}
 function beginDrag(event:React.PointerEvent,nodeId:string){event.stopPropagation();const rect=canvasRef.current?.getBoundingClientRect();if(!rect)return;const additive=event.shiftKey||event.metaKey||event.ctrlKey;let selection=selectedNodeIds.includes(nodeId)?selectedNodeIds:additive?[...selectedNodeIds,nodeId]:[nodeId];if(additive&&selectedNodeIds.includes(nodeId))selection=selectedNodeIds.filter(id=>id!==nodeId);if(!selection.includes(nodeId))selection=[nodeId];setSelectedNodeIds(selection);setSelectedEdgeId(null);dragStartSnapshot.current=clonePositions(positions);setDragging({anchorId:nodeId,startX:(event.clientX-rect.left)/zoom,startY:(event.clientY-rect.top)/zoom,originals:Object.fromEntries(selection.map(id=>[id,{...(positions[id]??{x:0,y:0})}]))});event.currentTarget.setPointerCapture(event.pointerId)}
 function beginPan(event:React.PointerEvent<HTMLDivElement>){if(event.target!==event.currentTarget||!viewportRef.current)return;setPanning({x:event.clientX,y:event.clientY,left:viewportRef.current.scrollLeft,top:viewportRef.current.scrollTop});event.currentTarget.setPointerCapture(event.pointerId)}
 function pointerMove(event:React.PointerEvent){if(dragging){const rect=canvasRef.current?.getBoundingClientRect();if(!rect)return;const dx=(event.clientX-rect.left)/zoom-dragging.startX,dy=(event.clientY-rect.top)/zoom-dragging.startY;setPositions(current=>{const next={...current};for(const[id,origin]of Object.entries(dragging.originals))next[id]={x:Math.max(10,origin.x+dx),y:Math.max(10,origin.y+dy)};return next})}else if(panning&&viewportRef.current){viewportRef.current.scrollLeft=panning.left-(event.clientX-panning.x);viewportRef.current.scrollTop=panning.top-(event.clientY-panning.y)}}
 async function endPointer(){if(dragging){const before=dragStartSnapshot.current,changed:PositionSnapshot={};for(const id of Object.keys(dragging.originals)){const raw=positions[id];if(raw)changed[id]=applySnap(raw)}setPositions(current=>({...current,...changed}));setDragging(null);dragStartSnapshot.current=null;if(before&&Object.entries(changed).some(([id,p])=>before[id]?.x!==p.x||before[id]?.y!==p.y))pushUndo(before);await persistPositions(changed);setMessage(`${Object.keys(changed).length} ${Object.keys(changed).length===1?"node":"nodes"} moved.`)}setPanning(null)}
 function applySnap(p:Position):Position{return snapToGrid?{x:Math.max(GRID_SIZE,Math.round(p.x/GRID_SIZE)*GRID_SIZE),y:Math.max(GRID_SIZE,Math.round(p.y/GRID_SIZE)*GRID_SIZE)}:p}
 function pushUndo(s:PositionSnapshot){setUndoStack(c=>[...c.slice(-29),clonePositions(s)]);setRedoStack([])}
 async function persistPositions(s:PositionSnapshot){await Promise.all(Object.entries(s).map(([id,p])=>{const n=nodes.find(x=>x.id===id);return n?supabase.from("emmaus_graph_nodes").update({metadata:{...(n.metadata??{}),canvas_x:p.x,canvas_y:p.y}}).eq("id",id):Promise.resolve()}))}
 async function undoLayout(){const previous=undoStack.at(-1);if(!previous)return;setRedoStack(c=>[...c.slice(-29),clonePositions(positions)]);setUndoStack(c=>c.slice(0,-1));setPositions(clonePositions(previous));setMessage("Layout undone and saved.");await persistPositions(previous)}
 async function redoLayout(){const next=redoStack.at(-1);if(!next)return;setUndoStack(c=>[...c.slice(-29),clonePositions(positions)]);setRedoStack(c=>c.slice(0,-1));setPositions(clonePositions(next));setMessage("Layout redone and saved.");await persistPositions(next)}
 async function createNode(){if(!nodeDraft.node_key.trim()||!nodeDraft.title.trim())return setMessage("Node key and title are required.");setSaving(true);const initial=applySnap({x:80,y:80});const{data,error}=await supabase.from("emmaus_graph_nodes").insert({...nodeDraft,node_key:nodeDraft.node_key.trim().toLowerCase().replace(/[^a-z0-9:-]+/g,"-"),subtitle:nodeDraft.subtitle||null,scripture_reference:nodeDraft.scripture_reference||null,summary:nodeDraft.summary||null,metadata:{canvas_x:initial.x,canvas_y:initial.y}}).select("id,node_key,node_type,title,subtitle,scripture_reference,summary,status,metadata").single();setSaving(false);if(error)return setMessage(error.message);pushUndo(positions);setNodes(c=>[...c,data as NodeRow]);setPositions(c=>({...c,[data.id]:initial}));setSelectedNodeIds([data.id]);setNodeDraft({node_key:"",node_type:"theme",title:"",subtitle:"",scripture_reference:"",summary:"",status:"draft"});setMessage("Node created.")}
 function selectNode(event:React.MouseEvent,nodeId:string){if(connectSource&&connectSource!==nodeId){void createEdge(connectSource,nodeId);return}if(event.shiftKey||event.metaKey||event.ctrlKey)setSelectedNodeIds(c=>c.includes(nodeId)?c.filter(id=>id!==nodeId):[...c,nodeId]);else setSelectedNodeIds([nodeId]);setSelectedEdgeId(null)}
 async function createEdge(sourceId:string,targetId:string){setSaving(true);const{data,error}=await supabase.from("emmaus_graph_edges").insert({source_node_id:sourceId,target_node_id:targetId,relationship_key:edgeDraft.relationship_key,explanation:edgeDraft.explanation||null,confidence_score:edgeDraft.confidence_score,confidence_class:confidenceClass(edgeDraft.confidence_score),status:edgeDraft.status}).select("id,source_node_id,target_node_id,relationship_key,explanation,confidence_score,confidence_class,evidence_summary,interpretive_notes,status").single();setSaving(false);setConnectSource(null);if(error)return setMessage(error.message);setEdges(c=>[...c,data as EdgeRow]);setSelectedEdgeId(data.id);setSelectedNodeIds([]);setMessage("Relationship created.")}
 async function updateSelectedNode(patch:Partial<NodeRow>){if(!selectedNodeId)return;const{error}=await supabase.from("emmaus_graph_nodes").update(patch).eq("id",selectedNodeId);if(error)return setMessage(error.message);setNodes(c=>c.map(n=>n.id===selectedNodeId?{...n,...patch}:n))}
 async function updateSelectedEdge(patch:Partial<EdgeRow>){if(!selectedEdgeId)return;const next=patch.confidence_score===undefined?patch:{...patch,confidence_class:confidenceClass(patch.confidence_score)};const{error}=await supabase.from("emmaus_graph_edges").update(next).eq("id",selectedEdgeId);if(error)return setMessage(error.message);setEdges(c=>c.map(e=>e.id===selectedEdgeId?{...e,...next}:e))}
 async function deleteSelected(){if(selectedEdgeId){const{error}=await supabase.from("emmaus_graph_edges").delete().eq("id",selectedEdgeId);if(error)return setMessage(error.message);setEdges(c=>c.filter(e=>e.id!==selectedEdgeId));setSelectedEdgeId(null);return setMessage("Relationship deleted.")}if(selectedNodeIds.length){for(const id of selectedNodeIds){const{error}=await supabase.from("emmaus_graph_nodes").delete().eq("id",id);if(error)return setMessage(error.message)}const ids=new Set(selectedNodeIds);setNodes(c=>c.filter(n=>!ids.has(n.id)));setEdges(c=>c.filter(e=>!ids.has(e.source_node_id)&&!ids.has(e.target_node_id)));setPositions(c=>{const next={...c};for(const id of ids)delete next[id];return next});setMessage(`${ids.size} ${ids.size===1?"node":"nodes"} deleted.`);setSelectedNodeIds([])}}

 const normalizedSearch=search.trim().toLowerCase();
 const visibleNodes=nodes.filter(n=>(!normalizedSearch||[n.title,n.node_key,n.scripture_reference,n.summary].some(v=>v?.toLowerCase().includes(normalizedSearch)))&&(typeFilter==="all"||n.node_type===typeFilter)&&(statusFilter==="all"||(statusFilter==="active"?n.status!=="archived":n.status===statusFilter)));
 const visibleIds=new Set(visibleNodes.map(n=>n.id));const visibleEdges=edges.filter(e=>visibleIds.has(e.source_node_id)&&visibleIds.has(e.target_node_id)&&(statusFilter==="all"||(statusFilter==="active"?e.status!=="archived":e.status===statusFilter)));
 async function autoLayout(){pushUndo(positions);const arranged=Object.fromEntries(visibleNodes.map((n,i)=>[n.id,applySnap({x:60+(i%4)*270,y:60+Math.floor(i/4)*170})])) as PositionSnapshot;setPositions(c=>({...c,...arranged}));await persistPositions(arranged);setMessage("Auto-layout saved.")}
 function focusNode(n:NodeRow){setSelectedNodeIds([n.id]);setSelectedEdgeId(null);const p=positions[n.id];if(p&&viewportRef.current)viewportRef.current.scrollTo({left:Math.max(0,p.x*zoom-180),top:Math.max(0,p.y*zoom-140),behavior:"smooth"})}
 const selectedNode=nodes.find(n=>n.id===selectedNodeId)??null,selectedEdge=edges.find(e=>e.id===selectedEdgeId)??null,canvasWidth=Math.max(1200,...Object.values(positions).map(p=>p.x+NODE_WIDTH+120)),canvasHeight=Math.max(760,...Object.values(positions).map(p=>p.y+NODE_HEIGHT+120));
 const relationshipLabel=(key:string)=>relationships.find(r=>r.key===key)?.label??key.replaceAll("_"," ");

 return <div className="grid gap-5 xl:grid-cols-[280px_1fr_340px]">
  <aside className="space-y-5 rounded-[2rem] border border-slate-200 bg-white p-5 shadow-xl"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-indigo-700">Node Palette</p><h2 className="mt-2 text-2xl font-black text-slate-950">Add to the graph</h2></div><Field label="Node key"><input className={inputClass} value={nodeDraft.node_key} onChange={e=>setNodeDraft({...nodeDraft,node_key:e.target.value})} placeholder="theme-light"/></Field><Field label="Type"><select className={inputClass} value={nodeDraft.node_type} onChange={e=>setNodeDraft({...nodeDraft,node_type:e.target.value})}>{nodeTypes.map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Title"><input className={inputClass} value={nodeDraft.title} onChange={e=>setNodeDraft({...nodeDraft,title:e.target.value})}/></Field><Field label="Scripture reference"><input className={inputClass} value={nodeDraft.scripture_reference} onChange={e=>setNodeDraft({...nodeDraft,scripture_reference:e.target.value})}/></Field><Field label="Summary"><textarea className={inputClass} rows={3} value={nodeDraft.summary} onChange={e=>setNodeDraft({...nodeDraft,summary:e.target.value})}/></Field><button disabled={saving} onClick={()=>void createNode()} className="w-full rounded-xl bg-indigo-600 px-4 py-3 font-black text-white disabled:opacity-50">Create node</button><div className="border-t border-slate-200 pt-5"><p className="text-xs font-black uppercase tracking-[0.16em] text-indigo-700">Connection defaults</p></div><Field label="Relationship"><select className={inputClass} value={edgeDraft.relationship_key} onChange={e=>setEdgeDraft({...edgeDraft,relationship_key:e.target.value})}>{relationships.map(r=><option key={r.key} value={r.key}>{r.label}</option>)}</select></Field><Field label="Confidence"><input className={inputClass} type="number" min={0} max={100} value={edgeDraft.confidence_score} onChange={e=>setEdgeDraft({...edgeDraft,confidence_score:Number(e.target.value)})}/></Field><Field label="Explanation"><textarea className={inputClass} rows={3} value={edgeDraft.explanation} onChange={e=>setEdgeDraft({...edgeDraft,explanation:e.target.value})}/></Field></aside>
  <section className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-xl"><div className="space-y-3 border-b border-slate-200 bg-slate-950 px-5 py-4 text-white"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-300">Visual Graph Builder</p><p className="mt-1 text-sm text-indigo-100/70">{visibleNodes.length} nodes · {selectedNodeIds.length} selected · Shift/Cmd/Ctrl-click to select more</p></div><div className="flex flex-wrap gap-2"><button disabled={!undoStack.length} onClick={()=>void undoLayout()} className={toolButton}>Undo</button><button disabled={!redoStack.length} onClick={()=>void redoLayout()} className={toolButton}>Redo</button><button onClick={()=>setSnapToGrid(v=>!v)} className={`rounded-full px-4 py-2 text-sm font-black ${snapToGrid?"bg-emerald-300 text-slate-950":"border border-white/20 bg-white/10"}`}>Snap {snapToGrid?"on":"off"}</button><button disabled={selectedNodeIds.length!==1} onClick={()=>setConnectSource(selectedNodeId)} className="rounded-full bg-amber-300 px-4 py-2 text-sm font-black text-slate-950 disabled:opacity-40">Connect</button><button onClick={()=>void autoLayout()} className={toolButton}>Auto-layout</button></div></div><div className="grid gap-2 md:grid-cols-[1fr_160px_150px_auto]"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search nodes..." className="rounded-xl border border-white/15 bg-white/10 px-3 py-2 text-sm text-white outline-none"/><select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)} className="rounded-xl bg-slate-900 px-3 py-2 text-sm"><option value="all">All types</option>{nodeTypes.map(t=><option key={t} value={t}>{t.replace("_"," ")}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="rounded-xl bg-slate-900 px-3 py-2 text-sm"><option value="active">Active</option><option value="all">All</option><option value="draft">Draft</option><option value="reviewed">Reviewed</option><option value="published">Published</option><option value="archived">Archived</option></select><div className="flex items-center rounded-xl border border-white/15 bg-white/10"><button onClick={()=>setZoom(v=>Math.max(.5,Number((v-.1).toFixed(1))))} className="px-3 py-2">−</button><span className="min-w-14 text-center text-xs font-black">{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(v=>Math.min(1.5,Number((v+.1).toFixed(1))))} className="px-3 py-2">+</button></div></div></div>
  <div ref={viewportRef} className="h-[760px] overflow-auto bg-slate-100"><div ref={canvasRef} onPointerDown={beginPan} onPointerMove={pointerMove} onPointerUp={()=>void endPointer()} className={`relative origin-top-left bg-[radial-gradient(circle,#cbd5e1_1px,transparent_1px)] [background-size:${GRID_SIZE}px_${GRID_SIZE}px] ${panning?"cursor-grabbing":"cursor-grab"}`} style={{width:canvasWidth,height:canvasHeight,transform:`scale(${zoom})`}}><svg className="pointer-events-none absolute inset-0 h-full w-full overflow-visible"><defs><marker id="emmaus-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5L0 10z" fill="#64748b"/></marker></defs>{visibleEdges.map(e=>{const s=positions[e.source_node_id],t=positions[e.target_node_id];if(!s||!t)return null;const x1=s.x+NODE_WIDTH/2,y1=s.y+NODE_HEIGHT/2,x2=t.x+NODE_WIDTH/2,y2=t.y+NODE_HEIGHT/2,mx=(x1+x2)/2,my=(y1+y2)/2-36;return <g key={e.id} className="pointer-events-auto cursor-pointer" onClick={()=>{setSelectedEdgeId(e.id);setSelectedNodeIds([])}}><path d={`M ${x1} ${y1} Q ${mx} ${my} ${x2} ${y2}`} fill="none" stroke={selectedEdgeId===e.id?"#4f46e5":"#64748b"} strokeWidth={selectedEdgeId===e.id?4:2.5} markerEnd="url(#emmaus-arrow)"/><rect x={mx-66} y={my-16} width="132" height="32" rx="16" fill="white" stroke="#cbd5e1"/><text x={mx} y={my-2} textAnchor="middle" fontSize="10" fontWeight="700">{relationshipLabel(e.relationship_key).slice(0,20)}</text><text x={mx} y={my+10} textAnchor="middle" fontSize="9">{e.confidence_score}%</text></g>})}</svg>{visibleNodes.map(n=>{const p=positions[n.id]??{x:0,y:0},selected=selectedNodeIds.includes(n.id);return <button key={n.id} onPointerDown={e=>beginDrag(e,n.id)} onClick={e=>selectNode(e,n.id)} onDoubleClick={()=>focusNode(n)} className={`absolute rounded-2xl border bg-white p-4 text-left shadow-lg ${selected?"border-indigo-500 ring-4 ring-indigo-100":connectSource===n.id?"border-amber-400 ring-4 ring-amber-100":"border-slate-200"}`} style={{left:p.x,top:p.y,width:NODE_WIDTH,minHeight:NODE_HEIGHT}}><div className="flex justify-between gap-3"><span className="rounded-full bg-indigo-50 px-2 py-1 text-[10px] font-black uppercase text-indigo-700">{n.node_type.replace("_"," ")}</span><span className="text-[10px] font-black uppercase text-slate-400">{n.status}</span></div><h3 className="mt-3 font-black text-slate-950">{n.title}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-500">{n.scripture_reference||n.subtitle||n.summary||n.node_key}</p></button>})}</div></div></section>
  <aside className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-xl"><p className="text-xs font-black uppercase tracking-[0.16em] text-indigo-700">Inspector</p>{selectedNodeIds.length>1&&<div className="mt-5 rounded-2xl border border-indigo-200 bg-indigo-50 p-5"><h2 className="text-2xl font-black text-slate-950">{selectedNodeIds.length} nodes selected</h2><p className="mt-2 text-sm leading-6 text-slate-600">Drag any selected node to move the entire group. Delete removes all selected nodes.</p></div>}{selectedNode&&<div className="mt-5 space-y-4"><div className="flex justify-between"><h2 className="text-2xl font-black">Edit node</h2><button onClick={()=>focusNode(selectedNode)} className="rounded-lg border px-3 py-2 text-xs font-black">Locate</button></div><Field label="Title"><input className={inputClass} value={selectedNode.title} onChange={e=>setNodes(c=>c.map(n=>n.id===selectedNode.id?{...n,title:e.target.value}:n))} onBlur={()=>void updateSelectedNode({title:selectedNode.title})}/></Field><Field label="Summary"><textarea className={inputClass} rows={5} value={selectedNode.summary??""} onChange={e=>setNodes(c=>c.map(n=>n.id===selectedNode.id?{...n,summary:e.target.value}:n))} onBlur={()=>void updateSelectedNode({summary:selectedNode.summary})}/></Field><Field label="Status"><select className={inputClass} value={selectedNode.status} onChange={e=>void updateSelectedNode({status:e.target.value as NodeRow["status"]})}><option value="draft">Draft</option><option value="reviewed">Reviewed</option><option value="published">Published</option><option value="archived">Archived</option></select></Field></div>}{selectedEdge&&<div className="mt-5 space-y-4"><h2 className="text-2xl font-black">Edit relationship</h2><Field label="Relationship"><select className={inputClass} value={selectedEdge.relationship_key} onChange={e=>void updateSelectedEdge({relationship_key:e.target.value})}>{relationships.map(r=><option key={r.key} value={r.key}>{r.label}</option>)}</select></Field><Field label="Confidence"><input className={inputClass} type="number" value={selectedEdge.confidence_score} onChange={e=>void updateSelectedEdge({confidence_score:Number(e.target.value)})}/></Field></div>}{!selectedNodeIds.length&&!selectedEdge&&<p className="mt-5 leading-7 text-slate-500">Shift/Cmd/Ctrl-click nodes to multi-select. Cmd/Ctrl+A selects all visible nodes.</p>}{(selectedNodeIds.length>0||selectedEdge)&&<button onClick={()=>void deleteSelected()} className="mt-6 w-full rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 font-black text-rose-700">Delete selected</button>}<p className="mt-5 text-sm font-bold text-slate-500">{message}</p></aside>
 </div>
}
function clonePositions(s:PositionSnapshot):PositionSnapshot{return Object.fromEntries(Object.entries(s).map(([id,p])=>[id,{...p}]))}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="text-sm font-black text-slate-700">{label}</span><div className="mt-2">{children}</div></label>}
function confidenceClass(score:number){return score>=95?"explicit":score>=85?"strong":score>=65?"supported":score>=40?"tentative":"disputed"}
const inputClass="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-slate-950 outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100";
const toolButton="rounded-full border border-white/20 bg-white/10 px-4 py-2 text-sm font-black disabled:opacity-35";
