"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type Node={id:string;node_key:string;node_type:string;title:string;subtitle:string|null;summary:string|null;scripture_reference:string|null;metadata:Record<string,unknown>|null};
type Edge={id:string;source_node_id:string;target_node_id:string;relationship_key:string;explanation:string|null;weight:number};
type Connection={node:Node;edge:Edge};

export default function GraphNodeExplorer({nodeKey}:{nodeKey:string}){
 const supabase=useMemo(()=>createClient(),[]),router=useRouter(),search=useSearchParams();
 const[node,setNode]=useState<Node|null>(null),[connections,setConnections]=useState<Connection[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 const origin=search.get("from"),originLabel=search.get("fromLabel");
 async function load(){setLoading(true);setMessage("");const{data:current,error}=await supabase.from("emmaus_graph_nodes").select("id,node_key,node_type,title,subtitle,summary,scripture_reference,metadata").eq("node_key",decodeURIComponent(nodeKey)).eq("status","published").maybeSingle();if(error||!current){setMessage(error?.message??"Discovery not found.");setLoading(false);return}setNode(current as Node);const{data:edgeRows,error:edgeError}=await supabase.from("emmaus_graph_edges").select("id,source_node_id,target_node_id,relationship_key,explanation,weight").or(`source_node_id.eq.${current.id},target_node_id.eq.${current.id}`).eq("status","published").order("weight",{ascending:false}).limit(80);if(edgeError){setMessage(edgeError.message);setLoading(false);return}const edges=(edgeRows??[]) as Edge[];const ids=[...new Set(edges.map(e=>e.source_node_id===current.id?e.target_node_id:e.source_node_id))];if(ids.length){const{data:related,error:relatedError}=await supabase.from("emmaus_graph_nodes").select("id,node_key,node_type,title,subtitle,summary,scripture_reference,metadata").in("id",ids).eq("status","published");if(relatedError){setMessage(relatedError.message);setLoading(false);return}const byId=Object.fromEntries(((related??[]) as Node[]).map(n=>[n.id,n]));setConnections(edges.map(edge=>({edge,node:byId[edge.source_node_id===current.id?edge.target_node_id:edge.source_node_id]})).filter(item=>item.node));}else setConnections([]);setLoading(false)}
 useEffect(()=>{void load()},[nodeKey]);
 function travel(target:Node){const params=new URLSearchParams();params.set("from",node?.node_key??"");params.set("fromLabel",node?.title??"");router.push(`/emmaus/explore/${encodeURIComponent(target.node_key)}?${params.toString()}`)}
 const grouped=connections.reduce<Record<string,Connection[]>>((acc,item)=>{(acc[item.node.node_type]??=[]).push(item);return acc},{});
 if(loading)return <div className="rounded-[2rem] border border-slate-200 bg-white p-10 text-center font-black text-slate-500 shadow-xl">Opening this discovery...</div>;
 if(!node)return <div className="rounded-[2rem] border border-rose-200 bg-rose-50 p-10 text-center font-black text-rose-700">{message||"Discovery not found."}</div>;
 return <div className="mx-auto max-w-7xl space-y-6">
  <nav className="flex flex-wrap items-center gap-2 text-sm font-black text-slate-500"><Link href="/emmaus" className="hover:text-indigo-700">Emmaus</Link><span>→</span>{origin&&originLabel?<><Link href={`/emmaus/explore/${encodeURIComponent(origin)}`} className="hover:text-indigo-700">{originLabel}</Link><span>→</span></>:null}<span className="text-indigo-700">{node.title}</span></nav>
  <section className="overflow-hidden rounded-[2rem] bg-slate-950 p-7 text-white shadow-2xl sm:p-9"><div className="flex flex-wrap items-start justify-between gap-5"><div className="max-w-4xl"><p className="text-xs font-black uppercase tracking-[0.18em] text-amber-300">{node.node_type.replaceAll("_"," ")} discovery</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">{node.title}</h1>{node.subtitle&&<p className="mt-2 text-xl font-black text-indigo-200">{node.subtitle}</p>}{node.scripture_reference&&<p className="mt-4 text-lg font-black text-amber-200">{node.scripture_reference}</p>}<p className="mt-5 max-w-3xl text-lg leading-8 text-indigo-50/75">{node.summary}</p></div><div className="rounded-2xl border border-white/10 bg-white/10 px-5 py-4 text-center"><p className="text-3xl font-black">{connections.length}</p><p className="text-[10px] font-black uppercase tracking-widest text-indigo-200">Connections</p></div></div></section>
  <section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{Object.entries(grouped).map(([type,items])=><div key={type} className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-xl"><p className="text-xs font-black uppercase tracking-[0.16em] text-indigo-700">{type.replaceAll("_"," ")}</p><div className="mt-4 space-y-3">{items.map(({node:target,edge})=><button key={edge.id} onClick={()=>travel(target)} className="w-full rounded-2xl border border-slate-200 bg-slate-50 p-4 text-left transition hover:-translate-y-0.5 hover:border-indigo-400 hover:bg-indigo-50"><p className="font-black text-slate-950">{target.title}</p><p className="mt-1 text-xs font-black uppercase tracking-wide text-indigo-700">{edge.relationship_key.replaceAll("_"," ")}</p>{edge.explanation&&<p className="mt-2 text-sm leading-6 text-slate-600">{edge.explanation}</p>}<p className="mt-3 text-xs font-black text-indigo-600">Travel here →</p></button>)}</div></div>)}</section>
  {!connections.length&&<section className="rounded-[2rem] border border-dashed border-slate-300 bg-white p-10 text-center shadow-xl"><h2 className="text-2xl font-black text-slate-950">This discovery is waiting for more connections.</h2><p className="mt-3 text-slate-600">The node exists, but its surrounding graph has not been fully developed yet.</p></section>}
  <div className="flex flex-wrap gap-3">{origin&&originLabel&&<button onClick={()=>router.back()} className="rounded-full border border-indigo-300 bg-indigo-50 px-5 py-3 font-black text-indigo-700">← Return to {originLabel}</button>}<Link href="/emmaus/explore/john-1" className="rounded-full bg-indigo-600 px-5 py-3 font-black text-white">Return to John 1</Link></div><p className="min-h-5 text-sm font-bold text-slate-500">{message}</p>
 </div>;
}
