"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type GraphNode={id:string;node_key:string;node_type:string;title:string;subtitle:string|null;summary:string|null;scripture_reference:string|null};
type GraphEdge={id:string;source_node_id:string;target_node_id:string;relationship_key:string;explanation:string|null;weight:number};
type CanvasNode=GraphNode&{x:number;y:number;depth:number};
type CanvasEdge=GraphEdge&{source:string;target:string};

const FILTERS=["all","verse","passage","theme","person","place","event","discovery","language_term","question"];

export default function InteractiveGraphCanvas({nodeKey}:{nodeKey:string}){
 const supabase=useMemo(()=>createClient(),[]);
 const viewport=useRef<HTMLDivElement>(null);
 const[nodes,setNodes]=useState<CanvasNode[]>([]),[edges,setEdges]=useState<CanvasEdge[]>([]),[selected,setSelected]=useState<CanvasNode|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[zoom,setZoom]=useState(1),[offset,setOffset]=useState({x:0,y:0}),[filter,setFilter]=useState("all"),[dragging,setDragging]=useState(false),[dragStart,setDragStart]=useState({x:0,y:0});
 useEffect(()=>{void initialize()},[nodeKey]);

 async function initialize(){setLoading(true);setMessage("");const decoded=decodeURIComponent(nodeKey);const{data:root,error}=await supabase.from("emmaus_graph_nodes").select("id,node_key,node_type,title,subtitle,summary,scripture_reference").eq("node_key",decoded).eq("status","published").maybeSingle();if(error||!root){setMessage(error?.message??"Graph node not found.");setLoading(false);return}const center={...(root as GraphNode),x:600,y:390,depth:0};setNodes([center]);setSelected(center);setEdges([]);await expandNode(center,true);setLoading(false)}

 async function expandNode(node:CanvasNode,initial=false){const{data:edgeRows,error}=await supabase.from("emmaus_graph_edges").select("id,source_node_id,target_node_id,relationship_key,explanation,weight").or(`source_node_id.eq.${node.id},target_node_id.eq.${node.id}`).eq("status","published").order("weight",{ascending:false}).limit(initial?18:12);if(error){setMessage(error.message);return}const raw=(edgeRows??[]) as GraphEdge[];const ids=[...new Set(raw.map(edge=>edge.source_node_id===node.id?edge.target_node_id:edge.source_node_id))];if(!ids.length)return;const{data:related,error:nodeError}=await supabase.from("emmaus_graph_nodes").select("id,node_key,node_type,title,subtitle,summary,scripture_reference").in("id",ids).eq("status","published");if(nodeError){setMessage(nodeError.message);return}const relatedNodes=(related??[]) as GraphNode[];
 setNodes(current=>{const known=new Set(current.map(item=>item.id));const additions=relatedNodes.filter(item=>!known.has(item.id));const ring=node.depth===0?210:150;const positioned=additions.map((item,index)=>{const angle=(Math.PI*2*index)/Math.max(1,additions.length)+(node.depth%2?Math.PI/8:0);return{...item,x:node.x+Math.cos(angle)*ring,y:node.y+Math.sin(angle)*ring,depth:node.depth+1}});return[...current,...positioned]});
 setEdges(current=>{const known=new Set(current.map(item=>item.id));const additions=raw.filter(item=>!known.has(item.id)).map(item=>({...item,source:item.source_node_id,target:item.target_node_id}));return[...current,...additions]});}

 function beginDrag(event:React.PointerEvent){setDragging(true);setDragStart({x:event.clientX-offset.x,y:event.clientY-offset.y});(event.currentTarget as HTMLElement).setPointerCapture(event.pointerId)}
 function drag(event:React.PointerEvent){if(dragging)setOffset({x:event.clientX-dragStart.x,y:event.clientY-dragStart.y})}
 function endDrag(){setDragging(false)}
 const visibleNodes=nodes.filter(node=>filter==="all"||node.node_type===filter);
 const visibleIds=new Set(visibleNodes.map(node=>node.id));
 const visibleEdges=edges.filter(edge=>visibleIds.has(edge.source)&&visibleIds.has(edge.target));
 const byId=Object.fromEntries(nodes.map(node=>[node.id,node]));
 if(loading)return <div className="rounded-[2rem] border border-slate-200 bg-white p-10 text-center font-black text-slate-500 shadow-xl">Building the graph canvas...</div>;
 if(!nodes.length)return <div className="rounded-[2rem] border border-rose-200 bg-rose-50 p-10 text-center font-black text-rose-700">{message||"Graph unavailable."}</div>;
 return <div className="grid gap-6 xl:grid-cols-[1fr_340px]">
  <section className="overflow-hidden rounded-[2rem] border border-slate-800 bg-slate-950 shadow-2xl"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 px-5 py-4 text-white"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-300">Interactive graph canvas</p><p className="mt-1 text-sm text-indigo-100/70">Drag to pan. Use the controls to zoom. Select a node to inspect or expand it.</p></div><div className="flex gap-2"><button onClick={()=>setZoom(value=>Math.min(1.8,value+.15))} className="rounded-full bg-white/10 px-4 py-2 font-black">＋</button><button onClick={()=>setZoom(value=>Math.max(.55,value-.15))} className="rounded-full bg-white/10 px-4 py-2 font-black">−</button><button onClick={()=>{setZoom(1);setOffset({x:0,y:0})}} className="rounded-full bg-white/10 px-4 py-2 text-sm font-black">Reset</button></div></div>
   <div className="flex flex-wrap gap-2 border-b border-white/10 px-5 py-3">{FILTERS.map(item=><button key={item} onClick={()=>setFilter(item)} className={`rounded-full px-3 py-1.5 text-[11px] font-black capitalize ${filter===item?"bg-amber-300 text-slate-950":"bg-white/10 text-white"}`}>{item.replaceAll("_"," ")}</button>)}</div>
   <div ref={viewport} onPointerDown={beginDrag} onPointerMove={drag} onPointerUp={endDrag} onPointerCancel={endDrag} className="h-[720px] touch-none cursor-grab overflow-hidden bg-[radial-gradient(circle_at_center,rgba(79,70,229,.27),#020617_70%)] active:cursor-grabbing"><svg width="1200" height="780" style={{transform:`translate(${offset.x}px,${offset.y}px) scale(${zoom})`,transformOrigin:"center"}} className="transition-transform duration-75"><defs><filter id="nodeGlow"><feGaussianBlur stdDeviation="4" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>{visibleEdges.map(edge=>{const source=byId[edge.source],target=byId[edge.target];if(!source||!target)return null;return <g key={edge.id}><line x1={source.x} y1={source.y} x2={target.x} y2={target.y} stroke="rgba(129,140,248,.45)" strokeWidth={Math.max(1.5,Number(edge.weight||1)*1.3)}/><text x={(source.x+target.x)/2} y={(source.y+target.y)/2-7} fill="rgba(224,231,255,.7)" fontSize="9" textAnchor="middle">{edge.relationship_key.replaceAll("_"," ")}</text></g>})}{visibleNodes.map(node=><g key={node.id} transform={`translate(${node.x},${node.y})`} onPointerDown={event=>event.stopPropagation()} onClick={()=>setSelected(node)} onDoubleClick={()=>void expandNode(node)} className="cursor-pointer" filter="url(#nodeGlow)"><circle r={node.depth===0?55:node.depth===1?38:31} fill={nodeColor(node.node_type)} stroke={selected?.id===node.id?"#fde68a":"#e0e7ff"} strokeWidth={selected?.id===node.id?5:2}/><text y="-4" fill="white" fontSize={node.depth===0?12:9} fontWeight="900" textAnchor="middle">{short(node.title,node.depth===0?18:13)}</text><text y="12" fill="rgba(255,255,255,.72)" fontSize="7" fontWeight="700" textAnchor="middle">{node.node_type.replaceAll("_"," ")}</text></g>)}</svg></div></section>
  <aside className="space-y-5"><section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-xl">{selected?<><p className="text-xs font-black uppercase tracking-[0.16em] text-indigo-700">Selected node</p><h2 className="mt-2 text-3xl font-black text-slate-950">{selected.title}</h2>{selected.scripture_reference&&<p className="mt-2 font-black text-indigo-700">{selected.scripture_reference}</p>}<p className="mt-4 text-sm leading-7 text-slate-600">{selected.summary}</p><div className="mt-5 grid gap-3"><button onClick={()=>void expandNode(selected)} className="rounded-full bg-indigo-600 px-5 py-3 font-black text-white">Expand connections</button><Link href={`/emmaus/explore/${encodeURIComponent(selected.node_key)}`} className="rounded-full border border-indigo-300 bg-indigo-50 px-5 py-3 text-center font-black text-indigo-700">Open full explorer</Link></div></>:<p className="text-sm text-slate-500">Select a graph node to inspect it.</p>}</section><section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-xl"><p className="text-xs font-black uppercase tracking-[0.16em] text-indigo-700">Canvas status</p><div className="mt-4 grid grid-cols-2 gap-3"><Stat value={visibleNodes.length} label="Visible nodes"/><Stat value={visibleEdges.length} label="Visible links"/><Stat value={`${Math.round(zoom*100)}%`} label="Zoom"/><Stat value={filter.replaceAll("_"," ")} label="Filter"/></div><p className="mt-4 text-xs leading-5 text-slate-500">Double-click any node to reveal another layer without leaving the canvas.</p></section><p className="min-h-5 text-sm font-bold text-slate-500">{message}</p></aside>
 </div>
}
function Stat({value,label}:{value:string|number;label:string}){return <div className="rounded-2xl bg-slate-50 p-3 text-center"><p className="text-xl font-black text-slate-950">{value}</p><p className="mt-1 text-[10px] font-black uppercase text-slate-400">{label}</p></div>}
function short(value:string,max:number){return value.length>max?`${value.slice(0,max-1)}…`:value}
function nodeColor(type:string){const colors:Record<string,string>={verse:"#4f46e5",passage:"#4338ca",book:"#1d4ed8",theme:"#7c3aed",person:"#0f766e",place:"#0369a1",event:"#b45309",discovery:"#be123c",language_term:"#475569",question:"#c026d3",doctrine:"#9f1239",promise:"#15803d",command:"#b91c1c"};return colors[type]??"#334155"}
