"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type Verse={id:string;verse_start:number;reference_label:string;text_content:string;graph_node_id:string|null};
type Node={id:string;node_key:string;node_type:string;title:string;subtitle:string|null;summary:string|null;scripture_reference:string|null};
type Edge={id:string;source_node_id:string;target_node_id:string;relationship_key:string;explanation:string|null};
type Connection={node:Node;edge:Edge};
type SectionKey="questions"|"language"|"scripture"|"themes"|"people"|"places"|"events"|"discoveries"|"journal";

const sectionOrder:SectionKey[]=["questions","language","scripture","themes","people","places","events","discoveries","journal"];

export default function JohnOneDiscoveryExplorer(){
 const supabase=useMemo(()=>createClient(),[]),router=useRouter();
 const[verses,setVerses]=useState<Verse[]>([]),[connections,setConnections]=useState<Connection[]>([]),[selectedVerse,setSelectedVerse]=useState<Verse|null>(null),[selectedConnection,setSelectedConnection]=useState<Connection|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 const[response,setResponse]=useState(""),[openSections,setOpenSections]=useState<Set<SectionKey>>(new Set(["questions"])),[sheetOpen,setSheetOpen]=useState(false),[verseMenuOpen,setVerseMenuOpen]=useState(false);

 async function loadChapter(){setLoading(true);const{data,error}=await supabase.from("emmaus_scripture_nodes").select("id,verse_start,reference_label,text_content,graph_node_id").eq("translation","KJV").eq("book_key","john").eq("chapter",1).eq("status","published").order("verse_start");if(error){setMessage(error.message);setLoading(false);return}const rows=(data??[]) as Verse[];setVerses(rows);setSelectedVerse(rows[0]??null);setLoading(false)}
 async function loadNeighborhood(graphNodeId:string){const{data:edgeRows,error}=await supabase.from("emmaus_graph_edges").select("id,source_node_id,target_node_id,relationship_key,explanation").or(`source_node_id.eq.${graphNodeId},target_node_id.eq.${graphNodeId}`).eq("status","published").limit(60);if(error){setMessage(error.message);return}const edges=(edgeRows??[]) as Edge[];const ids=[...new Set(edges.map(e=>e.source_node_id===graphNodeId?e.target_node_id:e.source_node_id))];if(!ids.length){setConnections([]);return}const{data:nodeRows,error:nodeError}=await supabase.from("emmaus_graph_nodes").select("id,node_key,node_type,title,subtitle,summary,scripture_reference").in("id",ids).eq("status","published");if(nodeError){setMessage(nodeError.message);return}const map=Object.fromEntries(((nodeRows??[]) as Node[]).map(n=>[n.id,n]));setConnections(edges.map(edge=>{const id=edge.source_node_id===graphNodeId?edge.target_node_id:edge.source_node_id;return{node:map[id],edge}}).filter(item=>item.node));}

 useEffect(()=>{void loadChapter();const stored=window.localStorage.getItem("emmaus-john1-sections");if(stored){try{setOpenSections(new Set(JSON.parse(stored) as SectionKey[]))}catch{}}},[]);
 useEffect(()=>{if(selectedVerse?.graph_node_id)void loadNeighborhood(selectedVerse.graph_node_id);else setConnections([]);setSelectedConnection(null);setSheetOpen(false)},[selectedVerse?.graph_node_id]);

 function chooseVerse(verse:Verse){setSelectedVerse(verse);setResponse("");setVerseMenuOpen(false);window.scrollTo({top:0,behavior:"smooth"})}
 function selectNext(){if(!selectedVerse)return;const next=verses.find(v=>v.verse_start===selectedVerse.verse_start+1);if(next)chooseVerse(next)}
 function selectPrevious(){if(!selectedVerse)return;const previous=verses.find(v=>v.verse_start===selectedVerse.verse_start-1);if(previous)chooseVerse(previous)}
 function toggleSection(key:SectionKey){setOpenSections(current=>{const next=new Set(current);next.has(key)?next.delete(key):next.add(key);window.localStorage.setItem("emmaus-john1-sections",JSON.stringify([...next]));return next})}
 function inspect(connection:Connection){setSelectedConnection(connection);setSheetOpen(true)}
 function travel(connection:Connection){router.push(`/emmaus/explore/${encodeURIComponent(connection.node.node_key)}?from=${encodeURIComponent(selectedVerse?.reference_label??"John 1")}&fromLabel=${encodeURIComponent(selectedVerse?.reference_label??"John 1")}`)}

 const grouped=useMemo(()=>connections.reduce<Record<string,Connection[]>>((acc,item)=>{(acc[item.node.node_type]??=[]).push(item);return acc},{}),[connections]);
 const sections:Record<SectionKey,{label:string;description:string;items:Connection[]}>= {
  questions:{label:"Discovery Questions",description:"Observe first, then interpret and apply.",items:grouped.question??[]},
  language:{label:"Greek Insights",description:"Original-language terms connected to this verse.",items:grouped.language_term??[]},
  scripture:{label:"Scripture Connections",description:"Old Testament echoes, passages, and nearby verses.",items:[...(grouped.passage??[]),...(grouped.verse??[]),...(grouped.book??[])]},
  themes:{label:"Themes",description:"Major biblical ideas developed by this verse.",items:grouped.theme??[]},
  people:{label:"People",description:"People who appear in or illuminate this verse.",items:grouped.person??[]},
  places:{label:"Places",description:"Locations connected to this passage.",items:grouped.place??[]},
  events:{label:"Events",description:"Narrative events tied to this verse.",items:grouped.event??[]},
  discoveries:{label:"Related Journeys",description:"Curated discoveries and routes that continue from here.",items:[...(grouped.discovery??[]),...(grouped.rabbbit_trail??[])]},
  journal:{label:"Your Discovery",description:"Record what you notice, question, or want to remember.",items:[]},
 };

 if(loading)return <div className="rounded-[2rem] border border-slate-200 bg-white p-10 text-center font-black text-slate-500 shadow-xl">Loading John 1...</div>;
 if(!verses.length)return <div className="rounded-[2rem] border border-rose-200 bg-rose-50 p-10 text-center font-black text-rose-700">John 1 is not available yet. Apply the KJV corpus migration first.</div>;

 return <div className="mx-auto max-w-5xl pb-28 lg:pb-10">
  <div className="sticky top-0 z-30 -mx-4 border-b border-slate-800 bg-slate-950 px-4 py-4 text-white shadow-2xl sm:rounded-b-[2rem] sm:px-6">
   <div className="mx-auto flex max-w-5xl items-start justify-between gap-4"><div className="min-w-0"><p className="text-xs font-black uppercase tracking-[0.18em] text-amber-300">John 1 · KJV</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">{selectedVerse?.reference_label}</h1><p className="mt-2 line-clamp-3 text-sm leading-6 text-indigo-100 sm:text-base">{selectedVerse?.text_content}</p></div><button onClick={()=>setVerseMenuOpen(v=>!v)} className="shrink-0 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm font-black">Verse {selectedVerse?.verse_start} ▾</button></div>
   {verseMenuOpen&&<div className="mx-auto mt-4 max-h-72 max-w-5xl overflow-auto rounded-2xl border border-white/10 bg-slate-900 p-3"><div className="grid grid-cols-5 gap-2 sm:grid-cols-8 md:grid-cols-12">{verses.map(v=><button key={v.id} onClick={()=>chooseVerse(v)} className={`rounded-xl px-3 py-2 text-sm font-black ${selectedVerse?.id===v.id?"bg-amber-300 text-slate-950":"bg-white/10 text-white hover:bg-white/20"}`}>{v.verse_start}</button>)}</div></div>}
  </div>

  <div className="mt-6 flex flex-wrap items-center justify-between gap-3"><button disabled={selectedVerse?.verse_start===1} onClick={selectPrevious} className="rounded-full border border-slate-300 bg-white px-5 py-3 font-black text-slate-700 disabled:opacity-40">← Previous</button><div className="flex flex-wrap gap-2">{connections.slice(0,8).map(item=><button key={item.edge.id} onClick={()=>inspect(item)} className="rounded-full border border-indigo-200 bg-indigo-50 px-3 py-2 text-xs font-black text-indigo-700 hover:border-indigo-400">{item.node.title}</button>)}</div><button disabled={selectedVerse?.verse_start===51} onClick={selectNext} className="rounded-full bg-indigo-600 px-5 py-3 font-black text-white disabled:opacity-40">Next →</button></div>

  <div className="mt-6 space-y-4">{sectionOrder.map(key=>{const section=sections[key];if(key!=="journal"&&!section.items.length)return null;const open=openSections.has(key);return <section key={key} className="overflow-hidden rounded-[1.75rem] border border-slate-200 bg-white shadow-lg"><button onClick={()=>toggleSection(key)} className="flex w-full items-center justify-between gap-4 p-5 text-left"><div><p className="text-lg font-black text-slate-950">{section.label}</p><p className="mt-1 text-sm text-slate-500">{section.description}</p></div><div className="flex items-center gap-3"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black text-slate-600">{key==="journal"?response.trim()?"Saved locally":"Notes":section.items.length}</span><span className="text-2xl font-black text-indigo-700">{open?"−":"+"}</span></div></button>{open&&<div className="border-t border-slate-100 p-5">{key==="journal"?<><textarea value={response} onChange={e=>setResponse(e.target.value)} rows={6} placeholder="What do you notice? What connection do you see?" className="w-full rounded-2xl border border-slate-300 bg-slate-50 p-4 outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100"/><p className="mt-3 text-sm text-slate-500">Walk-session persistence is the next integration step.</p></>:<div className="grid gap-3 sm:grid-cols-2">{section.items.map(item=><button key={item.edge.id} onClick={()=>inspect(item)} className="rounded-2xl border border-slate-200 bg-slate-50 p-4 text-left transition hover:-translate-y-0.5 hover:border-indigo-400 hover:bg-indigo-50"><p className="font-black text-slate-950">{item.node.title}</p><p className="mt-1 text-xs font-black uppercase tracking-wide text-indigo-700">{item.edge.relationship_key.replaceAll("_"," ")}</p>{item.node.scripture_reference&&<p className="mt-2 text-sm font-bold text-slate-600">{item.node.scripture_reference}</p>}</button>)}</div>}</div>}</section>})}</div>

  <button onClick={()=>router.push(`/emmaus/explore/${encodeURIComponent(`scripture:kjv:john-1-${selectedVerse?.verse_start??1}`)}`)} className="mt-6 w-full rounded-[1.75rem] border border-indigo-200 bg-gradient-to-r from-indigo-50 to-violet-50 p-5 text-left shadow-lg"><p className="text-xs font-black uppercase tracking-[0.16em] text-indigo-700">Visual Layer</p><p className="mt-2 text-2xl font-black text-slate-950">Open the Scripture Galaxy</p><p className="mt-2 text-sm text-slate-600">Explore this verse as a visual network without losing your place in John 1.</p></button>
  <p className="mt-5 min-h-5 text-sm font-bold text-slate-500">{message}</p>

  {sheetOpen&&selectedConnection&&<div className="fixed inset-0 z-50 flex items-end bg-slate-950/55 p-0 backdrop-blur-sm sm:items-center sm:justify-center sm:p-6" onClick={()=>setSheetOpen(false)}><div className="max-h-[82vh] w-full overflow-auto rounded-t-[2rem] bg-white p-6 shadow-2xl sm:max-w-xl sm:rounded-[2rem]" onClick={e=>e.stopPropagation()}><div className="mx-auto mb-5 h-1.5 w-14 rounded-full bg-slate-200 sm:hidden"/><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-indigo-700">{selectedConnection.node.node_type.replaceAll("_"," ")}</p><h2 className="mt-2 text-3xl font-black text-slate-950">{selectedConnection.node.title}</h2></div><button onClick={()=>setSheetOpen(false)} className="rounded-full bg-slate-100 px-3 py-2 font-black text-slate-600">✕</button></div>{selectedConnection.node.scripture_reference&&<p className="mt-3 font-black text-indigo-700">{selectedConnection.node.scripture_reference}</p>}<div className="mt-5 rounded-2xl bg-slate-50 p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-400">Why this connects</p><p className="mt-2 leading-7 text-slate-700">{selectedConnection.edge.explanation??selectedConnection.node.summary??"This node is connected to the selected verse in the Emmaus knowledge graph."}</p></div>{selectedConnection.node.summary&&selectedConnection.edge.explanation!==selectedConnection.node.summary&&<div className="mt-4"><p className="text-xs font-black uppercase tracking-wide text-slate-400">Topic overview</p><p className="mt-2 leading-7 text-slate-700">{selectedConnection.node.summary}</p></div>}<div className="mt-6 flex gap-3"><button onClick={()=>setSheetOpen(false)} className="flex-1 rounded-full border border-slate-300 px-5 py-3 font-black text-slate-700">Close</button><button onClick={()=>travel(selectedConnection)} className="flex-1 rounded-full bg-indigo-600 px-5 py-3 font-black text-white">Explore topic →</button></div></div></div>}
 </div>;
}
