"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type Node={id:string;node_key:string;node_type:string;title:string;subtitle:string|null;summary:string|null;scripture_reference:string|null};
type Edge={id:string;source_node_id:string;target_node_id:string;relationship_key:string;explanation:string|null;weight:number};
type OrbitNode={node:Node;edge:Edge;x:number;y:number;ring:number};

export default function ScriptureGalaxy({nodeKey,userId}:{nodeKey:string;userId?:string}){
 const supabase=useMemo(()=>createClient(),[]),router=useRouter();
 const[center,setCenter]=useState<Node|null>(null),[orbitNodes,setOrbitNodes]=useState<OrbitNode[]>([]),[selected,setSelected]=useState<OrbitNode|null>(null),[visited,setVisited]=useState<Set<string>>(new Set()),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 async function load(){setLoading(true);setMessage("");const decoded=decodeURIComponent(nodeKey);const{data:root,error}=await supabase.from("emmaus_graph_nodes").select("id,node_key,node_type,title,subtitle,summary,scripture_reference").eq("node_key",decoded).eq("status","published").maybeSingle();if(error||!root){setMessage(error?.message??"Discovery not found.");setLoading(false);return}setCenter(root as Node);
 const{data:edges,error:edgeError}=await supabase.from("emmaus_graph_edges").select("id,source_node_id,target_node_id,relationship_key,explanation,weight").or(`source_node_id.eq.${root.id},target_node_id.eq.${root.id}`).eq("status","published").order("weight",{ascending:false}).limit(24);if(edgeError){setMessage(edgeError.message);setLoading(false);return}const rows=(edges??[]) as Edge[];const ids=[...new Set(rows.map(e=>e.source_node_id===root.id?e.target_node_id:e.source_node_id))];const{data:related}=ids.length?await supabase.from("emmaus_graph_nodes").select("id,node_key,node_type,title,subtitle,summary,scripture_reference").in("id",ids).eq("status","published"):{data:[]};const map=Object.fromEntries(((related??[]) as Node[]).map(n=>[n.id,n]));const arranged=arrange(rows.map(edge=>({edge,node:map[edge.source_node_id===root.id?edge.target_node_id:edge.source_node_id]})).filter(item=>item.node));setOrbitNodes(arranged);
 if(userId){const{data:sessions}=await supabase.from("emmaus_walk_sessions").select("id").eq("user_id",userId);const sessionIds=(sessions??[]).map((s:any)=>s.id);if(sessionIds.length){const[{data:progress},{data:branches}]=await Promise.all([supabase.from("emmaus_walk_step_progress").select("step_id").in("session_id",sessionIds).eq("completed",true),supabase.from("emmaus_adaptive_branch_visits").select("source_node_id,target_node_id").in("session_id",sessionIds)]);const idsFromBranches=(branches??[]).flatMap((b:any)=>[b.source_node_id,b.target_node_id]);const stepIds=(progress??[]).map((p:any)=>p.step_id);const discovered=new Set<string>(idsFromBranches);if(stepIds.length){const{data:steps}=await supabase.from("emmaus_discovery_path_steps").select("graph_node_id").in("id",stepIds);for(const s of steps??[])discovered.add((s as any).graph_node_id)}setVisited(discovered)}}
 setLoading(false)}

 useEffect(()=>{void load()},[nodeKey,userId]);

 function travel(item:OrbitNode){router.push(`/emmaus/explore/${encodeURIComponent(item.node.node_key)}?from=${encodeURIComponent(center?.node_key??"")}&fromLabel=${encodeURIComponent(center?.title??"")}`)}
 if(loading)return <div className="rounded-[2rem] border border-slate-200 bg-white p-10 text-center font-black text-slate-500 shadow-xl">Rendering Scripture Galaxy...</div>;
 if(!center)return <div className="rounded-[2rem] border border-rose-200 bg-rose-50 p-10 text-center font-black text-rose-700">{message||"Discovery not found."}</div>;
 return <div className="grid gap-6 xl:grid-cols-[1fr_340px]">
  <section className="overflow-hidden rounded-[2rem] border border-slate-800 bg-slate-950 shadow-2xl"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 px-6 py-5 text-white"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-amber-300">Visual Scripture Galaxy</p><h1 className="mt-1 text-3xl font-black">{center.title}</h1></div><div className="rounded-full bg-white/10 px-4 py-2 text-sm font-black text-indigo-100">{orbitNodes.length} orbiting discoveries</div></div>
   <div className="overflow-auto bg-[radial-gradient(circle_at_center,rgba(79,70,229,.32),rgba(15,23,42,.96)_58%,#020617_100%)]"><svg width="1200" height="850" className="block"><defs><filter id="galaxyGlow"><feGaussianBlur stdDeviation="5" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>{orbitNodes.map(item=><g key={`line-${item.edge.id}`}><line x1="600" y1="425" x2={item.x} y2={item.y} stroke="rgba(129,140,248,.45)" strokeWidth={Math.max(1.5,Number(item.edge.weight)*1.4)}/><text x={(600+item.x)/2} y={(425+item.y)/2-8} fill="rgba(224,231,255,.72)" fontSize="10" textAnchor="middle">{item.edge.relationship_key.replaceAll("_"," ")}</text></g>)}
   <g transform="translate(600,425)" filter="url(#galaxyGlow)"><circle r="66" fill="#f59e0b" stroke="#fff7ed" strokeWidth="4"/><text y="-4" fill="#111827" fontSize="14" fontWeight="900" textAnchor="middle">{short(center.title,18)}</text><text y="16" fill="#78350f" fontSize="10" fontWeight="800" textAnchor="middle">{center.node_type.replaceAll("_"," ")}</text></g>
   {orbitNodes.map(item=><g key={item.edge.id} transform={`translate(${item.x},${item.y})`} onClick={()=>setSelected(item)} className="cursor-pointer" filter="url(#galaxyGlow)"><circle r={item.ring===1?38:31} fill={nodeColor(item.node.node_type)} stroke={visited.has(item.node.id)?"#fde68a":"#e0e7ff"} strokeWidth={visited.has(item.node.id)?5:2}/><text y="-3" fill="white" fontSize="10" fontWeight="900" textAnchor="middle">{short(item.node.title,14)}</text><text y="12" fill="rgba(255,255,255,.72)" fontSize="8" fontWeight="700" textAnchor="middle">{item.node.node_type.replaceAll("_"," ")}</text></g>)}</svg></div></section>
  <aside className="space-y-5"><section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-xl"><p className="text-xs font-black uppercase tracking-[0.16em] text-indigo-700">Center discovery</p><h2 className="mt-2 text-2xl font-black text-slate-950">{center.title}</h2>{center.scripture_reference&&<p className="mt-2 font-black text-indigo-700">{center.scripture_reference}</p>}<p className="mt-4 text-sm leading-6 text-slate-600">{center.summary}</p></section>
  <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-xl">{selected?<><p className="text-xs font-black uppercase tracking-[0.16em] text-indigo-700">Selected orbit</p><h2 className="mt-2 text-2xl font-black text-slate-950">{selected.node.title}</h2><p className="mt-2 text-xs font-black uppercase tracking-wide text-indigo-700">{selected.edge.relationship_key.replaceAll("_"," ")}</p>{selected.node.scripture_reference&&<p className="mt-3 font-black text-slate-700">{selected.node.scripture_reference}</p>}<p className="mt-4 text-sm leading-6 text-slate-600">{selected.edge.explanation??selected.node.summary}</p><button onClick={()=>travel(selected)} className="mt-5 w-full rounded-full bg-indigo-600 px-5 py-3 font-black text-white">Travel to this discovery →</button></>:<p className="text-sm leading-6 text-slate-500">Select any orbiting node to inspect the connection and travel deeper into Scripture.</p>}</section>
  <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-xl"><p className="text-xs font-black uppercase tracking-[0.16em] text-indigo-700">Legend</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs font-black text-slate-600">{["verse","passage","theme","person","place","event","discovery","language_term","question","book"].map(type=><div key={type} className="flex items-center gap-2"><span className="h-3 w-3 rounded-full" style={{background:nodeColor(type)}}/><span>{type.replaceAll("_"," ")}</span></div>)}</div><p className="mt-4 text-xs leading-5 text-slate-500">Gold outlines indicate discoveries already illuminated through the learner’s Walk history.</p></section><p className="min-h-5 text-sm font-bold text-slate-500">{message}</p></aside>
 </div>;
}

function arrange(items:{node:Node;edge:Edge}[]):OrbitNode[]{const sorted=[...items].sort((a,b)=>Number(b.edge.weight)-Number(a.edge.weight));return sorted.map((item,index)=>{const ring=index<8?1:2;const ringItems=ring===1?Math.min(8,sorted.length):Math.max(1,sorted.length-8);const ringIndex=ring===1?index:index-8;const radius=ring===1?205:335;const angle=(Math.PI*2*ringIndex)/ringItems-Math.PI/2+(ring===2?Math.PI/12:0);return{...item,x:600+Math.cos(angle)*radius,y:425+Math.sin(angle)*radius,ring}})}
function short(value:string,max:number){return value.length>max?`${value.slice(0,max-1)}…`:value}
function nodeColor(type:string){const map:Record<string,string>={verse:"#4f46e5",passage:"#4338ca",book:"#1d4ed8",theme:"#7c3aed",person:"#0f766e",place:"#0369a1",event:"#b45309",discovery:"#be123c",language_term:"#475569",question:"#c026d3",doctrine:"#9f1239",promise:"#15803d",command:"#b91c1c"};return map[type]??"#334155"}
