"use client";

import Link from "next/link";
import TestimonyTicker from "@/components/TestimonyTicker";

export default function TestimonyBoardPage(){return <main className="lfp-page pb-24">
 <section className="relative overflow-hidden"><div aria-hidden className="lfp-grid absolute inset-0"/><div aria-hidden className="lfp-orb -right-20 top-0 h-64 w-64 bg-violet-200/45"/><div className="lfp-shell relative py-12 sm:py-16"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div className="max-w-3xl"><p className="lfp-eyebrow">Testimony</p><h1 className="mt-3 text-4xl font-black tracking-[-.045em] text-slate-950 sm:text-6xl">Your story may be the hope <span className="lfp-gradient-text">someone else needs.</span></h1><p className="mt-5 text-lg leading-8 text-slate-600">Preserve stories of redemption, healing, perseverance, restored relationships, and the steady faithfulness of God.</p></div><Link href="/testimonies/submit" className="lfp-button lfp-button-primary"><span>＋</span> Share Your Story</Link></div></div></section>
 <div className="lfp-shell py-8 sm:py-12"><section className="grid gap-5 lg:grid-cols-[.72fr_1.28fr]"><aside className="space-y-4"><div className="lfp-card p-6"><p className="text-[11px] font-black uppercase tracking-[.16em] text-violet-700">Why testimony matters</p><h2 className="mt-2 text-2xl font-black text-slate-950">Someone else's remembered faithfulness can become today's courage.</h2><p className="mt-3 leading-7 text-slate-600">Testimony is not performance. It is remembering what God has done in a way that points people toward Him rather than toward us.</p></div><div className="rounded-[1.7rem] bg-[rgb(var(--lfp-ink))] p-6 text-white"><p className="text-[11px] font-black uppercase tracking-[.16em] text-sky-300">The complete journey</p><p className="mt-2 text-xl font-black">Need → Prayer → Praise → Testimony</p><p className="mt-2 text-sm leading-6 text-slate-300">The long-term L&F experience will keep these moments connected so the community can see the whole journey.</p></div></aside><section><p className="lfp-eyebrow">Stories of grace</p><h2 className="mt-2 text-3xl font-black tracking-tight text-slate-950">Real stories from real lives</h2><p className="mt-3 leading-7 text-slate-600">Take your time with these. They are not status updates; they are records of God's faithfulness.</p><div className="mt-6"><TestimonyTicker pageMode emptyMessage="No testimonies have been published yet. Your story could be the first."/></div></section></section></div>
 </main>}
