import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import PushPrompt from "@/components/PushPrompt";
import { ministryPortals } from "@/lib/ministry-hub";

const quick=[{href:"/prayer/submit",icon:"♡",label:"Ask for prayer",note:"Let someone carry this with you"},{href:"https://emmaus.lostandfoundproject.org",external:true,icon:"▤",label:"Open Emmaus",note:"Get back into the Word"},{href:"/praise",icon:"✦",label:"Share a praise",note:"Name what God is doing"},{href:"/discover",icon:"⌁",label:"Discover",note:"Find your next step"}];

export default async function DashboardPage(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/login");
 const now=new Date().toISOString();
 const [{data:profile},{data:memberships},{data:nextGathering},{data:latestContent}]=await Promise.all([
  supabase.from("profiles").select("full_name").eq("id",user.id).single(),
  supabase.from("ministry_memberships").select("ministry_slug,membership_role").eq("user_id",user.id),
  supabase.from("ministry_content").select("id,ministry_slug,title,summary,starts_at,location").eq("is_published",true).eq("content_type","gathering").gte("starts_at",now).order("starts_at",{ascending:true}).limit(1).maybeSingle(),
  supabase.from("ministry_content").select("id,ministry_slug,title,summary,content_type,created_at").eq("is_published",true).order("created_at",{ascending:false}).limit(1).maybeSingle()
 ]);
 const firstName=profile?.full_name?.trim().split(" ")[0]||"friend"; const followed=new Set((memberships??[]).map(m=>m.ministry_slug)); const followedPortals=ministryPortals.filter(m=>followed.has(m.slug)); const nextMinistry=nextGathering?ministryPortals.find(m=>m.slug===nextGathering.ministry_slug):null; const latestMinistry=latestContent?ministryPortals.find(m=>m.slug===latestContent.ministry_slug):null;
 return <main className="lfp-page pb-24">
  <section className="relative overflow-hidden"><div aria-hidden className="lfp-grid absolute inset-0"/><div aria-hidden className="lfp-orb -right-24 -top-20 h-72 w-72 bg-blue-200/50"/><div className="lfp-shell relative py-10 sm:py-14"><p className="lfp-eyebrow">My Path</p><div className="mt-3 grid gap-8 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div><h1 className="text-4xl font-black tracking-[-.045em] text-slate-950 sm:text-6xl">Good to see you, {firstName}.</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-600">Your home should answer one question: what is the next faithful thing you can do today?</p></div><div className="lfp-glass rounded-[1.7rem] p-5"><p className="text-[11px] font-black uppercase tracking-[.16em] text-blue-700">Today</p><p className="mt-2 text-xl font-black text-slate-950">You don't have to do everything.</p><p className="mt-1 text-sm leading-6 text-slate-600">Open Scripture. Carry one need. Encourage one person. Take one next step.</p></div></div>
   <div className="mt-8 grid grid-cols-2 gap-3 lg:grid-cols-4">{quick.map(q=>{const body=<><span className="text-xl text-blue-700">{q.icon}</span><span className="mt-3 block font-black text-slate-950">{q.label}</span><span className="mt-1 block text-xs leading-5 text-slate-500">{q.note}</span></>; return q.external?<a key={q.label} href={q.href} target="_blank" rel="noopener noreferrer" className="lfp-glass rounded-[1.4rem] p-4 transition hover:-translate-y-1">{body}</a>:<Link key={q.label} href={q.href} className="lfp-glass rounded-[1.4rem] p-4 transition hover:-translate-y-1">{body}</Link>})}</div></div></section>
  <div className="lfp-shell pb-14"><PushPrompt/>
   <section className="mt-8 grid gap-5 lg:grid-cols-[1.1fr_.9fr]">
    <div className="rounded-[2rem] bg-[rgb(var(--lfp-ink))] p-7 text-white shadow-2xl sm:p-8"><p className="text-[11px] font-black uppercase tracking-[.17em] text-sky-300">Up next</p>{nextGathering?<><h2 className="mt-3 text-3xl font-black">{nextGathering.title}</h2><p className="mt-3 font-bold text-slate-300">{nextMinistry?.title||"L&F"} · {new Date(nextGathering.starts_at).toLocaleString()}</p>{nextGathering.location&&<p className="mt-2 text-slate-400">{nextGathering.location}</p>}<Link href="/events" className="lfp-button mt-6 bg-white text-slate-950">View gathering →</Link></>:<><h2 className="mt-3 text-3xl font-black">Nothing scheduled? Your path is still active.</h2><p className="mt-3 leading-7 text-slate-300">Community doesn't begin and end with an event. Pray, study, encourage, or discover something new today.</p><Link href="/discover" className="lfp-button mt-6 bg-white text-slate-950">Discover a next step →</Link></>}</div>
    <div className="lfp-card p-7 sm:p-8"><p className="text-[11px] font-black uppercase tracking-[.17em] text-blue-700">Fresh from L&F</p>{latestContent?<><h2 className="mt-3 text-2xl font-black text-slate-950">{latestContent.title}</h2><p className="mt-2 text-sm font-bold text-slate-500">{latestMinistry?.title||"Ministry"} · {latestContent.content_type}</p>{latestContent.summary&&<p className="mt-3 leading-7 text-slate-600">{latestContent.summary}</p>}<Link href={`/ministries/${latestContent.ministry_slug}`} className="mt-5 inline-flex font-black text-blue-700">Open →</Link></>:<><h2 className="mt-3 text-2xl font-black text-slate-950">Your discovery stream starts here.</h2><p className="mt-3 leading-7 text-slate-600">As ministries publish resources and gatherings, the newest useful things will surface here automatically.</p><Link href="/discover" className="mt-5 inline-flex font-black text-blue-700">Explore →</Link></>}</div>
   </section>
   <section className="mt-12"><div className="flex items-end justify-between gap-4"><div><p className="lfp-eyebrow">My spaces</p><h2 className="mt-2 text-3xl font-black text-slate-950">Where you belong and grow</h2></div><Link href="/ministries" className="font-black text-blue-700">Manage →</Link></div><div className="mt-6 grid gap-4 md:grid-cols-3">{(followedPortals.length?followedPortals:ministryPortals).map(m=><Link key={m.slug} href={`/ministries/${m.slug}`} className="lfp-card p-6"><span className="text-2xl">{m.icon}</span><p className="mt-4 text-[11px] font-black uppercase tracking-[.16em] text-blue-700">{followed.has(m.slug)?"Your space":"Discover"}</p><h3 className="mt-1 text-2xl font-black text-slate-950">{m.title}</h3><p className="mt-2 leading-7 text-slate-600">{m.description}</p></Link>)}</div></section>
   <section className="mt-12 rounded-[2rem] border border-emerald-100 bg-emerald-50/70 p-7 sm:p-8"><p className="text-[11px] font-black uppercase tracking-[.17em] text-emerald-700">Community rhythm</p><h2 className="mt-2 text-3xl font-black text-slate-950">Prayer can become praise. Praise can become testimony.</h2><p className="mt-3 max-w-3xl leading-7 text-slate-600">L&F is being shaped around the whole story—not disconnected posts. Carry a need, return when something changes, celebrate God's faithfulness, and preserve the story for someone who needs hope later.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/prayer" className="lfp-button lfp-button-primary">Go to Prayer</Link><Link href="/community" className="lfp-button lfp-button-secondary">Community</Link></div></section>
  </div>
 </main>;
}
